### ISSUE TITLE
[其他]: 川虎助手问题

### ISSUE THREAD

**Issue by skystary** [GaiZhenbiao/ChuanhuChatGPT#1001]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 错误描述

提示：1 validation error for Tool args_schema subclass of BaseModel expected (type=type_error.subclass; expected_class=BaseModel)

PS：依赖都装完了，切换到川虎助手pro，又提示要安装numexpr（不知道是不是依赖写漏了）

PPS：部署安装依赖的时候遇到大量问题，始终解决不了，最后使用了虚拟环境才成功，但是虚拟环境又无法直接在配置中直接指定外服务器和端口，所以是修改了启动文件（还好有OpenAI帮忙）

### 复现操作

打开网页，切换模型为川虎助理，直接报错

### 错误日志

```shell
/home/ecs-user/ChuanhuChatGPT/myenv/lib/python3.11/site-packages/langchain/__init__.py:34: UserWarning: Importing PromptTemplate from langchain root module is no longer supported. Please use langchain.prompts.PromptTemplate instead.
  warnings.warn(
/home/ecs-user/ChuanhuChatGPT/myenv/lib/python3.11/site-packages/langchain/__init__.py:34: UserWarning: Importing LLMChain from langchain root module is no longer supported. Please use langchain.chains.LLMChain instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/ecs-user/ChuanhuChatGPT/modules/models/models.py", line 104, in get_model
    model = ChuanhuAgent_Client(model_name, access_key, user_name=user_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ecs-user/ChuanhuChatGPT/modules/models/ChuanhuAgent.py", line 86, in __init__
    Tool.from_function(
  File "/home/ecs-user/ChuanhuChatGPT/myenv/lib/python3.11/site-packages/langchain_core/tools.py", line 570, in from_function
    return cls(
           ^^^^
  File "/home/ecs-user/ChuanhuChatGPT/myenv/lib/python3.11/site-packages/langchain_core/tools.py", line 550, in __init__
    super(Tool, self).__init__(
  File "/home/ecs-user/ChuanhuChatGPT/myenv/lib/python3.11/site-packages/langchain_core/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "/home/ecs-user/ChuanhuChatGPT/myenv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Tool
args_schema
  subclass of BaseModel expected (type=type_error.subclass; expected_class=BaseModel)
```

### 运行环境

Python: 3.11.2  •  Gradio: 3.43.2  •  ChuanhuChat: [20231215]
OS: Windows11 22H2  •  Browser: Firefox

**Comment by wuzhichaoab** [comment]
我也遇到了这个问题，你是怎么解决的

**Comment by astorm-z** [comment]
+1

**Comment by GaiZhenbiao** [comment]
确实有问题，正在修复～

**Comment by pengtb** [comment]
same problem encountered in both manually installed & latest docker images. Falling back to docker image 20231110 solves the problem.

**Comment by pengtb** [comment]
[here](https://github.com/langchain-ai/langchain/issues/5974#issuecomment-1793656335) it is.
