### ISSUE TITLE
[本地部署] Error when execute: got an unexpected keyword argument 'ws_max_size'

### ISSUE THREAD

**Issue by hyyz17200** [GaiZhenbiao/ChuanhuChatGPT#101]
### 错误描述
Execute "python3 ChuanhuChatbot.py" gives me error. Failed to start.

### 复现操作
1. Setup the environment follows the Readme.  
2. Execute the command.

### 终端（控制台）中的错误报告
```console
/media/mydata/ChuanhuChatGPT# python3 ChuanhuChatbot.py
川虎的温馨提示：访问 http://localhost:7860 查看界面
Traceback (most recent call last):
  File "/media/mydata/ChuanhuChatGPT/ChuanhuChatbot.py", line 404, in <module>
    demo.queue().launch(share=False) # 改为 share=True 可以创建公开分享链接
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1397, in launch
    server_name, server_port, local_url, app, server = networking.start_server(
  File "/usr/local/lib/python3.9/dist-packages/gradio/networking.py", line 144, in start_server
    config = uvicorn.Config(
TypeError: __init__() got an unexpected keyword argument 'ws_max_size'
```

#### 桌面系统

 - OS: Debian 11

#### 运行依赖

- Gradio version: 3.20.0
- Python3 version: 3.9.2

**Comment by GaiZhenbiao** [comment]
请尝试升级gradio
