### ISSUE TITLE
[Bug]: 使用DALL-E3模型作图以后，再切换回gpt4进行文字交流，生成空白回复

### ISSUE THREAD

**Issue by Scolism** [GaiZhenbiao/ChuanhuChatGPT#1011]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

![11](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/43903287/446c0464-10d5-4b1d-9ffc-bb216095ddd2)
![微信图片_20231222203835](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/43903287/a3437e74-acd2-4185-865e-6551b108b7f1)

### 复现操作

第三方api进行操作，使用DALL-E3模型作图以后，再切换回gpt4进行文字交流，生成空白回复, 报错信息提示有json解析问题

### 错误日志

```shell
2023-12-22 20:28:11,609 [INFO] [models.py:39] 正在加载OpenAI模型: GPT4
2023-12-22 20:28:11,609 [INFO] [models.py:138] 模型设置为了： GPT4
2023-12-22 20:28:15,994 [INFO] [base_model.py:528] 用户louise的输入为：你好
JSON解析错误,收到的内容: {"error":{"message":"Bad Request\n (request id: 2023122220303462231090t0qgLNzc)","type":"invalid_request_error","param":"","code":2}}
Traceback (most recent call last):
  File "/www/wwwroot/cc.mio.cm/ChuanhuChatGPT/modules/models/base_model.py", line 598, in predict
    for chatbot, status_text in iter:
  File "/www/wwwroot/cc.mio.cm/ChuanhuChatGPT/modules/models/base_model.py", line 322, in stream_next_chatbot
    for partial_text in stream_iter:
  File "/www/wwwroot/cc.mio.cm/ChuanhuChatGPT/modules/models/OpenAI.py", line 46, in get_answer_stream_iter
    for i in iter:
  File "/www/wwwroot/cc.mio.cm/ChuanhuChatGPT/modules/models/OpenAI.py", line 222, in _decode_chat_response
    raise Exception(error_msg)
Exception: {"error":{"message":"Bad Request\n (request id: 2023122220303462231090t0qgLNzc)","type":"invalid_request_error","param":"","code":2}}
```

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by Scolism** [comment]
新版本已解决。
