### ISSUE TITLE
[本地部署]: 提示__init__() got an unexpected keyword argument 'proxy_ssl_context'

### ISSUE THREAD

**Issue by yzAnwen** [GaiZhenbiao/ChuanhuChatGPT#1012]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

更新了之后无法运行，提示：TypeError: __init__() got an unexpected keyword argument 'proxy_ssl_context'。请帮忙瞧瞧是什么问题。

### 复现操作

运行了run_Linux.sh，进行了更新。

### 错误日志

```shell
2023-12-24 06:57:40,924 [INFO] [utils.py:160] NumExpr defaulting to 1 threads.
2023-12-24 06:57:41,864 [INFO] [config.py:297] 默认模型设置为了：GPT4
Traceback (most recent call last):
  File "/usr/local/ChuanhuChatGPT/ChuanhuChatbot.py", line 9, in <module>
    from modules.train_func import *
  File "/usr/local/ChuanhuChatGPT/modules/train_func.py", line 7, in <module>
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
  File "/usr/local/lib/python3.9/site-packages/openai/_client.py", line 107, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 760, in __init__
    self._client = http_client or httpx.Client(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 682, in __init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[BaseTransport]] = {
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 685, in <dictcomp>
    else self._init_proxy_transport(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 739, in _init_proxy_transport
    return HTTPTransport(
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 149, in __init__
    self._pool = httpcore.HTTPProxy(
TypeError: __init__() got an unexpected keyword argument 'proxy_ssl_context'
```

### 运行环境

```markdown
- OS: CentOS 9
- Browser:Chrome
- Gradio version: 3.43.2
- Python version: python3.9
```

**Comment by mension** [comment]
代理的问题，估计是，我也遇到了，切换代理工具，解决了。具体原因没细纠

**Comment by mension** [comment]
@GaiZhenbiao 大佬瞅一下，换成最新包，其他环境会不会有影响，我的mac 用clash做proxy，换成最新包是ok的

**Comment by mension** [comment]
[https://github.com/encode/httpx/discussions/2893](HTTPProxy.__init__() got an unexpected keyword argument 'proxy_ssl_context')

**Comment by yzAnwen** [comment]
pip install --upgrade httpx
