### ISSUE TITLE
huggingface上部署后，提问时候，报错401 Authorization Required [远程部署]: 

### ISSUE THREAD

**Issue by leoncool23** [GaiZhenbiao/ChuanhuChatGPT#1047]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

huggingface上部署后，提问时候，报错401 Authorization Required，使用得是oneapi 中转的openai key 

### 复现操作

huggingface上部署后，提问时候，报错401 Authorization Required，使用得是oneapi 中转的openai key 

### 错误日志

```shell
401 Authorization Required
```

### 运行环境

- OS: 
- Server: 
- Gradio version: 
- Python version:

**Comment by leoncool23** [comment]
JSON解析错误,收到的内容: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
JSON解析错误,收到的内容: <html>
JSON解析错误,收到的内容: <head><title>401 Authorization Required</title></head>
JSON解析错误,收到的内容: <body>
JSON解析错误,收到的内容: <h1>401 Authorization Required</h1>
JSON解析错误,收到的内容: <p>This server could not verify that you are authorized to access the document requested.<hr/>Powered by Tengine</body>
JSON解析错误,收到的内容: </html>
Traceback (most recent call last):
  File "/home/user/app/modules/models/base_model.py", line 519, in predict
    for chatbot, status_text in iter:
  File "/home/user/app/modules/models/base_model.py", line 297, in stream_next_chatbot
    for partial_text in stream_iter:
  File "/home/user/app/modules/models/OpenAI.py", line 44, in get_answer_stream_iter
    for i in iter:
  File "/home/user/app/modules/models/OpenAI.py", line 221, in _decode_chat_response
    raise Exception(error_msg)
Exception: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>401 Authorization Required</title></head><body><h1>401 Authorization Required</h1><p>This server could not verify that you are authorized to access the document requested.<hr/>Powered by Tengine</body></html>
