### ISSUE TITLE
[Bug]:claude api报错 

### ISSUE THREAD

**Issue by ryanbai** [GaiZhenbiao/ChuanhuChatGPT#1068]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

2024-03-07 01:37:25,927 [INFO] [base_model.py:692] 回答为：^[[34m获取对话时发生错误，请查看后台日志: 'Anthropic' object has no attribute 'messages'^[[0m
Traceback (most recent call last):
  File "/home/azureuser/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/azureuser/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/azureuser/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/home/azureuser/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/azureuser/anaconda3/envs/py39/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/azureuser/anaconda3/envs/py39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/azureuser/anaconda3/envs/py39/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/home/azureuser/anaconda3/envs/py39/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/home/azureuser/anaconda3/envs/py39/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/home/azureuser/anaconda3/envs/py39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/azureuser/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "/home/azureuser/ChuanhuChatGPT/modules/utils.py", line 92, in auto_name_chat_history
    return current_model.auto_name_chat_history(*args)
  File "/home/azureuser/ChuanhuChatGPT/modules/models/base_model.py", line 961, in auto_name_chat_history
    return self.rename_chat_history(filename, chatbot)
  File "/home/azureuser/ChuanhuChatGPT/modules/models/base_model.py", line 938, in rename_chat_history
    self.delete_chat_history(self.history_file_path)
  File "/home/azureuser/ChuanhuChatGPT/modules/models/base_model.py", line 1088, in delete_chat_history
    if not filename.endswith(".json"):
AttributeError: 'NoneType' object has no attribute 'endswith'

### 复现操作

填写claude的key，重启。选择claude模型，输入对话内容，之后报错

### 运行环境

- OS:  Ubuntu
- Browser: chrome
- Gradio version: 
- Python version:  3.9

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
需要更新anthropic：
```
pip install anthropic==0.18.1
```

**Comment by GaiZhenbiao** [comment]
这个问题看上去不是claude引起的，反而像是此前有过的一个bug。请拉取最新版本，并安装requirements.txt

**Comment by ryanbai** [comment]
更新并安装requirements后ok了，多谢。
