### ISSUE TITLE
[远程部署]:  start error

### ISSUE THREAD

**Issue by themass** [GaiZhenbiao/ChuanhuChatGPT#1072]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

root@ecs-wYF2x3:~/work/ChuanhuChatGPT# python ChuanhuChatbot.py 
2024-03-09 15:47:01,596 [INFO] [_client.py:1026] HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
2024-03-09 15:47:03,126 [INFO] [font_manager.py:1578] generated new fontManager
Traceback (most recent call last):
  File "/root/work/ChuanhuChatGPT/ChuanhuChatbot.py", line 8, in <module>
    from modules.models.models import get_model
  File "/root/work/ChuanhuChatGPT/modules/models/models.py", line 9, in <module>
    from modules import config
  File "/root/work/ChuanhuChatGPT/modules/config.py", line 9, in <module>
    from . import shared
  File "/root/work/ChuanhuChatGPT/modules/shared.py", line 1, in <module>
    from modules.presets import CHAT_COMPLETION_URL, BALANCE_API_URL, USAGE_API_URL, API_HOST, OPENAI_API_BASE, IMAGES_COMPLETION_URL
  File "/root/work/ChuanhuChatGPT/modules/presets.py", line 366, in <module>
    ).set(
      ^^^^
TypeError: Base.set() got an unexpected keyword argument 'chatbot_code_background_color_dark'

### 复现操作

安装 python 环境，
执行  python ChuanhuChatbot.py 

### 错误日志

```shell
root@ecs-wYF2x3:~/work/ChuanhuChatGPT# python ChuanhuChatbot.py 
2024-03-09 15:47:01,596 [INFO] [_client.py:1026] HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
2024-03-09 15:47:03,126 [INFO] [font_manager.py:1578] generated new fontManager
Traceback (most recent call last):
  File "/root/work/ChuanhuChatGPT/ChuanhuChatbot.py", line 8, in <module>
    from modules.models.models import get_model
  File "/root/work/ChuanhuChatGPT/modules/models/models.py", line 9, in <module>
    from modules import config
  File "/root/work/ChuanhuChatGPT/modules/config.py", line 9, in <module>
    from . import shared
  File "/root/work/ChuanhuChatGPT/modules/shared.py", line 1, in <module>
    from modules.presets import CHAT_COMPLETION_URL, BALANCE_API_URL, USAGE_API_URL, API_HOST, OPENAI_API_BASE, IMAGES_COMPLETION_URL
  File "/root/work/ChuanhuChatGPT/modules/presets.py", line 366, in <module>
    ).set(
      ^^^^
TypeError: Base.set() got an unexpected keyword argument 'chatbot_code_background_color_dark'
```

### 运行环境

- OS:  linux 
- Server: 
- Gradio version: 0.9
- Python version:  3.11

### 补充说明

dd

**Comment by GaiZhenbiao** [comment]
请安装 requirements.txt 中指定的版本。
```
pip install -r requirements.txt --upgrade
```
