### ISSUE TITLE
[Docker]: 部署时报错itsdangerous模块缺失，无法启动

### ISSUE THREAD

**Issue by zodiacg** [GaiZhenbiao/ChuanhuChatGPT#1077]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

拉取最新版镜像（20240310），启动时gradio报依赖缺失，无法启动（itsdangerous）

### 复现操作

1. 正常使用docker-compose部署
2. 服务无法启动

### 错误日志

```shell
2024-03-15 01:17:27,910 [INFO] [config.py:311] 默认模型设置为了：GPT3.5 Turbo
2024-03-15 01:17:28,690 [INFO] [gradio_patch.py:114] Overrided the gradio.oauth/logout route
/bin/sh: 1: git: not found
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/gradio/oauth.py", line 21, in attach_oauth
    from starlette.middleware.sessions import SessionMiddleware
  File "/root/.local/lib/python3.9/site-packages/starlette/middleware/sessions.py", line 5, in <module>
    import itsdangerous
ModuleNotFoundError: No module named 'itsdangerous'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/ChuanhuChatbot.py", line 811, in <module>
    logout_btn.click(
  File "/root/.local/lib/python3.9/site-packages/gradio/blocks.py", line 1538, in __exit__
    self.app = routes.App.create_app(self)
  File "/root/.local/lib/python3.9/site-packages/gradio/routes.py", line 285, in create_app
    attach_oauth(app)
  File "/root/.local/lib/python3.9/site-packages/gradio/oauth.py", line 23, in attach_oauth
    raise ImportError(
ImportError: Cannot initialize OAuth to due a missing library. Please run `pip install gradio[oauth]` or add `gradio[oauth]` to your requirements.txt file in order to install the required dependencies.
```

### 运行环境

- OS: Linux/amd64
- Docker version: 24.0.5
- Gradio version: 镜像内置
- Python version: 镜像内置

**Comment by R3n1ian9** [comment]
遇到了同样的问题

**Comment by yufeiyohi** [comment]
我也碰到了同样的问题，docker中没有安装相对应的python model

**Comment by C-Dragon8** [comment]
我也碰到了同样的问题，重新安装itsdangerous、gradio后仍报错。

**Comment by AsoulAva** [comment]
遇到了同样的问题

**Comment by ZZFFLL** [comment]
No matching distribution found for gradio[oauth]==3.44.0

**Comment by guyuhengand** [comment]
不会改docker包😭有时间麻烦更新一下docker包呀

**Comment by Keldos-Li** [comment]
发布新的release前，可以使用这个Docker包：[chuanhuchatgpt-72209a0](https://github.com/GaiZhenbiao/ChuanhuChatGPT/actions/runs/8360898381/artifacts/1342927532)

**Comment by WIIASD** [comment]
这个版本的镜像还能用： https://portainer.local.wiiasd.com/#!/2/docker/images/tuchuanhuhuhu~2Fchuanhuchatgpt%3A20240305

**Comment by Keldos-Li** [comment]
@ken0414 刚发了20240410版本，用新的版本试试吧~
