### ISSUE TITLE
[其他] 输入任何内容都会报错

### ISSUE THREAD

**Issue by slideslide** [GaiZhenbiao/ChuanhuChatGPT#112]
### 错误描述
> 输入任何内容都会报错

### 错误截图
>![image](https://user-images.githubusercontent.com/86949124/224355486-8daa2f58-2045-4340-ac17-270162b663f2.png)

```console
payload: {'model': 'gpt-3.5-turbo', 'messages': [{'role': 'system', 'content': 'You are a helpful assistant.'}, {'role': 'user', 'content': 'hi'}], 'temperature': 1, 'top_p': 1, 'n': 1, 'stream': True, 'presence_penalty': 0, 'frequency_penalty': 0}
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1035, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 972, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\ChuanhuChatGPT\ChuanhuChatGPT4\utils.py", line 40, in postprocess
    for i, (message, response) in enumerate(y):
ValueError: not enough values to unpack (expected 2, got 0)
```

### 其他
>   解决方法：删掉util中第44行的括号
                None if message is None else mdtex2html.convert((message)),
                None if message is None else mdtex2html.convert(message),
似乎并不能解决。

**Comment by Miloxing** [comment]
多谢提醒

**Comment by slideslide** [comment]
![image](https://user-images.githubusercontent.com/86949124/224357119-542d1a69-8e6f-45a9-a889-507805e3bbbb.png)
似乎并不能解决

**Comment by slideslide** [comment]
> 看Readme，应该是代理的问题

上面这个确实是代理问题，但是原issue的问题依旧没有解决。

**Comment by GaiZhenbiao** [comment]
请提供详细的复现步骤

**Comment by slideslide** [comment]
> 请提供详细的复现步骤
正常部署在Windows10 22H2本地后，发了hi就立即发生报错。

**Comment by slideslide** [comment]
在更新到截至发送为止的最新版本后依旧如此，同样的步骤，gradio尝试过重装，但依旧没有解决。
```console
payload: {'model': 'gpt-3.5-turbo', 'messages': [{'role': 'system', 'content': 'You are a helpful assistant.'}, {'role': 'user', 'content': 'hi'}], 'temperature': 1, 'top_p': 1, 'n': 1, 'stream': True, 'presence_penalty': 0, 'frequency_penalty': 0}
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1035, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 972, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\ChuanhuChatGPT\ChuanhuChatGPT6\utils.py", line 41, in postprocess
    for i, (message, response) in enumerate(y):
ValueError: not enough values to unpack (expected 2, got 0)
```
![image](https://user-images.githubusercontent.com/86949124/224463566-382eb351-a7fc-4ce8-9b0e-9834a0ddd53e.png)

**Comment by slideslide** [comment]
在什么都不输入的情况下Enter
```console
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 858, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\utils.py", line 448, in async_iteration
    return next(iterator)
  File "J:\bots\chatGPT\ChuanhuChatGPT1\utils.py", line 110, in predict
    messages[-1]['content'] = temp2['content']
IndexError: list index out of range
```

**Comment by slideslide** [comment]
token是可用的，但是为什么会返回为空呢？

**Comment by Keldos-Li** [comment]
有可能是空白的api_key.txt造成的（？）
参考：#115 #119

**Comment by GaiZhenbiao** [comment]
最新版应该修复了api_key.txt相关的bug了，拉取下试试？

**Comment by czrui99** [comment]
请问使用chatgpt的api接口是需要开代理吗

**Comment by slideslide** [comment]
> 有可能是空白的api_key.txt造成的（？） 参考：#115 #119
不应该，有填入内容的

**Comment by slideslide** [comment]
> 最新版应该修复了api_key.txt相关的bug了，拉取下试试？

已经是最新版本
