### ISSUE TITLE
启动后过一会就会停止

### ISSUE THREAD

**Issue by MAOKO1993** [GaiZhenbiao/ChuanhuChatGPT#113]
川虎的温馨提示：访问 http://localhost:7860 查看界面
Traceback (most recent call last):
  File "/Users/wangdi/Develop/ChuanhuChatGPT/ChuanhuChatbot.py", line 143, in <module>
    demo.queue().launch(share=False) # 改为 share=True 可以创建公开分享链接
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1460, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True.

**Comment by GaiZhenbiao** [comment]
请试着重装gradio
