### ISSUE TITLE
[本地部署]: ubuntu18.04本地部署遇到python问题

### ISSUE THREAD

**Issue by txarmux** [GaiZhenbiao/ChuanhuChatGPT#1156]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

python3.10 ChuanhuChatbot.py 运行出错

### 复现操作

正常本地部署，内容还没修改

### 错误日志

```shell
ubuntu@ubuntu:~/chatgpt-web$ python3.10 ChuanhuChatbot.py 
Traceback (most recent call last):
  File "/home/ubuntu/chatgpt-web/ChuanhuChatbot.py", line 10, in <module>
    from modules.overwrites import *
  File "/home/ubuntu/chatgpt-web/modules/overwrites.py", line 4, in <module>
    from llama_index import Prompt
ImportError: cannot import name 'Prompt' from 'llama_index' (unknown location)
2024-08-28 10:53:44,265 [INFO] [_client.py:1038] HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
ubuntu@ubuntu:~/chatgpt-web$
```

### 运行环境

```markdown
- OS: ubuntu18.04
- Browser: Edge
- Gradio version: 1.3.0
- Python version: 3.10
```

**Comment by GaiZhenbiao** [comment]
请使用最新的主线代码。你用的应该是很久之前的版本了
