### ISSUE TITLE
[Bug]: 有时出现空消息且页面无报错

### ISSUE THREAD

**Issue by hengyanqwe** [GaiZhenbiao/ChuanhuChatGPT#1177]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

![image](https://github.com/user-attachments/assets/bb3113b6-845e-45a8-bb56-553942345235)

### 复现操作

不断打开新对话跟gpt打招呼，有时就会出现

### 错误日志

```shell
2024-12-17 10:56:08,092 [INFO] [_client.py:1026] HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
2024-12-17 10:56:09,521 [INFO] [config.py:118] 已设置可用模型：['GPT3.5 Turbo', 'GPT-4o', 'o1-preview']
2024-12-17 10:56:09,521 [INFO] [config.py:123] 已添加额外的模型：[]
2024-12-17 10:56:09,521 [INFO] [config.py:202] OpenAI API Base set to: https://api.zhizengzeng.com/v1
2024-12-17 10:56:09,521 [INFO] [config.py:331] 默认模型设置为了：GPT3.5 Turbo
2024-12-17 10:56:10,612 [INFO] [utils.py:160] NumExpr defaulting to 1 threads.
fatal: detected dubious ownership in repository at '/home/ChuanhuChatGPT'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/ChuanhuChatGPT
fatal: detected dubious ownership in repository at '/home/ChuanhuChatGPT'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/ChuanhuChatGPT
2024-12-17 10:57:02,404 [INFO] [ChuanhuChatbot.py:506] Get User Name: chen_ql
2024-12-17 10:57:02,405 [INFO] [models.py:38] 正在加载 OpenAI 模型: GPT3.5 Turbo
2024-12-17 10:57:02,408 [INFO] [models.py:149] 模型设置为了： GPT3.5 Turbo
2024-12-17 10:59:22,113 [INFO] [models.py:38] 正在加载 OpenAI 模型: GPT-4o
2024-12-17 10:59:22,115 [INFO] [models.py:149] 模型设置为了： GPT-4o
2024-12-17 10:59:30,542 [INFO] [base_model.py:615] 用户chen_ql的输入为：[34m你好[0m
2024-12-17 10:59:32,372 [INFO] [base_model.py:703] 回答为：[34m你好！有什么我可以帮助你的吗？[0m
2024-12-17 10:59:32,372 [INFO] [base_model.py:709] Tokens per second：16.959412610912512
2024-12-17 10:59:37,105 [INFO] [base_model.py:615] 用户chen_ql的输入为：[34m你好[0m
Traceback (most recent call last):
  File "/home/ChuanhuChatGPT/modules/models/OpenAIVision.py", line 250, in _decode_chat_response
    finish_reason = chunk["finish_details"]
KeyError: 'finish_details'
Traceback (most recent call last):
  File "/home/ChuanhuChatGPT/modules/models/OpenAIVision.py", line 250, in _decode_chat_response
    finish_reason = chunk["finish_details"]
KeyError: 'finish_details'
Traceback (most recent call last):
  File "/home/ChuanhuChatGPT/modules/models/OpenAIVision.py", line 250, in _decode_chat_response
    finish_reason = chunk["finish_details"]
KeyError: 'finish_details'
Traceback (most recent call last):
  File "/home/ChuanhuChatGPT/modules/models/OpenAIVision.py", line 250, in _decode_chat_response
    finish_reason = chunk["finish_details"]
KeyError: 'finish_details'
Traceback (most recent call last):
  File "/home/ChuanhuChatGPT/modules/models/OpenAIVision.py", line 250, in _decode_chat_response
    finish_reason = chunk["finish_details"]
KeyError: 'finish_details'
Traceback (most recent call last):
  File "/home/ChuanhuChatGPT/modules/models/OpenAIVision.py", line 250, in _decode_chat_response
    finish_reason = chunk["finish_details"]
KeyError: 'finish_details'
Traceback (most recent call last):
  File "/home/ChuanhuChatGPT/modules/models/OpenAIVision.py", line 250, in _decode_chat_response
    finish_reason = chunk["finish_details"]
KeyError: 'finish_details'
Traceback (most recent call last):
  File "/home/ChuanhuChatGPT/modules/models/OpenAIVision.py", line 250, in _decode_chat_response
    finish_reason = chunk["finish_details"]
KeyError: 'finish_details'
Traceback (most recent call last):
  File "/home/ChuanhuChatGPT/modules/models/OpenAIVision.py", line 250, in _decode_chat_response
    finish_reason = chunk["finish_details"]
KeyError: 'finish_details'
Traceback (most recent call last):
  File "/home/ChuanhuChatGPT/modules/models/OpenAIVision.py", line 250, in _decode_chat_response
    finish_reason = chunk["finish_details"]
KeyError: 'finish_details'
Traceback (most recent call last):
  File "/home/ChuanhuChatGPT/modules/models/OpenAIVision.py", line 250, in _decode_chat_response
    finish_reason = chunk["finish_details"]
KeyError: 'finish_details'
2024-12-17 10:59:41,836 [INFO] [base_model.py:703] 回答为：[34m[0m
2024-12-17 10:59:41,836 [INFO] [base_model.py:709] Tokens per second：4.439494087378722
```

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by hengyanqwe** [comment]
提议：加一条browserconsole的配置，输出接收到的json信息，不然我都不好排查是川虎chat的原因还是api提供商的原因

**Comment by crosswk** [comment]
和已有的Bug1169、Bug1176是一样的，我按照Bug1169作者的描述，加了几行代码，暂时解决了这个问题。
