### ISSUE TITLE
not enough values to unpack

### ISSUE THREAD

**Issue by thewintersun** [GaiZhenbiao/ChuanhuChatGPT#120]
Loading template...
川虎的温馨提示：访问 http://localhost:7860 查看界面
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
chat_counter - 0
payload: {'model': 'gpt-3.5-turbo', 'messages': [{'role': 'system', 'content': 'You are a helpful assistant.'}, {'role': 'user', 'content': '你好'}], 'temperature': 1, 'top_p': 1, 'n': 1, 'stream': True, 'presence_penalty': 0, 'frequency_penalty': 0}
Traceback (most recent call last):
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 1035, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 972, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\code\git\ChuanhuChatGPT\utils.py", line 41, in postprocess
    for i, (message, response) in enumerate(y):
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by thewintersun** [comment]
怎么我一测试，全都是问题......

**Comment by thewintersun** [comment]
代理问题

**Comment by thewintersun** [comment]
代理问题

**Comment by MLP8934** [comment]
我也是这种问题，怎么解决嘞

**Comment by thewintersun** [comment]
> 我也是这种问题，怎么解决嘞

要翻墙才能连上openai的api接口
