### ISSUE TITLE
[本地部署] ReadTimeout

### ISSUE THREAD

**Issue by libiaoliang** [GaiZhenbiao/ChuanhuChatGPT#158]
### 错误描述
> 输入信息后报错，前天使用还没有任何问题

### 错误截图
![Uploading image.png…]()
![Uploading 屏幕截图 2023-03-15 182426.png…]()

### 终端（控制台）中的错误报告
> Traceback (most recent call last):
  File "F:\python\anaconda\envs\test\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "F:\python\anaconda\envs\test\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "F:\python\anaconda\envs\test\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "F:\python\anaconda\envs\test\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "F:\python\anaconda\envs\test\lib\http\client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "F:\python\anaconda\envs\test\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "F:\python\anaconda\envs\test\lib\ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "F:\python\anaconda\envs\test\lib\ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\python\anaconda\envs\test\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "F:\python\anaconda\envs\test\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "F:\python\anaconda\envs\test\lib\site-packages\urllib3\util\retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "F:\python\anaconda\envs\test\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
    raise value
  File "F:\python\anaconda\envs\test\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "F:\python\anaconda\envs\test\lib\site-packages\urllib3\connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "F:\python\anaconda\envs\test\lib\site-packages\urllib3\connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\python\anaconda\envs\test\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\python\anaconda\envs\test\lib\site-packages\gradio\blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "F:\python\anaconda\envs\test\lib\site-packages\gradio\blocks.py", line 858, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\python\anaconda\envs\test\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\python\anaconda\envs\test\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\python\anaconda\envs\test\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\python\anaconda\envs\test\lib\site-packages\gradio\utils.py", line 448, in async_iteration
    return next(iterator)
  File "C:\Users\Administrator\Desktop\中转\ChuanhuChatGPT-main\utils.py", line 194, in predict
    for chatbot, history, status_text, token_count in iter:
  File "C:\Users\Administrator\Desktop\中转\ChuanhuChatGPT-main\utils.py", line 138, in stream_predict
    response = get_response(openai_api_key, system_prompt, history, temperature, top_p, True)
  File "C:\Users\Administrator\Desktop\中转\ChuanhuChatGPT-main\utils.py", line 122, in get_response
    response = requests.post(API_URL, headers=headers, json=payload, stream=True, timeout=timeout)
  File "F:\python\anaconda\envs\test\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "F:\python\anaconda\envs\test\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "F:\python\anaconda\envs\test\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\python\anaconda\envs\test\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "F:\python\anaconda\envs\test\lib\site-packages\requests\adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=5)

```console)
```

#### 桌面系统
> **请填写以下列表：**

 - OS: [Windows10]
 - Browser: [edge]

#### 运行依赖
> **请填写以下列表：**
> 你可以在终端中依次输入以下指令以查看软件版本：
> ```shell
> pip show gradio:
> python --version
> ```
> （如果你使用Python3，请将`pip`替换为`pip3`，`python`替换为`python3`）

- Gradio version:3.20.1
- Python (或Python3) version:3.9.15

### 其他
api测试程序正常，api和网页版均能正常使用回复，前天还是正常，昨天没用，今天打开就是这样了

**Comment by libiaoliang** [comment]
urllib3版本1.25.11，代理能够正常使用，openai.com和127.0.0.1已经按要求添加

**Comment by tisoz** [comment]
我测下来好像是http那边没有实时返回数据 , 导致一条数据老长时间返回 , 这边没做兼容 , 等待更新吧

**Comment by libiaoliang** [comment]
更新新版本后不再报错，但是获取回答时间~非~常~~非~常~~慢~，期待跟新

**Comment by libiaoliang** [comment]
新版本情况不变，顺便发现新版本的小bug，选择模式后有时当前模式界面并不会变（有时又会变），但实质上是变了的，4.0的统一json错误，3.5的统一对话非常慢，建议优先把核心对话功能修复，只要核心功能正常其它的都是细枝末节![screenshot-127 0 0 1_7860-2023 03 16-15_12_48](https://user-images.githubusercontent.com/95110455/225543107-cbe9f8b7-7ea7-4b2d-a6c3-9f5ea244fc20.png)
![Uploading screenshot-127.0.0.1_7860-2023.03.16-15_12_48.png…]()

**Comment by GaiZhenbiao** [comment]
界面这个你升级最新版gradio就好了。
```
pip install -r requirements.txt --upgrade
```
对话速度方面，我用的时候感觉挺正常的，这可能和网络环境、问的时间之类有关。参考：#162

**Comment by libiaoliang** [comment]
我测试了一下，的确我这儿有问题，chatgpt本体我与它的对话速度非常快，代理速度也还行，但不知道为什么我本地编写了一个测试调用api连续对话的代码，竟然要平均25s才能收发消息，前几天都是正常的，请问你知道问题可能出在哪里吗？

**Comment by libiaoliang** [comment]
> > 我测试了一下，的确我这儿有问题，chatgpt本体我与它的对话速度非常快，代理速度也还行，但不知道为什么我本地编写了一个测试调用api连续对话的代码，竟然要平均25s才能收发消息，前几天都是正常的，请问你知道问题可能出在哪里吗？
> 
> 我也是 , 前几天正常 , 但是这两天对话异常慢 , api接口也确认走了代理 , 但是就是经常超时

是不是它对免费用户限流了。。。

**Comment by tisoz** [comment]
> > > 我测试了一下，的确我这儿有问题，chatgpt本体我与它的对话速度非常快，代理速度也还行，但不知道为什么我本地编写了一个测试调用api连续对话的代码，竟然要平均25s才能收发消息，前几天都是正常的，请问你知道问题可能出在哪里吗？
> > 
> > 
> > 我也是 , 前几天正常 , 但是这两天对话异常慢 , api接口也确认走了代理 , 但是就是经常超时
> 
> 是不是它对免费用户限流了。。。

我也在其他几个gpt项目测了api , 使用的自己的key , 有些是正常的 , 有些不正常 , 但我也没法确定是哪里的原因 , 所以目前很头疼

**Comment by libiaoliang** [comment]
> > > > 我测试了一下，的确我这儿有问题，chatgpt本体我与它的对话速度非常快，代理速度也还行，但不知道为什么我本地编写了一个测试调用api连续对话的代码，竟然要平均25s才能收发消息，前几天都是正常的，请问你知道问题可能出在哪里吗？
> > > 
> > > 
> > > 我也是 , 前几天正常 , 但是这两天对话异常慢 , api接口也确认走了代理 , 但是就是经常超时
> > 
> > 
> > 是不是它对免费用户限流了。。。
> 
> 我也在其他几个gpt项目测了API ， 使用的自己的key ， 有些是正常的 ， 有些不正常 ， 但我也没法确定是哪里的原因 ， 所以目前很头疼

狗openai，限流不明说，我绑定了张0.7美元余额的信用卡立刻就不卡了

**Comment by tisoz** [comment]
> 

暂不清楚原因 , 昨天卡的飞起 , 今天又不卡了 , 也没做充值之类的操作 , 推测是他们开发对stream续流出现了问题, 应该是官方bug .
今天已经可以正常使用了
