### ISSUE TITLE
[本地部署] ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by icocoon** [GaiZhenbiao/ChuanhuChatGPT#194]
### 错误描述
> 运行后网页会出现error，命令行中出现一些错误提示

### 复现操作
> 1. 正常完成本地部署
> 2. 在对话框中要求 ChatGPT “你能帮我做些什么”
> 3. ChatGPT 未输出任何内容，并提示 error

### 错误截图
> 
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/17640822/226072431-11460991-afc0-40a9-bcd5-779ff93216c0.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/17640822/226072454-08a09de7-9276-450f-ab2e-7b57e78e98b7.png">

### 终端（控制台）中的错误报告

```console
Traceback (most recent call last):
  File "/Users/heqing/Library/Python/3.9/lib/python/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/heqing/Library/Python/3.9/lib/python/site-packages/gradio/blocks.py", line 1059, in process_api
    result = await self.call_function(
  File "/Users/heqing/Library/Python/3.9/lib/python/site-packages/gradio/blocks.py", line 882, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/heqing/Library/Python/3.9/lib/python/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/heqing/Library/Python/3.9/lib/python/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/heqing/Library/Python/3.9/lib/python/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/heqing/Library/Python/3.9/lib/python/site-packages/gradio/utils.py", line 549, in async_iteration
    return next(iterator)
  File "/Users/heqing/ChuanhuChatGPT-main/utils.py", line 257, in predict
    for chatbot, history, status_text, all_token_counts in iter:
  File "/Users/heqing/ChuanhuChatGPT-main/utils.py", line 145, in stream_predict
    system_prompt_token_count = count_token(system_prompt)
  File "/Users/heqing/ChuanhuChatGPT-main/utils.py", line 57, in count_token
    encoding = tiktoken.get_encoding("cl100k_base")
  File "/Users/heqing/Library/Python/3.9/lib/python/site-packages/tiktoken/registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "/Users/heqing/Library/Python/3.9/lib/python/site-packages/tiktoken_ext/openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "/Users/heqing/Library/Python/3.9/lib/python/site-packages/tiktoken/load.py", line 115, in load_tiktoken_bpe
    return {
  File "/Users/heqing/Library/Python/3.9/lib/python/site-packages/tiktoken/load.py", line 117, in <dictcomp>
    for token, rank in (line.split() for line in contents.splitlines() if line)
ValueError: not enough values to unpack (expected 2, got 1)
```

#### 桌面系统
> **请填写以下列表：**

 - OS: macOS 12.6.3
 - Browser: Chrome

#### 运行依赖
> **请填写以下列表：**
> 你可以在终端中依次输入以下指令以查看软件版本：
> ```shell
> pip show gradio
> python --version
> ```
> （如果你使用Python3，请将`pip`替换为`pip3`，`python`替换为`python3`）

- Gradio version: 3.21.0
- Python (或Python3) version: 3.9.6

### 其他
> 甩进chatGPT里，解释如下：

在 tiktoken/load.py 文件的第 117 行代码中，line.split() 分割出来的结果不符合预期的长度，导致在生成字典时抛出了 ValueError 异常。

更具体地说，这是因为 line.split() 返回了一个长度为 1 的列表，而字典的生成器表达式要求每个元素都是长度为 2 的列表（即有两个值）。因此，该异常指出了一个文件格式错误，通常是因为文件中的某些行缺少必要的信息。

要修复此问题，您需要检查 tiktoken_ext/openai_public.py 中的 cl100k_base 函数和相关数据文件，以确保文件格式正确并且在加载文件时没有遗漏任何信息。

**Comment by Keldos-Li** [comment]
感谢反馈，不过还是希望您能提供原始的报错信息……最好能遵照我们issue模板的格式，提供页面截图与终端的报错输出……长一点也没有问题。

ChatGPT的解读或许有道理，但定位到的或许不是我们能解决或能帮您解决的问题的位置😂

一般来说，或许报错的最后几行可能会比较有价值，请在截图或复制时尽量带上。🤔

另外，烦请修改一下issue标题，替换其中的“简短的问题描述”为更能描述错误状态的短句。

**Comment by Keldos-Li** [comment]
好吧，首先请尝试重装一下`tiktoken`……
```shell
pip uninstall tiktoken
pip install --upgrade tiktoken
```

如果还是不行，可以再试着重装或更新其他依赖。

最后，记得拉取我们最新的脚本。

**Comment by Lonely-observer0** [comment]
我也是这个问题ValueError: not enough values to unpack (expected 2, got 1)，用最新的脚本，tiktoken==0.3.2，0.3.1，0.3都不行

**Comment by Keldos-Li** [comment]
需要检查代理问题。
