### ISSUE TITLE
本地部署提示报错：ImportError: cannot import name dataclass_transform

### ISSUE THREAD

**Issue by xuchaoyang123** [GaiZhenbiao/ChuanhuChatGPT#195]
环境是本地mac book  有py3环境

安装完依赖后 py3运行提示报错

(base) carl@P_CHAOYXU-MB0 ChuanhuChatGPT % python3 ChuanhuChatbot.py      

Traceback (most recent call last):
  File "ChuanhuChatbot.py", line 2, in <module>
    import gradio as gr
  File "/Users/carl/opt/anaconda3/lib/python3.8/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/Users/carl/opt/anaconda3/lib/python3.8/site-packages/gradio/components.py", line 32, in <module>
    from gradio import media_data, processing_utils, utils
  File "/Users/carl/opt/anaconda3/lib/python3.8/site-packages/gradio/processing_utils.py", line 21, in <module>
    from fastapi import UploadFile
  File "/Users/carl/opt/anaconda3/lib/python3.8/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/Users/carl/opt/anaconda3/lib/python3.8/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/Users/carl/opt/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/Users/carl/opt/anaconda3/lib/python3.8/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 41, in init pydantic.dataclasses
    # +---------+-----------------------------------------+
ImportError: cannot import name dataclass_transform

**Comment by xuchaoyang123** [comment]
找到了原因 和conda 虚拟环境有关系。已经解决。
conda activate py38
然后再 pip3 install -r requirements.txt
 python3  ChuanhuChatbot.py
