### ISSUE TITLE
docker部署时，设置代理后会报错

### ISSUE THREAD

**Issue by yyihuan** [GaiZhenbiao/ChuanhuChatGPT#200]
### 错误描述
 在容器内配置代理地址http_proxy和https_proxy时会报错
```console
Traceback (most recent call last):
  File "/app/ChuanhuChatbot.py", line 157, in <module>
    demo.queue().launch(server_name="0.0.0.0", server_port=7860, share=False)
  File "/root/.local/lib/python3.9/site-packages/gradio/blocks.py", line 1496, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True.
```

### 运行环境
> **请填写以下列表：**

- OS: [e.g. Linux Ubuntu]
- Docker version:  23.0.1
- Gradio version:  默认镜像版本
- Python (或Python3) version: 3.9（镜像内版本）

### 当前解决方式
增加no_proxy=“localhost, 127.0.0.1”

**Comment by GaiZhenbiao** [comment]
现在支持检测并使用环境变量里的HTTP_PROXY代理了
