### ISSUE TITLE
[其他] 自从4,5天前更新了版本之后基本请求就没有成功过

### ISSUE THREAD

**Issue by thewintersun** [GaiZhenbiao/ChuanhuChatGPT#203]
自从有一次UI做了比较大的改动的那个版本之后， 
后来实时请求的基本上就没有成功过。

但是用老的版本一直都是可以用的。

log如下：

### 错误描述
To create a public link, set `share=True` in `launch()`.
2023-03-18 22:41:30,250 [INFO] [utils.py:311] 输入为：112
2023-03-18 22:41:30,259 [INFO] [utils.py:340] 使用流式传输
2023-03-18 22:41:30,259 [INFO] [utils.py:164] 实时回答模式
2023-03-18 22:41:30,721 [INFO] [utils.py:180] 输入token计数: 20
Traceback (most recent call last):
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 858, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\utils.py", line 448, in async_iteration
    return next(iterator)
  File "D:\code\git\ChuanhuChatGPT\utils.py", line 352, in predict
    for chatbot, history, status_text, all_token_counts in iter:
  File "D:\code\git\ChuanhuChatGPT\utils.py", line 183, in stream_predict
    response = get_response(
  File "D:\code\git\ChuanhuChatGPT\utils.py", line 144, in get_response
    response = requests.post(
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
Keyboard interruption in main thread... closing server.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021E146548B0>
Traceback (most recent call last):
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
  File "C:\Users\luoluo\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed

**Comment by Keldos-Li** [comment]
如果环境一致，不太应该出现老版本成功而新版本不行的情形。更倾向于您可以参考这几个同类issue：
- #49 
- #25 
- https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/5#issuecomment-1454063453

**Comment by learnCodeON** [comment]
你可以尝试多换几个网络节点。

**Comment by Keldos-Li** [comment]
问题重复而久未回复，关闭了。
