### ISSUE TITLE
按教程配置了clash的yaml文件，还是一直回答不出来

### ISSUE THREAD

**Issue by 1205129045x** [GaiZhenbiao/ChuanhuChatGPT#242]
### 问题说明
我用同样api，换了个翻墙软件就能回答出来，再换回clash后就不行了
### 问题截图
![屏幕截图_20230321_100228](https://user-images.githubusercontent.com/50540240/226504149-3eba38ed-0d5b-46c3-871a-4b09937d81fe.png)
### 操作说明
- 我clash用的是rule模式，按教程把openai.com加入到了rules规则里面
![image](https://user-images.githubusercontent.com/50540240/226503308-57fd0b03-7dff-47a2-b398-ad345e2bbfc6.png)

### 错误代码
```console
Traceback (most recent call last):
  File "C:\Users\12051\AppData\Roaming\Python\Python38\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\12051\AppData\Roaming\Python\Python38\site-packages\gradio\blocks.py", line 1069, in process_api
    result = await self.call_function(
  File "C:\Users\12051\AppData\Roaming\Python\Python38\site-packages\gradio\blocks.py", line 892, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\12051\AppData\Roaming\Python\Python38\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\12051\AppData\Roaming\Python\Python38\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\12051\AppData\Roaming\Python\Python38\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\12051\AppData\Roaming\Python\Python38\site-packages\gradio\utils.py", line 549, in async_iteration
    return next(iterator)
  File "C:\Users\12051\Desktop\Syncthing共享文件夹\ChuanhuChatGPT-main\ChuanhuChatGPT-main\chat_func.py", line 304, in predict
    for chatbot, history, status_text, all_token_counts in iter:
  File "C:\Users\12051\Desktop\Syncthing共享文件夹\ChuanhuChatGPT-main\ChuanhuChatGPT-main\chat_func.py", line 125, in stream_predict
    response = get_response(
  File "C:\Users\12051\Desktop\Syncthing共享文件夹\ChuanhuChatGPT-main\ChuanhuChatGPT-main\chat_func.py", line 82, in get_response
    response = requests.post(
  File "C:\Users\12051\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\12051\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\12051\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\12051\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\12051\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F3FFFD7850>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
```

### 终端提示
![image](https://user-images.githubusercontent.com/50540240/226505931-a983e5cb-ec80-4c7d-9cf4-141fd792c5ef.png)

### 我的yaml配置文件
https://github.com/1205129045x/images/blob/main/glados.rocks_1205129045%40qq.yaml
有没有大佬可以帮我配置一下是不是我配置错了

**Comment by GaiZhenbiao** [comment]
新版本的脚本支持在初次载入的时候检测地区，你可以看看你的地区是什么。

**Comment by 1205129045x** [comment]
> 新版本的脚本支持在初次载入的时候检测地区，你可以看看你的地区是什么。

我按https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/180这里面操作system proxy选择http就好了

**Comment by 1205129045x** [comment]
> 新版本的脚本支持在初次载入的时候检测地区，你可以看看你的地区是什么。

为什么我问他问题的时候，他说是chat-gpt3，这个程序用的不是3.5吗

**Comment by 1205129045x** [comment]
> 新版本的脚本支持在初次载入的时候检测地区，你可以看看你的地区是什么。

我问他是chatgpt几的时候，为什么回答的是3，这个不是3.5吗
