### ISSUE TITLE
[本地部署] 提问的时候HTTPSConnectionPool错误

### ISSUE THREAD

**Issue by buf3** [GaiZhenbiao/ChuanhuChatGPT#247]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1069, in process_api
    result = await self.call_function(
  File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 892, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 549, in async_iteration
    return next(iterator)
  File "D:\gitlab\houduan\chatgpt\chat_func.py", line 321, in predict
    for chatbot, history, status_text, all_token_counts in iter:
  File "D:\gitlab\houduan\chatgpt\chat_func.py", line 130, in stream_predict
    response = get_response(
  File "D:\gitlab\houduan\chatgpt\chat_func.py", line 83, in get_response
    response = requests.post(
  File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLEr
ror(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

请看下错误，老是error  55555555555555

**Comment by GaiZhenbiao** [comment]
最新版代码加入了地区选择功能，你试试

**Comment by buf3** [comment]
> 

  File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='ipapi.co', port=443): Max retries exceeded with url: /json/ (Caused by SSLError(SSLEOFError(8, '
EOF occurred in violation of protocol (_ssl.c:997)')))

更新完代码运行错误成这个了

**Comment by buf3** [comment]
> 最新版代码加入了地区检测功能，你试试。看一下你的地区是什么

日本

**Comment by buf3** [comment]
> 最新版代码加入了地区检测功能，你试试。看一下你的地区是什么

{
    "ip": "3.112.212.131",
    "network": "3.112.192.0/18",
    "version": "IPv4",
    "city": "Tokyo",
    "region": "Tokyo",
    "region_code": "13",
    "country": "JP",
    "country_name": "Japan",
    "country_code": "JP",
    "country_code_iso3": "JPN",
    "country_capital": "Tokyo",
    "country_tld": ".jp",
    "continent_code": "AS",
    "in_eu": false,
    "postal": "140-0002",
    "latitude": 35.616978,
    "longitude": 139.745521,
    "timezone": "Asia/Tokyo",
    "utc_offset": "+0900",
    "country_calling_code": "+81",
    "currency": "JPY",
    "currency_name": "Yen",
    "languages": "ja",
    "country_area": 377835.0,
    "country_population": 126529100,
    "asn": "AS16509",
    "org": "AMAZON-02"
}

**Comment by hiki321** [comment]
我也报这个错，我是美国节点能正常用官网的chatgpt，但是川虎会检测为中国，然后请求和连接报错

**Comment by GaiZhenbiao** [comment]
> 我也报这个错，我是美国节点能正常用官网的chatgpt，但是川虎会检测为中国，然后请求和连接报错

应该还是没配置好。请查看readme中“SSL一直等待”部分的内容。

**Comment by xudong-zhu** [comment]
后来怎么解决的啊，我和你一样

**Comment by xudong-zhu** [comment]
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 393, in run_predict output = await app.get_blocks().process_api( File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1069, in process_api result = await self.call_function( File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 892, in call_function prediction = await anyio.to_thread.run_sync( File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync return await get_asynclib().run_sync_in_worker_thread( File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio_backends_asyncio.py", line 937, in run_sync_in_worker_thread return await future File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio_backends_asyncio.py", line 867, in run result = context.run(func, *args) File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 549, in async_iteration return next(iterator) File "D:\gitlab\houduan\chatgpt\chat_func.py", line 321, in predict for chatbot, history, status_text, all_token_counts in iter: File "D:\gitlab\houduan\chatgpt\chat_func.py", line 130, in stream_predict response = get_response( File "D:\gitlab\houduan\chatgpt\chat_func.py", line 83, in get_response response = requests.post( File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 115, in post return request("post", url, data=data, json=json, **kwargs) File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request resp = self.send(prep, **send_kwargs) File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send r = adapter.send(request, **kwargs) File "C:\Users\Fang\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 563, in send raise SSLError(e, request=request) requests.exceptions.SSLError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLEr ror(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
> 
> 请看下错误，老是error 55555555555555

后来怎么解决的，我和你一样
