### ISSUE TITLE
 No module named gradio

### ISSUE THREAD

**Issue by linbo0** [GaiZhenbiao/ChuanhuChatGPT#248]
### 错误描述
> 请简明描述该错误。
python ChuanhuChatbot.py
Traceback (most recent call last):
  File "ChuanhuChatbot.py", line 6, in <module>
    import gradio as gr
ImportError: No module named gradio

python3 ChuanhuChatbot.py
Traceback (most recent call last):
  File "ChuanhuChatbot.py", line 10, in <module>
    from overwrites import *
  File "/home/ubuntu/CCCGPT/ChuanhuChatGPT-main/overwrites.py", line 18, in <module>
    from docx import Document as DocxDocument
ModuleNotFoundError: No module named 'docx'

已尝试过重装gradio，还是一样

**Comment by GaiZhenbiao** [comment]
请拉取最新版代码。你这个版本的代码存在bug，有多余的依赖项。

**Comment by linbo0** [comment]
sudo git pull https://github.com/GaiZhenbiao/ChuanhuChatGPT.git main -f
From https://github.com/GaiZhenbiao/ChuanhuChatGPT
 * branch            main       -> FETCH_HEAD
Already up to date.

已按说明拉取了最新版本，然后还是报同样的错误
