### ISSUE TITLE
[云端部署]KeyError: 'country_name'

### ISSUE THREAD

**Issue by S-Donjuan** [GaiZhenbiao/ChuanhuChatGPT#250]
```console
Traceback (most recent call last):
  File "/root/ChuanhuChatGPT/ChuanhuChatbot.py", line 133, in <module>
    status_display = gr.Markdown(get_geoip(), elem_id="status_display")
                                 ^^^^^^^^^^^
  File "/root/ChuanhuChatGPT/utils.py", line 290, in get_geoip
    country = data['country_name']
              ~~~~^^^^^^^^^^^^^^^^
KeyError: 'country_name'

```

### 运行环境
- CentOS7.6
- Gradio version:3.23.0
- Python (或Python3) version:3.11.0

**Comment by phpmaple** [comment]
我是本地 macos M1 也是这个错误, docker 和 python 执行都是这个问题

**Comment by GaiZhenbiao** [comment]
> 我是本地 macos M1 也是这个错误, docker 和 python 执行都是这个问题

现在应该修复了。请拉取最新版代码。
