### ISSUE TITLE
[本地部署] 上传索引文件报错

### ISSUE THREAD

**Issue by Elaoed** [GaiZhenbiao/ChuanhuChatGPT#262]
### 错误描述
> 本地部署完成后，上传一个pdf文件，在上传索引文件的时候，代码报错，显示返回回来的Response为None. INFO:root:Response: None. 

### 错误截图
> 如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。

### 终端（控制台）中的错误报告
> 如果可以，请复制终端中的主要错误报告。

```console
INFO:root:Response: None
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/blocks.py", line 898, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/homebrew/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/homebrew/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/utils.py", line 549, in async_iteration
    return next(iterator)
  File "/Users/ren/Coding/ChuanhuChatGPT/chat_func.py", line 275, in predict
    history, chatbot, status_text = chat_ai(openai_api_key, index, inputs, history, chatbot)
  File "/Users/ren/Coding/ChuanhuChatGPT/llama_func.py", line 110, in chat_ai
    response, chatbot_display, status_text = ask_ai(
  File "/Users/ren/Coding/ChuanhuChatGPT/llama_func.py", line 176, in ask_ai
    new_response = ret_text + "\n----------\n" + "\n\n".join(nodes)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

#### 桌面系统
> **请填写以下列表：**

 - OS: Macos 13.2
 - Browser: Chrome

#### 运行依赖

- Gradio version: 3.23.0
- Python (或Python3) version: 3.10.8

### 其他
> 哦对了，代码走到了langchain三方插件里openapi.py里的169行 
```
 "You are trying to use a chat model. This way of initializing it is "
                "no longer supported. Instead, please use: "
                "`from langchain.chat_models import ChatOpenAI`"
```
> 于是我就顺便按照提示改了一下 返回了ChatOpenAI. 不搭噶，原先的代码也是这么报错的

**Comment by Keldos-Li** [comment]
请更新所有依赖：
```
pip install -r requirements.txt --upgrade
```

另外记得先换用官方源在执行pip install（如果之前使用别的镜像），更多问题可以参考[常见问题](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/常见问题)
