### ISSUE TITLE
[本地部署] requests.exceptions.ConnectionError 

### ISSUE THREAD

**Issue by zeng6868** [GaiZhenbiao/ChuanhuChatGPT#274]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后在空白行处填写信息~

### 错误描述
> mac系统，提示错误
   

### 复现操作
> 你之前干了什么，然后出现了错误呢？例如：
> 1. 按照本地部署步骤，下载最新zip文件解压，修改了main.py代码中的api
> 2. 终端输入了安装 requirement.txt 命令，安装完成
> 3. 输入python3 ChuanhuChatbot.py后，出现错误提示
### 错误截图
> 如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。

### 终端（控制台）中的错误报告
> 如果可以，请复制终端中的主要错误报告。

```console
zengxiaozeng@cengxiaocengdeMacBook-Pro ChuanhuChatGPT-main % python3 ChuanhuChatbot.py
INFO:root:获取模板文件名列表
INFO:root:获取文件名列表，目录为templates，文件类型为['.csv', 'json']，是否为纯文本列表True
INFO:root:加载模板文件1 中文Prompts.json，模式为2（0为返回字典和下拉菜单，1为返回下拉菜单，2为返回字典）
INFO:root:Loading template...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x170278130>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ipapi.co', port=443): Max retries exceeded with url: /json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x170278130>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zengxiaozeng/chuanhugpt/ChuanhuChatGPT-main/ChuanhuChatbot.py", line 133, in <module>
    status_display = gr.Markdown(get_geoip(), elem_id="status_display")
  File "/Users/zengxiaozeng/chuanhugpt/ChuanhuChatGPT-main/utils.py", line 340, in get_geoip
    response = requests.get('https://ipapi.co/json/', timeout=5)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ipapi.co', port=443): Max retries exceeded with url: /json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x170278130>: Failed to establish a new connection: [Errno 61] Connection refused'))

```

#### 桌面系统
> **请填写以下列表：**

 - OS: [Macos ventura 13.2.1]
 - Browser: [edge]

#### 运行依赖
> **请填写以下列表：**
> 你可以在终端中依次输入以下指令以查看软件版本：
> ```shell
> pip show gradio
> python --version
> ```
> （如果你使用Python3，请将`pip`替换为`pip3`，`python`替换为`python3`）

- Gradio version:     3.23.0
- Python (或Python3) version:     3.10.8

### 其他
> 补充说明

**Comment by GaiZhenbiao** [comment]
看readme
