### ISSUE TITLE
[本地部署] 挂梯子与不挂梯子都出错

### ISSUE THREAD

**Issue by Crx0816** [GaiZhenbiao/ChuanhuChatGPT#285]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后在空白行处填写信息~

### 错误描述
> 请简明描述该错误。另外，请注意替换issue标题中的“简短的错误描述”。
挂梯子与不挂梯子都出错
### 复现操作
> 你之前干了什么，然后出现了错误呢？例如：
> 1. 正常完成本地部署
> 2. 在对话框中要求 ChatGPT “以LaTeX格式输出三角函数”
> 3. ChatGPT 输出部分内容后程序被自动终止
运行的时候报ERROR
### 错误截图
> 如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。
界面报错：
![image](https://user-images.githubusercontent.com/112409516/226808298-2209f953-9f90-4921-885d-774e1f2be111.png)

不挂梯子的时候报错如下：
![image](https://user-images.githubusercontent.com/112409516/226808184-901f81b1-36dd-4fa0-8e29-1462ffad66e8.png)

挂梯子的时候报错如下：
![image](https://user-images.githubusercontent.com/112409516/226809230-9bd61af9-1cdc-40c5-9835-056e0d391180.png)

### 终端（控制台）中的错误报告
> 如果可以，请复制终端中的主要错误报告。

```console
INFO:root:重试中……
INFO:root:重试完毕
INFO:root:输入为：你好
INFO:root:使用流式传输
INFO:root:实时回答模式
INFO:root:输入token计数: 21
Traceback (most recent call last):
  File "E:\Anaconda\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Anaconda\lib\site-packages\gradio\blocks.py", line 1069, in process_api
    result = await self.call_function(
  File "E:\Anaconda\lib\site-packages\gradio\blocks.py", line 892, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Anaconda\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Anaconda\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Anaconda\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Anaconda\lib\site-packages\gradio\utils.py", line 549, in async_iteration
    return next(iterator)
  File "F:\脚本\ChuanhuChatGPT\chat_func.py", line 414, in retry
    for x in iter:
  File "F:\脚本\ChuanhuChatGPT\chat_func.py", line 329, in predict
    for chatbot, history, status_text, all_token_counts in iter:
  File "F:\脚本\ChuanhuChatGPT\chat_func.py", line 133, in stream_predict
    response = get_response(
  File "F:\脚本\ChuanhuChatGPT\chat_func.py", line 85, in get_response
    response = requests.post(
  File "E:\Anaconda\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "E:\Anaconda\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "E:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "E:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "E:\Anaconda\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "E:\Anaconda\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "E:\Anaconda\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "E:\Anaconda\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "E:\Anaconda\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Anaconda\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname
INFO:root:重试中……
INFO:root:重试完毕
INFO:root:输入为：你好
INFO:root:使用流式传输
INFO:root:实时回答模式
INFO:root:输入token计数: 21
Traceback (most recent call last):
  File "E:\Anaconda\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "E:\Anaconda\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "E:\Anaconda\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
```

#### 桌面系统
> **请填写以下列表：**

 - Windows10
 - Chrome

#### 运行依赖
> **请填写以下列表：**
> 你可以在终端中依次输入以下指令以查看软件版本：
> ```shell
> pip show gradio
> python --version
> ```
> （如果你使用Python3，请将`pip`替换为`pip3`，`python`替换为`python3`）

- Gradio version: 3.22.1
- Python (或Python3) version: 3.8.8

### 其他
> 补充说明
有点进退两难....
主机连接没反应显然是没挂梯子无法连接，ValueError: check_hostname requires server_hostname这个的解决方案又是把梯子关了。

**Comment by GaiZhenbiao** [comment]
请查看readme中关于代理的部分。
