### ISSUE TITLE
[本地部署] window环境下 启动报错 ImportError: cannot import name 'BaseOutputParser' from 'langchain.output_parsers'

### ISSUE THREAD

**Issue by q751654992** [GaiZhenbiao/ChuanhuChatGPT#314]
> 感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
> 请务必先查看 README 中是否已经对您的问题做出了解答。如果没有，请检索issue，查看有没有相同或类似的问题。如果您确信这是一个前人没有遇到的问题，欢迎提交该issue！注意，请编辑issue标题栏“简短的错误描述”部分，也请替换我们的issue模板中的原文。
> 如果您想问的是 `Something went wrong Expecting value: line 1 column 1 (char 0)`，请再好好看一遍 README！！

### 错误描述
window环境下 启动报错

### 复现操作
双击chatgpt - windows.bat

### 错误截图
如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。

### 终端（控制台）中的错误报告
```console
Traceback (most recent call last):
  File "L:\AI\chatgpt\ChuanhuChatGPT\ChuanhuChatbot.py", line 10, in <module>
    from overwrites import *
  File "L:\AI\chatgpt\ChuanhuChatGPT\overwrites.py", line 4, in <module>
    from llama_index import Prompt
  File "L:\AI\Python310\lib\site-packages\llama_index\__init__.py", line 18, in <module>
    from llama_index.indices.common.struct_store.base import SQLDocumentContextBuilder
  File "L:\AI\Python310\lib\site-packages\llama_index\indices\__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "L:\AI\Python310\lib\site-packages\llama_index\indices\keyword_table\__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "L:\AI\Python310\lib\site-packages\llama_index\indices\keyword_table\base.py", line 16, in <module>
    from llama_index.indices.base import DOCUMENTS_INPUT, BaseGPTIndex
  File "L:\AI\Python310\lib\site-packages\llama_index\indices\base.py", line 23, in <module>
    from llama_index.indices.prompt_helper import PromptHelper
  File "L:\AI\Python310\lib\site-packages\llama_index\indices\prompt_helper.py", line 12, in <module>
    from llama_index.langchain_helpers.chain_wrapper import LLMPredictor
  File "L:\AI\Python310\lib\site-packages\llama_index\langchain_helpers\chain_wrapper.py", line 6, in <module>
    from llama_index.llm_predictor.base import (  # noqa: F401
  File "L:\AI\Python310\lib\site-packages\llama_index\llm_predictor\__init__.py", line 4, in <module>
    from llama_index.llm_predictor.base import LLMPredictor
  File "L:\AI\Python310\lib\site-packages\llama_index\llm_predictor\base.py", line 15, in <module>
    from llama_index.prompts.base import Prompt
  File "L:\AI\Python310\lib\site-packages\llama_index\prompts\__init__.py", line 3, in <module>
    from llama_index.prompts.base import Prompt
  File "L:\AI\Python310\lib\site-packages\llama_index\prompts\base.py", line 11, in <module>
    from llama_index.output_parsers.base import BaseOutputParser
  File "L:\AI\Python310\lib\site-packages\llama_index\output_parsers\__init__.py", line 4, in <module>
    from llama_index.output_parsers.langchain import LangchainOutputParser
  File "L:\AI\Python310\lib\site-packages\llama_index\output_parsers\langchain.py", line 6, in <module>
    from langchain.output_parsers import BaseOutputParser as LCOutputParser
ImportError: cannot import name 'BaseOutputParser' from 'langchain.output_parsers' (L:\AI\Python310\lib\site-packages\langchain\output_parsers\__init__.py)
```

#### 桌面系统
**请填写以下列表：**

 - OS: Windows10
 - Browser: Chrome

#### 运行依赖
**请填写以下列表：**
> 你可以在终端中依次输入以下指令以查看软件版本：
> ```shell
> pip show gradio
>
```
Name: gradio
Version: 3.22.1
Summary: Python library for easily interacting with trained machine learning models
Home-page:
Author:
Author-email: Abubakar Abid <team@gradio.app>, Ali Abid <team@gradio.app>, Ali Abdalla <team@gradio.app>, Dawood Khan <team@gradio.app>, Ahsen Khaliq <team@gradio.app>, Pete Allen <team@gradio.app>, Ömer Faruk Özdemir <team@gradio.app>
License:
Location: l:\ai\python310\lib\site-packages
Requires: aiofiles, aiohttp, altair, fastapi, ffmpy, fsspec, httpx, huggingface-hub, jinja2, markdown-it-py, markupsafe, matplotlib, mdit-py-plugins, numpy, orjson, pandas, pillow, pydantic, pydub, python-multipart, pyyaml, requests, typing-extensions, uvicorn, websockets
Required-by:
```
> python --version
>
```
Python 3.10.10
```
> （如果你使用Python3，请将`pip`替换为`pip3`，`python`替换为`python3`）

- Gradio version:
- Python (或Python3) version:

### 其他
补充说明

**Comment by LibreJiayi** [comment]
我也是这个问题

**Comment by cuifeiran** [comment]
同上

**Comment by Keldos-Li** [comment]
你们都知道同上了还发新issue🥲，还有一个不改issue标题的🥲

**Comment by elonzh** [comment]
把 `requirements.txt` 中 `langchain` 改为 `langchain<0.0.119` 重新安装依赖即可。[新版 langchain](https://github.com/hwchase17/langchain/commit/ce5d97bcb3e263f6aa69da6c334e35e20bf4db11) 修改了包结构

**Comment by wolovejing** [comment]
> 把 `requirements.txt` 中 `langchain` 改为 `langchain<0.0.119` 重新安装依赖即可。[新版 langchain](https://github.com/hwchase17/langchain/commit/ce5d97bcb3e263f6aa69da6c334e35e20bf4db11) 修改了包结构

这个正确

**Comment by Vita0519** [comment]
Traceback (most recent call last):
  File "C:\Users\15457\Desktop\川虎\ChuanhuChatGPT\ChuanhuChatbot.py", line 6, in <module>
    import gradio as gr
  File "D:\app\python\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "D:\app\python\lib\site-packages\gradio\components.py", line 21, in <module>
    import altair as alt
  File "D:\app\python\lib\site-packages\altair\__init__.py", line 4, in <module>
    from .vegalite import *
  File "D:\app\python\lib\site-packages\altair\vegalite\__init__.py", line 2, in <module>
    from .v4 import *
  File "D:\app\python\lib\site-packages\altair\vegalite\v4\__init__.py", line 2, in <module>
    from .schema import *
  File "D:\app\python\lib\site-packages\altair\vegalite\v4\schema\__init__.py", line 2, in <module>
    from .core import *
  File "D:\app\python\lib\site-packages\altair\vegalite\v4\schema\core.py", line 4, in <module>
    from altair.utils.schemapi import SchemaBase, Undefined, _subclasses
  File "D:\app\python\lib\site-packages\altair\utils\__init__.py", line 1, in <module>
    from .core import (
  File "D:\app\python\lib\site-packages\altair\utils\core.py", line 14, in <module>
    import pandas as pd
  File "D:\pycode\Lib\site-packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "D:\pycode\Lib\site-packages\pandas\compat\__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "D:\pycode\Lib\site-packages\pandas\compat\numpy\__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "D:\pycode\Lib\site-packages\pandas\util\__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "D:\pycode\Lib\site-packages\pandas\util\_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "D:\pycode\Lib\site-packages\pandas\_libs\__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
ModuleNotFoundError: No module named 'pandas._libs.interval'

**Comment by BIMiracle** [comment]
`pip3 install --upgrade langchain`

**Comment by sunjianan9900** [comment]
pip install langchain==0.0.116
pip install gradio==3.22.1

**Comment by q751654992** [comment]
> pip install langchain==0.0.116 pip install gradio==3.22.1

指定低版本的langchain 确实解决了问题

**Comment by q751654992** [comment]
issue 暂时先不关  估计还有其他人有这个问题, 可以从这里找到解决办法

**Comment by yqty** [comment]
在谷歌云 vps 部署提示
venv/bin/python3: can't find '__main__' module in '/www/wwwroot/ChuanhuChatGPT-main/

**Comment by ULHI-xin** [comment]
I met with this issue after upgrading `llama-index==0.5.0`.
My solution is to upgrade `langchain==0.0.125` as well.
Hope this could help.

**Comment by Keldos-Li** [comment]
现在llama-index和langchain都更新到最新版即可。
