### ISSUE TITLE
索引文件后报错“API key长度不是51位”

### ISSUE THREAD

**Issue by hallfay** [GaiZhenbiao/ChuanhuChatGPT#326]
### 复现操作
1. 正常完成本地部署
2. 正常对话没问题
3. 索引文件，问答直接出问题，ERROR。无法使用，然后就开始出现API key错误
### 终端（控制台）中的错误报告
如果可以，请复制终端中的主要错误报告。

```console
stderr: ERROR:    Exception in ASGI application
stderr: Traceback (most recent call last):
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/responses.py", line 335, in __call__
stderr:     stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
stderr:   File "/root/.local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
stderr:     return await get_asynclib().run_sync_in_worker_thread(
stderr:   File "/root/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
stderr:     return await future
stderr:   File "/root/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
stderr:     result = context.run(func, *args)
stderr: FileNotFoundError: [Errno 2] No such file or directory: './assets/favicon.png'
stderr: 
stderr: During handling of the above exception, another exception occurred:
stderr: 
stderr: Traceback (most recent call last):
stderr:   File "/root/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
stderr:     result = await app(  # type: ignore[func-returns-value]
stderr:   File "/root/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
stderr:     return await self.app(scope, receive, send)
stderr:   File "/root/.local/lib/python3.9/site-packages/fastapi/applications.py", line 276, in __call__
stderr:     await super().__call__(scope, receive, send)
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
stderr:     await self.middleware_stack(scope, receive, send)
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
stderr:     raise exc
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
stderr:     await self.app(scope, receive, _send)
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
stderr:     await self.app(scope, receive, send)
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
stderr:     raise exc
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
stderr:     await self.app(scope, receive, sender)
stderr:   File "/root/.local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
stderr:     raise e
stderr:   File "/root/.local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
stderr:     await self.app(scope, receive, send)
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
stderr:     await route.handle(scope, receive, send)
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
stderr:     await self.app(scope, receive, send)
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/routing.py", line 69, in app
stderr:     await response(scope, receive, send)
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/responses.py", line 338, in __call__
stderr:     raise RuntimeError(f"File at path {self.path} does not exist.")
stderr: RuntimeError: File at path ./assets/favicon.png does not exist.
stderr: INFO:root:输入为：[34mhi[0m
stderr: INFO:root:☹️发生了错误：API key长度不是51位，请检查是否输入正确。

```

**Comment by MZhao-ouo** [comment]
现在试试还有问题吗

**Comment by KingDariaDu** [comment]
复制的hugging face上的项目，也是同样的会报错，但是我不知道网页上如何下载log，在页面的右上角同样出现☹️发生了错误：API key长度不是51位，请检查是否输入正确。

> 现在试试还有问题吗

**Comment by Keldos-Li** [comment]
> 复制的hugging face上的项目，也是同样的会报错，但是我不知道网页上如何下载log，在页面的右上角同样出现☹️发生了错误：API key长度不是51位，请检查是否输入正确。

@KingDariaDu 请在网页中填入自己的api key。

**Comment by Keldos-Li** [comment]
我猜是当时/favicon.png的问题造成的……现在该没问题了……先关了……请尝试拉取我们脚本的更新。

如果仍有问题请继续在该ISSUE下回复~
