### ISSUE TITLE
直接ip:7860可以正常使用，但是反代域名的时候，填入key就报错，报错如图：

### ISSUE THREAD

**Issue by yangyzp** [GaiZhenbiao/ChuanhuChatGPT#327]
> 感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
> 如果您确信这是一个我们的 bug，而不是因为您的原因部署失败，欢迎提交该issue！如果您不能确定这是bug还是您的问题，请选择其他类型的issue模板。
> 注意，请编辑issue标题栏“简短的错误描述”部分，也请替换我们的issue模板中的原文。

### 错误描述
docker部署的。
直接ip:7860可以正常使用，但是反代域名的时候，填入key就报错，报错如图：
[
](https://s1.locimg.com/2023/03/23/2c30a9eaef31e.png)

### 复现操作
你之前干了什么，然后出现了bug呢？例如：
1. 正常完成本地部署
2. 在对话框中要求 ChatGPT “以LaTeX格式输出三角函数”
3. ChatGPT 输出部分内容后程序被自动终止

### 错误截图
如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。

### 终端（控制台）中的错误报告
如果可以，请复制终端中的主要错误报告。

```console
(请使用错误报告替换本行)
```

### 运行环境
**请填写以下列表：**

 - OS: [e.g. Windows11 22H2]
 - Browser: [e.g. Chrome, safari]
 - Gradio version:
 - Python (或Python3) version:

### 其他
补充说明

**Comment by hallfay** [comment]
和我的一样，用docker部署就是一直出现这个问题。重新输入也没用。

stderr: INFO:root:输入为：[34mhello[0m
stderr: INFO:root:☹️发生了错误：API key长度不是51位，请检查是否输入正确。
stderr: INFO:root:API密钥更改为了
stderr: INFO:root:API密钥更改为了sk-6*******************************************D5pL
stderr: INFO:root:输入为：[34mhello[0m
stderr: INFO:root:使用流式传输
stderr: INFO:root:实时回答模式
stderr: INFO:root:输入token计数: 7
stderr: INFO:root:传输完毕。当前token计数为[0, 7]
stderr: INFO:root:回答为：[34m[0m
stderr: INFO:root:输入为：[34mhello[0m
stderr: INFO:root:使用流式传输
stderr: INFO:root:实时回答模式
stderr: INFO:root:输入token计数: 7
stderr: 
0it [00:00, ?it/s]INFO:root:  "error": {
stderr: INFO:root:    "message": "'' is not of type 'object' - 'messages.2'",
stderr: INFO:root:    "type": "invalid_request_error",
stderr: INFO:root:    "param": null,
stderr: INFO:root:    "code": null
stderr: INFO:root:  }
stderr: INFO:root:}
stderr: 
8it [00:00, 156.73it/s]
stderr: INFO:root:传输完毕。当前token计数为[0, 7, 7]
stderr: INFO:root:回答为：[34m[0m
stderr: ERROR:    Exception in ASGI application
stderr: Traceback (most recent call last):
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/responses.py", line 335, in __call__
stderr:     stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
stderr:   File "/root/.local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
stderr:     return await get_asynclib().run_sync_in_worker_thread(
stderr:   File "/root/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
stderr:     return await future
stderr:   File "/root/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
stderr:     result = context.run(func, *args)
stderr: FileNotFoundError: [Errno 2] No such file or directory: './assets/favicon.png'
stderr: 
stderr: During handling of the above exception, another exception occurred:
stderr: 
stderr: Traceback (most recent call last):
stderr:   File "/root/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
stderr:     result = await app(  # type: ignore[func-returns-value]
stderr:   File "/root/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
stderr:     return await self.app(scope, receive, send)
stderr:   File "/root/.local/lib/python3.9/site-packages/fastapi/applications.py", line 276, in __call__
stderr:     await super().__call__(scope, receive, send)
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
stderr:     await self.middleware_stack(scope, receive, send)
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
stderr:     raise exc
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
stderr:     await self.app(scope, receive, _send)
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
stderr:     await self.app(scope, receive, send)
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
stderr:     raise exc
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
stderr:     await self.app(scope, receive, sender)
stderr:   File "/root/.local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
stderr:     raise e
stderr:   File "/root/.local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
stderr:     await self.app(scope, receive, send)
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
stderr:     await route.handle(scope, receive, send)
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
stderr:     await self.app(scope, receive, send)
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/routing.py", line 69, in app
stderr:     await response(scope, receive, send)
stderr:   File "/root/.local/lib/python3.9/site-packages/starlette/responses.py", line 338, in __call__
stderr:     raise RuntimeError(f"File at path {self.path} does not exist.")
stderr: RuntimeError: File at path ./assets/favicon.png does not exist.
stderr: INFO:root:输入为：[34mhello[0m
stderr: INFO:root:☹️发生了错误：API key长度不是51位，请检查是否输入正确。

**Comment by iskoldt-X** [comment]
https://github.com/GaiZhenbiao/ChuanhuChatGPT#%E5%85%A8%E7%A8%8B%E4%BD%BF%E7%94%A8docker-%E4%B8%BAchuanhuchatgpt-%E5%BC%80%E5%90%AFhttps

试试这个方法

**Comment by yangyzp** [comment]
> https://github.com/GaiZhenbiao/ChuanhuChatGPT#%E5%85%A8%E7%A8%8B%E4%BD%BF%E7%94%A8docker-%E4%B8%BAchuanhuchatgpt-%E5%BC%80%E5%90%AFhttps
> 
> 试试这个方法

你好，链接是不是有点问题？

**Comment by langhai8045** [comment]
@yangyzp 有没有可能是这个问题，我是这么解决的哈
<img width="980" alt="image" src="https://user-images.githubusercontent.com/4609696/227254872-e0cdc663-da33-4d7c-9e85-9a7913570abb.png">

**Comment by langhai8045** [comment]
> 

我是群晖NAS，准确来说就是反带配置的时候漏了俩配置，加上就好了
![image](https://user-images.githubusercontent.com/4609696/227412545-8fe30ff4-a3c0-47bd-9070-640671bb2019.png)

**Comment by Qwerty4401** [comment]
> 确来说就是反带配置的时候漏了俩配置，加上就好了

你好，我也是群辉NAS，截图中的配置是在哪里，我的系统是6.1.7。

**Comment by langhai8045** [comment]
> > 确来说就是反带配置的时候漏了俩配置，加上就好了
> 
> 你好，我也是群辉NAS，截图中的配置是在哪里，我的系统是6.1.7。

我是DSM7，你可以考虑在DSM6的基础上升级到6.2.1以上版本
![image](https://user-images.githubusercontent.com/4609696/227417646-d75fd7fe-d2ac-44b3-85e8-ae4c267e78b6.png)

**Comment by Qwerty4401** [comment]
> 

好的，感谢指导。

**Comment by Qwerty4401** [comment]
> > > 确来说就是反带配置的时候漏了俩配置，加上就好了
> > 
> > 
> > 你好，我也是群辉NAS，截图中的配置是在哪里，我的系统是6.1.7。
> 
> 我是DSM7，你可以考虑在DSM6的基础上升级到6.2.1以上版本 ![image](https://user-images.githubusercontent.com/4609696/227417646-d75fd7fe-d2ac-44b3-85e8-ae4c267e78b6.png)

好的，感谢指导。

**Comment by yangyzp** [comment]
搞定了，感谢各网友的帮助~~希望大佬项目越做越好，支持一个
