### ISSUE TITLE
[本地部署] 出现ProxyError错误

### ISSUE THREAD

**Issue by Owenfly** [GaiZhenbiao/ChuanhuChatGPT#345]
### 错误描述
运行报错

### 复现操作
1、git fetch 最新的代码后
2、运行出现如下错误

### 错误截图
![image](https://user-images.githubusercontent.com/55825205/227414500-b1ab018e-42be-499d-8d3b-55de56a80276.png)

### 终端（控制台）中的错误报告
Traceback (most recent call last):
  File "C:\Users\86158\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\86158\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\86158\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ipapi.co', port=443): Max retries exceeded with url: /json/ (Caused by ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:980: The handshake operation timed out')))

    response = requests.get('https://ipapi.co/json/', timeout=5)
  File "C:\Users\86158\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\86158\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\86158\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\86158\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\86158\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='ipapi.co', port=443): Max retries exceeded with url: /json/ (Caused by ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:980: The handshake operation timed out')))

#### 桌面系统
 - OS: Windows11 
 - Browser: Chrome

**Comment by zodrie40879** [comment]
我也遇到了

**Comment by zodrie40879** [comment]
这个原因是在腾讯云上，再运行了vpn，再运行requests.get('https://ipapi.co/json/', timeout=5)这段代码报的错，但是浏览器是可以访问这个网址的，具体原因未知！
