### ISSUE TITLE
[其他] 本地部署的时候，pycharm填写了代理的地址和端口，但是启动后IP依然在中国，导致无法正常对话

### ISSUE THREAD

**Issue by CobeBriant** [GaiZhenbiao/ChuanhuChatGPT#385]
> 感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
> 在一切开始之前，请确保您已经阅读过 [常见问题](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/常见问题) 页面，查看它是否已经对您的问题做出了解答。如果没有，请检索issue与discussion，查看有没有相同或类似的问题。
> 如果您确信这是一个前人没有遇到的问题，欢迎提交该issue！
> 注意，请编辑issue标题栏“简短的错误描述”部分，也请替换我们的issue模板中的正文（但不要把所有内容都删完）。

### 错误描述
Hi team, I ran into an issue of _"本地部署的时候，pycharm填写了代理的地址和端口，但是启动后IP依然在中国，导致无法正常对话"_
I pulled the original code from git, meanwhile, I started the VPN on my laptop. It was supposed to be effected when I set the proxy settings in Pycharm, but actually NO.
I have no idea what the problem is now.

### 复现操作
1. Turned off the firewall
2. Set up the proxy in Pycharm, while checking the proxy settings from System Preferences -> Network -> Advanced
3. Ran ChuanhuChatbot.py in Pycharm terminal, stocked 

### 错误截图
<img width="629" alt="image" src="https://user-images.githubusercontent.com/12833690/227713421-5b9f2195-a2b4-49c9-ba56-401606032dda.png">

### 终端（控制台）中的错误报告

```console
Traceback (most recent call last):
  File "/Users/brhon/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/brhon/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/brhon/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1337, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brhon/Library/Python/3.8/lib/python/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/brhon/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/brhon/Library/Python/3.8/lib/python/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=1080): Max retries exceeded with url: http://127.0.0.1:7860/startup-events (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brhon/PycharmProjects/ChuanhuChatGPT/ChuanhuChatbot.py", line 416, in <module>
    demo.queue(concurrency_count=CONCURRENT_COUNT).launch(
  File "/Users/brhon/Library/Python/3.8/lib/python/site-packages/gradio/blocks.py", line 1477, in launch
    requests.get(f"{self.local_url}startup-events")
  File "/Users/brhon/Library/Python/3.8/lib/python/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Users/brhon/Library/Python/3.8/lib/python/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/brhon/Library/Python/3.8/lib/python/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/brhon/Library/Python/3.8/lib/python/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/brhon/Library/Python/3.8/lib/python/site-packages/requests/adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=1080): Max retries exceeded with url: http://127.0.0.1:7860/startup-events (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

```

### 运行环境
**请填写以下列表：**

 - OS: macOS Catalina
 - Browser: Chrome
 - Gradio version: V-3.22.1
 - Python (或Python3) version: python3.8
 - Pycharm: PyCharm 2019.2.2 (Professional Edition)

### 其他
No

**Comment by GaiZhenbiao** [comment]
请自行解决代理问题。
