### ISSUE TITLE
[Docker] 国内环境部署时无法稳定运行

### ISSUE THREAD

**Issue by TheresaQWQ** [GaiZhenbiao/ChuanhuChatGPT#390]
### 错误描述
国内服务器配合代理运行时，受限于代理本身无法保证100%的稳定性，会出现大量 Read timed out 报错，会直接导致程序崩溃

### 复现操作
国内服务器或类似弱网环境部署可以稳定复现

### 错误截图
![image](https://user-images.githubusercontent.com/22370654/227721441-f5c69876-10d3-4b82-8ec3-4d2d50af2ee7.png)

### 终端（控制台）中的错误报告
如果可以，请复制终端中的主要错误报告。

```console
2023-03-25 13:51:41,828 [INFO] [utils.py:296] 获取模板文件名列表
2023-03-25 13:51:41,829 [INFO] [utils.py:248] 获取文件名列表，目录为templates，文件类型为['.csv', 'json']，是否为纯文本列表True
2023-03-25 13:51:41,830 [INFO] [utils.py:296] 获取模板文件名列表
2023-03-25 13:51:41,830 [INFO] [utils.py:248] 获取文件名列表，目录为templates，文件类型为['.csv', 'json']，是否为纯文本列表True
2023-03-25 13:51:41,832 [INFO] [utils.py:296] 获取模板文件名列表
2023-03-25 13:51:41,832 [INFO] [utils.py:248] 获取文件名列表，目录为templates，文件类型为['.csv', 'json']，是否为纯文本列表True
2023-03-25 13:51:41,833 [INFO] [utils.py:270] 加载模板文件1 中文Prompts.json，模式为1（0为返回字典和下拉菜单，1为返回下拉菜单，2为返回字典）
2023-03-25 13:51:41,833 [INFO] [utils.py:272] Loading template...
2023-03-25 13:51:41,880 [INFO] [utils.py:296] 获取模板文件名列表
2023-03-25 13:51:41,881 [INFO] [utils.py:248] 获取文件名列表，目录为templates，文件类型为['.csv', 'json']，是否为纯文本列表True
2023-03-25 13:51:41,881 [INFO] [utils.py:270] 加载模板文件1 中文Prompts.json，模式为1（0为返回字典和下拉菜单，1为返回下拉菜单，2为返回字典）
2023-03-25 13:51:41,881 [INFO] [utils.py:272] Loading template...
2023-03-25 13:51:41,910 [INFO] [utils.py:265] 获取历史记录文件名列表
2023-03-25 13:51:41,911 [INFO] [utils.py:248] 获取文件名列表，目录为history，文件类型为['.json']，是否为纯文本列表True
2023-03-25 13:51:41,911 [INFO] [utils.py:265] 获取历史记录文件名列表
2023-03-25 13:51:41,911 [INFO] [utils.py:248] 获取文件名列表，目录为history，文件类型为['.json']，是否为纯文本列表True
2023-03-25 13:51:41,962 [INFO] [ChuanhuChatbot.py:387] 
川虎的温馨提示：访问 http://localhost:7860 查看界面
Reloading javascript...
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/root/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/root/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/.local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/root/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/root/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/root/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='172.21.0.1', port=10809): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/ChuanhuChatbot.py", line 400, in <module>
    demo.queue(concurrency_count=CONCURRENT_COUNT).launch(
  File "/root/.local/lib/python3.9/site-packages/gradio/blocks.py", line 1513, in launch
    if _frontend and (not networking.url_ok(self.local_url)) and (not self.share):
  File "/root/.local/lib/python3.9/site-packages/gradio/networking.py", line 181, in url_ok
    r = requests.head(url, timeout=3, verify=False)
  File "/root/.local/lib/python3.9/site-packages/requests/api.py", line 100, in head
    return request("head", url, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='172.21.0.1', port=10809): Read timed out. (read timeout=3)
```

### 运行环境
本报错只与网络环境有关，与运行环境无关

**请填写以下列表：**

- OS: [e.g. Linux Ubuntu]
- Docker version:
- Gradio version:
- Python version:

### 其他
希望增加相应容错机制

**Comment by GaiZhenbiao** [comment]
从错误信息看不出错误是哪里导致的。
```
demo.queue(concurrency_count=CONCURRENT_COUNT).launch(
```
这一句出错，难道是Gradio的问题？好像不在本项目的能力范围内。

**Comment by TheresaQWQ** [comment]
抱歉我的问题，Gradio启动之后貌似会访问自己检查一遍有没有开起来，这个检查产生的请求也走了代理，访问失败之后就崩了，关掉之后就正常了
