### ISSUE TITLE
[Bug]: 提示No module named 'langchain.chat_models'

### ISSUE THREAD

**Issue by sheququan** [GaiZhenbiao/ChuanhuChatGPT#407]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue。

### 错误表现

D:\ChuanhuChatGPT\ChuanhuChatGPT>python ChuanhuChatbot.py
Traceback (most recent call last):
  File "ChuanhuChatbot.py", line 10, in <module>
    from modules.overwrites import *
  File "D:\ChuanhuChatGPT\ChuanhuChatGPT\modules\overwrites.py", line 4, in <module>
    from llama_index import Prompt
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\llama_index\__init__.py", line 18, in <module>
    from llama_index.indices.common.struct_store.base import SQLDocumentContextBuilder
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\llama_index\indices\__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\llama_index\indices\keyword_table\__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\llama_index\indices\keyword_table\base.py", line 16, in <module>
    from llama_index.indices.base import DOCUMENTS_INPUT, BaseGPTIndex
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\llama_index\indices\base.py", line 23, in <module>
    from llama_index.indices.prompt_helper import PromptHelper
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\llama_index\indices\prompt_helper.py", line 12, in <module>
    from llama_index.langchain_helpers.chain_wrapper import LLMPredictor
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\llama_index\langchain_helpers\chain_wrapper.py", line 6, in <module>
    from llama_index.llm_predictor.base import (  # noqa: F401
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\llama_index\llm_predictor\__init__.py", line 4, in <module>
    from llama_index.llm_predictor.base import LLMPredictor
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\llama_index\llm_predictor\base.py", line 10, in <module>
    from langchain.chat_models import ChatOpenAI
ModuleNotFoundError: No module named 'langchain.chat_models'

### 复现操作

正常本地部署执行

### 运行环境

```markdown
- OS: 
- Browser: 
- Gradio version: 
- Python version:
```

**Comment by KaiserLord** [comment]
我也遇到了相同的问题，没有很好的解决，求助

**Comment by GaiZhenbiao** [comment]
升级到最新版langchain就行了。

pip install langchain —upgrade

**Comment by Keldos-Li** [comment]
已在常见问题中更新

**Comment by TypicalSpider** [comment]
> 升级到最新版langchain就行了。
> 
> pip install langchain —upgrade

更新过仍然不行：
```shell
lee@VM-0-3-ubuntu:~/gptDemo01/ChuanhuChatGPT$ pip3 install langchain --upgrade
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: langchain in /home/lee/.local/lib/python3.8/site-packages (0.0.27)
Requirement already satisfied: pyyaml in /home/lee/.local/lib/python3.8/site-packages (from langchain) (6.0)
Requirement already satisfied: sqlalchemy in /home/lee/.local/lib/python3.8/site-packages (from langchain) (2.0.7)
Requirement already satisfied: pydantic in /home/lee/.local/lib/python3.8/site-packages (from langchain) (1.10.7)
Requirement already satisfied: requests in /home/lee/.local/lib/python3.8/site-packages (from langchain) (2.28.2)
Requirement already satisfied: numpy in /home/lee/.local/lib/python3.8/site-packages (from langchain) (1.24.2)
Requirement already satisfied: typing-extensions>=4.2.0 in /home/lee/.local/lib/python3.8/site-packages (from pydantic->langchain) (4.5.0)
Requirement already satisfied: idna<4,>=2.5 in /home/lee/.local/lib/python3.8/site-packages (from requests->langchain) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/lee/.local/lib/python3.8/site-packages (from requests->langchain) (3.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/lee/.local/lib/python3.8/site-packages (from requests->langchain) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/lee/.local/lib/python3.8/site-packages (from requests->langchain) (1.26.15)
Requirement already satisfied: greenlet!=0.4.17 in /home/lee/.local/lib/python3.8/site-packages (from sqlalchemy->langchain) (2.0.2)
lee@VM-0-3-ubuntu:~/gptDemo01/ChuanhuChatGPT$ python3 ChuanhuChatbot.py 
Traceback (most recent call last):
  File "ChuanhuChatbot.py", line 10, in <module>
    from modules.overwrites import *
  File "/home/lee/gptDemo01/ChuanhuChatGPT/modules/overwrites.py", line 4, in <module>
    from llama_index import Prompt
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/__init__.py", line 18, in <module>
    from llama_index.indices.common.struct_store.base import SQLDocumentContextBuilder
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/indices/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/indices/keyword_table/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/indices/keyword_table/base.py", line 16, in <module>
    from llama_index.indices.base import DOCUMENTS_INPUT, BaseGPTIndex
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/indices/base.py", line 23, in <module>
    from llama_index.indices.prompt_helper import PromptHelper
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/indices/prompt_helper.py", line 12, in <module>
    from llama_index.langchain_helpers.chain_wrapper import LLMPredictor
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/langchain_helpers/chain_wrapper.py", line 6, in <module>
    from llama_index.llm_predictor.base import (  # noqa: F401
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/llm_predictor/__init__.py", line 4, in <module>
    from llama_index.llm_predictor.base import LLMPredictor
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/llm_predictor/base.py", line 10, in <module>
    from langchain.chat_models import ChatOpenAI
ModuleNotFoundError: No module named 'langchain.chat_models'
```

**Comment by GaiZhenbiao** [comment]
那再更新下llama_index？

**Comment by TypicalSpider** [comment]
> 

好像不是这个llama_index的问题
```shell
lee@VM-0-3-ubuntu:~/gptDemo01/ChuanhuChatGPT$ pip3 install llama_index --upgrade
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: llama_index in /home/lee/.local/lib/python3.8/site-packages (0.4.39)
Requirement already satisfied: pandas in /home/lee/.local/lib/python3.8/site-packages (from llama_index) (1.5.3)
Requirement already satisfied: transformers in /home/lee/.local/lib/python3.8/site-packages (from llama_index) (4.27.3)
Requirement already satisfied: dataclasses-json in /home/lee/.local/lib/python3.8/site-packages (from llama_index) (0.5.7)
Requirement already satisfied: langchain in /home/lee/.local/lib/python3.8/site-packages (from llama_index) (0.0.27)
Requirement already satisfied: openai>=0.26.4 in /home/lee/.local/lib/python3.8/site-packages (from llama_index) (0.27.2)
Requirement already satisfied: numpy in /home/lee/.local/lib/python3.8/site-packages (from llama_index) (1.24.2)
Requirement already satisfied: tenacity<9.0.0,>=8.2.0 in /home/lee/.local/lib/python3.8/site-packages (from llama_index) (8.2.2)
Requirement already satisfied: aiohttp in /home/lee/.local/lib/python3.8/site-packages (from openai>=0.26.4->llama_index) (3.8.4)
Requirement already satisfied: tqdm in /home/lee/.local/lib/python3.8/site-packages (from openai>=0.26.4->llama_index) (4.65.0)
Requirement already satisfied: requests>=2.20 in /home/lee/.local/lib/python3.8/site-packages (from openai>=0.26.4->llama_index) (2.28.2)
Requirement already satisfied: marshmallow-enum<2.0.0,>=1.5.1 in /home/lee/.local/lib/python3.8/site-packages (from dataclasses-json->llama_index) (1.5.1)
Requirement already satisfied: typing-inspect>=0.4.0 in /home/lee/.local/lib/python3.8/site-packages (from dataclasses-json->llama_index) (0.8.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.3.0 in /home/lee/.local/lib/python3.8/site-packages (from dataclasses-json->llama_index) (3.19.0)
Requirement already satisfied: sqlalchemy in /home/lee/.local/lib/python3.8/site-packages (from langchain->llama_index) (2.0.7)
Requirement already satisfied: pydantic in /home/lee/.local/lib/python3.8/site-packages (from langchain->llama_index) (1.10.7)
Requirement already satisfied: pyyaml in /home/lee/.local/lib/python3.8/site-packages (from langchain->llama_index) (6.0)
Requirement already satisfied: pytz>=2020.1 in /home/lee/.local/lib/python3.8/site-packages (from pandas->llama_index) (2023.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/lee/.local/lib/python3.8/site-packages (from pandas->llama_index) (2.8.2)
Requirement already satisfied: filelock in /home/lee/.local/lib/python3.8/site-packages (from transformers->llama_index) (3.10.6)
Requirement already satisfied: packaging>=20.0 in /home/lee/.local/lib/python3.8/site-packages (from transformers->llama_index) (23.0)
Requirement already satisfied: regex!=2019.12.17 in /home/lee/.local/lib/python3.8/site-packages (from transformers->llama_index) (2023.3.23)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in /home/lee/.local/lib/python3.8/site-packages (from transformers->llama_index) (0.13.3)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /home/lee/.local/lib/python3.8/site-packages (from transformers->llama_index) (0.13.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/lee/.local/lib/python3.8/site-packages (from huggingface-hub<1.0,>=0.11.0->transformers->llama_index) (4.5.0)
Requirement already satisfied: six>=1.5 in /home/lee/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas->llama_index) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/lee/.local/lib/python3.8/site-packages (from requests>=2.20->openai>=0.26.4->llama_index) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/lee/.local/lib/python3.8/site-packages (from requests>=2.20->openai>=0.26.4->llama_index) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/lee/.local/lib/python3.8/site-packages (from requests>=2.20->openai>=0.26.4->llama_index) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/lee/.local/lib/python3.8/site-packages (from requests>=2.20->openai>=0.26.4->llama_index) (1.26.15)
Requirement already satisfied: mypy-extensions>=0.3.0 in /home/lee/.local/lib/python3.8/site-packages (from typing-inspect>=0.4.0->dataclasses-json->llama_index) (1.0.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/lee/.local/lib/python3.8/site-packages (from aiohttp->openai>=0.26.4->llama_index) (1.3.3)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/lee/.local/lib/python3.8/site-packages (from aiohttp->openai>=0.26.4->llama_index) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/lee/.local/lib/python3.8/site-packages (from aiohttp->openai>=0.26.4->llama_index) (1.8.2)
Requirement already satisfied: attrs>=17.3.0 in /home/lee/.local/lib/python3.8/site-packages (from aiohttp->openai>=0.26.4->llama_index) (22.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/lee/.local/lib/python3.8/site-packages (from aiohttp->openai>=0.26.4->llama_index) (6.0.4)
Requirement already satisfied: aiosignal>=1.1.2 in /home/lee/.local/lib/python3.8/site-packages (from aiohttp->openai>=0.26.4->llama_index) (1.3.1)
Requirement already satisfied: greenlet!=0.4.17 in /home/lee/.local/lib/python3.8/site-packages (from sqlalchemy->langchain->llama_index) (2.0.2)
lee@VM-0-3-ubuntu:~/gptDemo01/ChuanhuChatGPT$ python3 ChuanhuChatbot.py 
Traceback (most recent call last):
  File "ChuanhuChatbot.py", line 10, in <module>
    from modules.overwrites import *
  File "/home/lee/gptDemo01/ChuanhuChatGPT/modules/overwrites.py", line 4, in <module>
    from llama_index import Prompt
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/__init__.py", line 18, in <module>
    from llama_index.indices.common.struct_store.base import SQLDocumentContextBuilder
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/indices/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/indices/keyword_table/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/indices/keyword_table/base.py", line 16, in <module>
    from llama_index.indices.base import DOCUMENTS_INPUT, BaseGPTIndex
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/indices/base.py", line 23, in <module>
    from llama_index.indices.prompt_helper import PromptHelper
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/indices/prompt_helper.py", line 12, in <module>
    from llama_index.langchain_helpers.chain_wrapper import LLMPredictor
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/langchain_helpers/chain_wrapper.py", line 6, in <module>
    from llama_index.llm_predictor.base import (  # noqa: F401
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/llm_predictor/__init__.py", line 4, in <module>
    from llama_index.llm_predictor.base import LLMPredictor
  File "/home/lee/.local/lib/python3.8/site-packages/llama_index/llm_predictor/base.py", line 10, in <module>
    from langchain.chat_models import ChatOpenAI
ModuleNotFoundError: No module named 'langchain.chat_models'
```

**Comment by TypicalSpider** [comment]
这个问题是用的python3.8.0引起的，解决方案：
升级python版本到3.8.1或3.9或更高

**Comment by Keldos-Li** [comment]
> 这个我也遇到了，需要用3.8以上版本的python。报错是因为langchain在python3.8能装的版本太老https://www.piwheels.org/project/langchain/
所以用python3.9就行

_Originally posted by @luoye2333 in_
- https://github.com/GaiZhenbiao/ChuanhuChatGPT/discussions/408#discussioncomment-5436483

---- 

已加入常见问题。

**Comment by svikramank** [comment]
`No module named 'langchain.chat_models'`

Facing the same issue when following the tutorial: https://python.langchain.com/en/latest/modules/models/chat/getting_started.html

**Comment by luoye2333** [comment]
> `No module named 'langchain.chat_models'`
> 
> Facing the same issue when following the tutorial: https://python.langchain.com/en/latest/modules/models/chat/getting_started.html

the version of langchain lib installed is too low, try use a different version of python(3.9), and install requirements.txt

**Comment by 1945083536** [comment]
只要把python升级到3.8.1就可以解决。
实际上不升级python，安装langchain都不成功，因为0.0.129版本必须要求python的版本在3.8.1以上

**Comment by guolongxmu** [comment]
我解决了。把pip的安装网址换成官方的，不要用国内的源就行

**Comment by sleeper1023** [comment]
我解决了一个这种情况，主要是当前运行目录下不要有和模块同名的自己的py程序，我就是起了一个langchain,py的文件，就导入出错了，把自己的程序改名成 test.py或者其他的就行了

**Comment by longsc2603** [comment]
Is there any solution for this without updating python to higher versions? My source code demands python3.7 since it is still using a lot of tensorflow v1.
