### ISSUE TITLE
[Bug]: 显示长度 api key 不足 51 位

### ISSUE THREAD

**Issue by mtcoafun** [GaiZhenbiao/ChuanhuChatGPT#409]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue。

### 错误表现

填入我的 api key 后，报错显示不足 51 位

### 复现操作

1. git clone
2. cd
3. 在本地打开
4. 填入 api key
5. 开始聊天之后显示不足 51 位

### 运行环境

```markdown
- OS: macOS 12.6.3
- Browser: chrome 111.0.5563.110（正式版本） (arm64)
- Gradio version: 
- Python version: Python 3.10.5
```

### 补充说明

<img width="983" alt="image" src="https://user-images.githubusercontent.com/50589627/227832724-6188954a-909f-47ef-90ae-b9471e55ce79.png">

**Comment by GaiZhenbiao** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/51039745/227833203-329ba1c5-8380-411f-b483-c59b34433dbe.png">

API-Key的长度总是51位，否则就是错误的

**Comment by mtcoafun** [comment]
![image](https://user-images.githubusercontent.com/50589627/227833794-40c81806-4a10-40f8-947f-98e5b043dcb1.png)

**Comment by mtcoafun** [comment]
<img width="1540" alt="企业微信20230327-113249@2x" src="https://user-images.githubusercontent.com/50589627/227834323-a7c69819-3532-49a9-9522-28a284c6f6ca.png">

**Comment by GaiZhenbiao** [comment]
你用的是最新版本吗？更新到最新版本试试

**Comment by mtcoafun** [comment]
使用代码写死的方式是正常的，图形界面中填入是不正常的，我更新下试试

**Comment by GaiZhenbiao** [comment]
这个就是一个简单的判断，不该出错的

```python
if len(openai_api_key) != 51:
        status_text = standard_error_msg + no_apikey_msg
        logging.info(status_text)
        chatbot.append((inputs, ""))
```

**Comment by mtcoafun** [comment]
重新拉取代码后构建出错
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ipapi.co', port=443): Max retries exceeded with url: /json/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chenqiwei/ChuanhuChatGPT/ChuanhuChatbot.py", line 72, in <module>
    status_display = gr.Markdown(get_geoip(), elem_id="status_display")
  File "/Users/chenqiwei/ChuanhuChatGPT/modules/utils.py", line 367, in get_geoip
    response = requests.get("https://ipapi.co/json/", timeout=5)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='ipapi.co', port=443): Max retries exceeded with url: /json/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))
```

**Comment by xmlv** [comment]
sk-xxx   粘贴的时候容易给s丢了，不知道为什么。 题主可以注意看下

**Comment by Keldos-Li** [comment]
_No Response_
