### ISSUE TITLE
[本地部署]: 

### ISSUE THREAD

**Issue by wxtt522** [GaiZhenbiao/ChuanhuChatGPT#424]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

![image](https://user-images.githubusercontent.com/28422636/228114416-9326b06c-3882-48bc-9e98-6acba5f7af2a.png)

### 复现操作

最近本地化部署出现访问api.openai.com 443超时的问题，这种添加代理的方式已经不行了吗？我尝试过添加openSSL包和urllib3降级，都没解决这个问题，太奇怪了，我自己使用脚本请求又是正常的。

### 错误日志

```shell
Traceback (most recent call last):
  File "D:\PycharmProjects\ChuanhuChatGPT\ChuanhuChatbot.py", line 105, in <module>
    usageTxt = gr.Markdown(get_usage(my_api_key), elem_id="usage_display")
  File "D:\PycharmProjects\ChuanhuChatGPT\modules\openai_func.py", line 53, in get_usage
    response=get_usage_response(openai_api_key=openai_api_key)
  File "D:\PycharmProjects\ChuanhuChatGPT\modules\openai_func.py", line 44, in get_usage_response
    response = requests.get(
  File "D:\Anaconda3\envs\ChuanhuChatGPT\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda3\envs\ChuanhuChatGPT\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda3\envs\ChuanhuChatGPT\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda3\envs\ChuanhuChatGPT\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda3\envs\ChuanhuChatGPT\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /dashboard/billing/credit_grants (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FEE4972CD0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
```

### 运行环境

```markdown
- OS: win10
- Browser: Chrome
- Gradio version: 3.22.1
- Python version: 3.8
```

**Comment by wxtt522** [comment]
我配置系统代理是正常的，但在代码里出现这个异常，我怀疑是哪个最新的包也有https限制

**Comment by wxtt522** [comment]
好吧，我找到问题所在了,func文件里单独指定了requests的proxy ...

**Comment by GaiZhenbiao** [comment]
你那么设置按理应该也不会出问题🤔️request是获取系统代理的
