### ISSUE TITLE
[本地部署]: Uncaught (in promise) TypeError: z.stylesheets is not iterable

### ISSUE THREAD

**Issue by leileiandme** [GaiZhenbiao/ChuanhuChatGPT#437]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

开启账号密码验证后，网页console出现这个错误（ Uncaught (in promise) TypeError: z.stylesheets is not iterable），并且登录不了，这是什么原因造成的
![微信截图_20230328220340](https://user-images.githubusercontent.com/30788108/228263982-c63f3f20-2bdf-4414-a53c-b82a8d93c14a.png)

### 复现操作

1.正常部署，没有改过什么

### 错误日志

```shell
进入网页
index.9d6b8df7.js:8 Uncaught (in promise) TypeError: z.stylesheets is not iterable
    at b (index.9d6b8df7.js:8:22067)
    at index.9d6b8df7.js:8:23182

点击登陆
Login.svelte:20 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Failed to parse URL from http://192.168.1.4:7860undefined/login
    at HTMLButtonElement.u (Login.svelte:20:24)
    at index.9d6b8df7.js:4:1266
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.zr (index.9d6b8df7.js:4:1253)
    at HTMLButtonElement.c (Button.svelte:11:33)
```

### 运行环境

```markdown
- OS: Windows10
- Browser: Chrome
- Gradio version: Version: 3.22.1
- Python version: 3.11.2
```

**Comment by Ravanla** [comment]
我也出现了同样的错误，请问大佬是怎么解决的？

**Comment by AnliComputer** [comment]
我也遇到了同样问题，请问是怎么解决的？谢谢
