### ISSUE TITLE
[本地部署]: NAS上部署的docker自启动失败

### ISSUE THREAD

**Issue by q107580018** [GaiZhenbiao/ChuanhuChatGPT#442]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

我的unraid每天早上自动开机，自启动docker容器，最近更新几次后，chatGPT一直自启动失败，查看了下日志，如下：
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/root/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /dashboard/billing/credit_grants (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x153e12f76310>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/ChuanhuChatbot.py", line 105, in <module>
    usageTxt = gr.Markdown(get_usage(my_api_key), elem_id="usage_display")
  File "/app/modules/openai_func.py", line 53, in get_usage
    response=get_usage_response(openai_api_key=openai_api_key)
  File "/app/modules/openai_func.py", line 44, in get_usage_response
    response = requests.get(
  File "/root/.local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /dashboard/billing/credit_grants (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x153e12f76310>: Failed to establish a new connection: [Errno 110] Connection timed out'))

### 复现操作

更新了该镜像

### 错误日志

```shell
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/root/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /dashboard/billing/credit_grants (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x153e12f76310>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/ChuanhuChatbot.py", line 105, in <module>
    usageTxt = gr.Markdown(get_usage(my_api_key), elem_id="usage_display")
  File "/app/modules/openai_func.py", line 53, in get_usage
    response=get_usage_response(openai_api_key=openai_api_key)
  File "/app/modules/openai_func.py", line 44, in get_usage_response
    response = requests.get(
  File "/root/.local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /dashboard/billing/credit_grants (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x153e12f76310>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

### 运行环境

```markdown
- OS: Unraid Server
- Browser: Docker
- Gradio version: 
- Python version:
```

### 补充说明
- 感觉还是跟代理有关系，因为我的代理也是通过docker的v2rayA启动后实现的，会不会是因为v2rayA还没启动，chatgpt先启动了导致的？
_No response_

**Comment by Qwerty4401** [comment]
是代理的问题，我之前遇到过这样的异常。
我是用路由器开的代理，设置域名api.openai.com和openai.com强制走代理，然后就没有问题了。

**Comment by Keldos-Li** [comment]
请自行解决代理问题
