### ISSUE TITLE
[Bug]: 提示精简token错误

### ISSUE THREAD

**Issue by BenjaminGao** [GaiZhenbiao/ChuanhuChatGPT#444]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue。

### 错误表现

聊天不超过20句，屏幕右上角提示 `Error` 错误。`精简token中[257, 216, 425, 1153, 1346, 1269]/3500`。

### 复现操作

1. 正常完成部署。
2. 3月29日下午更新最新的版本。
3. 用Clash开启代理，并添加规则，开启增强模式。选择美国代理。

### 错误日志

```shell
<!-- ALREADY CONVERTED BY PARSER. -->'], ('<p style="white-space:pre-wrap;">power query 中合并两列数据怎么写</p><!-- ALREADY CONVERTED BY PARSER. -->', '<!-- ALREADY CONVERTED BY PARSER. -->')]
2023-03-29 13:12:47,366 [INFO] [chat_func.py:270] 输入为：你是谁？我们刚才聊了什么？
2023-03-29 13:12:47,366 [INFO] [chat_func.py:346] 不使用流式传输
2023-03-29 13:12:47,366 [INFO] [chat_func.py:215] 一次性回答模式
Traceback (most recent call last):
  File "/Users/mingxin/miniconda3/envs/chuabhuChatGPT/lib/python3.9/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/mingxin/miniconda3/envs/chuabhuChatGPT/lib/python3.9/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/Users/mingxin/miniconda3/envs/chuabhuChatGPT/lib/python3.9/site-packages/gradio/blocks.py", line 898, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/mingxin/miniconda3/envs/chuabhuChatGPT/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/mingxin/miniconda3/envs/chuabhuChatGPT/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/mingxin/miniconda3/envs/chuabhuChatGPT/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/mingxin/miniconda3/envs/chuabhuChatGPT/lib/python3.9/site-packages/gradio/utils.py", line 549, in async_iteration
    return next(iterator)
  File "/Users/mingxin/Desktop/ChuanhuChatGPT/modules/chat_func.py", line 391, in predict
    for chatbot, history, status_text, all_token_counts in iter:
  File "/Users/mingxin/Desktop/ChuanhuChatGPT/modules/chat_func.py", line 462, in reduce_token_size
    for chatbot, history, status_text, previous_token_count in iter:
  File "/Users/mingxin/Desktop/ChuanhuChatGPT/modules/chat_func.py", line 347, in predict
    chatbot, history, status_text, all_token_counts = predict_all(
  File "/Users/mingxin/Desktop/ChuanhuChatGPT/modules/chat_func.py", line 245, in predict_all
    content = response["choices"][0]["message"]["content"]
KeyError: 'choices'
```

### 运行环境

```markdown
- OS: macOS 13.2.1
- Browser: 
- Gradio version: 
- Python version: 3.9
```

**Comment by BenjaminGao** [comment]
![dg2wW0](http://cdn.mxmd.xyz/uPic/dg2wW0.png)

**Comment by yuri2078** [comment]
一样的报错问题，至于这个你是谁应该是token上限了，他自己帮你总结之前的内容。

**Comment by morestart** [comment]
content = response["choices"][0]["message"]["content"]
KeyError: 'choices'
一样的error

**Comment by gghyoo** [comment]
我也会报这个错误，最大的问题是，报错之后，就不回答了。

**Comment by morestart** [comment]
似乎是由于上面[yuri2078](https://github.com/yuri2078)所说，达到了token的上限

**Comment by cheng6563** [comment]
我倒是想怎么关掉自动精简。
