### ISSUE TITLE
[本地部署]: 本地部署

### ISSUE THREAD

**Issue by Moster-R** [GaiZhenbiao/ChuanhuChatGPT#482]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

install requirements.txt之后，输入启动命令，出现，这个包有安装成功，但是就是提示cannot import name 'ServiceContext' from 'llama_index' 

### 复现操作

install requirements.txt之后，输入启动命令，出现，这个包有安装成功，但是就是提示cannot import name 'ServiceContext' from 'llama_index' 

### 错误日志

```shell
PS E:\Python_Code\公司\ChuanhuChatGPT-main> python ChuanhuChatbot.py
Traceback (most recent call last):
  File "E:\Python_Code\公司\ChuanhuChatGPT-main\ChuanhuChatbot.py", line 10, in <module>
    from modules.overwrites import *
  File "E:\Python_Code\公司\ChuanhuChatGPT-main\modules\overwrites.py", line 9, in <module>
    from modules.llama_func import *
  File "E:\Python_Code\公司\ChuanhuChatGPT-main\modules\llama_func.py", line 4, in <module>
    from llama_index import GPTSimpleVectorIndex, ServiceContext
ImportError: cannot import name 'ServiceContext' from 'llama_index' (D:\Program Files\Python\Python39\lib\site-packages\llama_index\__init__.py)
```

### 运行环境

```markdown
- OS: 
- Browser: 
- Gradio version: 
- Python version: 3.9
```

**Comment by Keldos-Li** [comment]
尝试依次执行：
```
pip install -r requirements.txt
pip install --upgrade llama_index
pip install --upgrade langchain
```

**Comment by Keldos-Li** [comment]
Duplicate with 
- #475
