### ISSUE TITLE
[Bug]: 添加users后，登录界面无法展示出，查看控制台显示如下错误

### ISSUE THREAD

**Issue by pgkk** [GaiZhenbiao/ChuanhuChatGPT#514]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

服务启动正常，但是添加users配置后，默认展示登录界面，页面加载时报错，查看控制台显示如下错误

Uncaught (in promise) TypeError: z.stylesheets is not iterable
    at b (index.d6979a87.js:8:22067)
    at index.d6979a87.js:8:23182

### 复现操作

服务启动正常，但是添加users配置后，默认展示登录界面，页面加载时报错

### 错误日志

```shell
Uncaught (in promise) TypeError: z.stylesheets is not iterable
    at b (index.d6979a87.js:8:22067)
    at index.d6979a87.js:8:23182
```

### 运行环境

- OS: Windows
- Browser: Chrome 
- Gradio version: unknown
- Python version: 3.9

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
Duplicate with 
- #437

另外请给出更多相关信息与复现步骤，一般不应该有这样的问题……
