### ISSUE TITLE
[Bug]: llama 0.5.5 breaking change

### ISSUE THREAD

**Issue by xingfanxia** [GaiZhenbiao/ChuanhuChatGPT#517]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

sync了latest main之后 docker部署运行有如下错误 likely a breaking change in `llama-index 0.5.5`
```
Traceback (most recent call last):
File "/root/.local/lib/python3.9/site-packages/gradio/routes.py", line 393, in run_predict
output = await app.get_blocks().process_api(
File "/root/.local/lib/python3.9/site-packages/gradio/blocks.py", line 1108, in process_api
result = await self.call_function(
File "/root/.local/lib/python3.9/site-packages/gradio/blocks.py", line 929, in call_function
prediction = await anyio.to_thread.run_sync(
File "/root/.local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
return await get_asynclib().run_sync_in_worker_thread(
File "/root/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
return await future
File "/root/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
result = context.run(func, *args)
File "/root/.local/lib/python3.9/site-packages/gradio/utils.py", line 490, in async_iteration
return next(iterator)
File "/app/modules/chat_func.py", line 272, in predict
from llama_index.indices.query.vector_store import GPTVectorStoreIndexQuery
ModuleNotFoundError: No module named 'llama_index.indices.query.vector_store'
```

### 复现操作

Docker 部署 dependency 错误

### 运行环境

- OS:  docker
Python: 3.9.16  •  Gradio: 3.24.1

### 帮助解决

- [X] 我愿意协助解决！

**Comment by xingfanxia** [comment]
Verified it's a breaking change in local env
