### ISSUE TITLE
[远程部署]:  No module named 'llama_index.indices.query.vector_store'根据常见问题，所有方法都试过了，还是无法解决。

### ISSUE THREAD

**Issue by fcmyoo** [GaiZhenbiao/ChuanhuChatGPT#521]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

![image](https://user-images.githubusercontent.com/17491381/229395442-5c68944b-1610-485d-8d4c-3fd78d64e2ae.png)
根据常见问题，所有方法都试过了，还是无法解决。请大神求解

### 复现操作

我这边按照部署脚本正常操作。但是一发送问题就报这个错误

### 错误日志

```shell
To create a public link, set `share=True` in `launch()`.
2023-04-03 10:03:10,827 [INFO] [utils.py:367] API密钥更改为了sk-l*******************************************51vw
2023-04-03 10:03:11,892 [ERROR] [openai_func.py:82] 获取API使用情况失败:API request failed with status code 403: {
  "error": {
    "message": "Your request to GET /dashboard/billing/credit_grants must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

2023-04-03 10:03:12,044 [ERROR] [openai_func.py:82] 获取API使用情况失败:API request failed with status code 403: {
  "error": {
    "message": "Your request to GET /dashboard/billing/credit_grants must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

2023-04-03 10:03:24,105 [ERROR] [openai_func.py:82] 获取API使用情况失败:API request failed with status code 403: {
  "error": {
    "message": "Your request to GET /dashboard/billing/credit_grants must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

Traceback (most recent call last):
  File "/www/wwwroot/chat.jxcloud.pro/ChuanhuChatGPT/chatgpt-env/lib/python3.9/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/www/wwwroot/chat.jxcloud.pro/ChuanhuChatGPT/chatgpt-env/lib/python3.9/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "/www/wwwroot/chat.jxcloud.pro/ChuanhuChatGPT/chatgpt-env/lib/python3.9/site-packages/gradio/blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/www/wwwroot/chat.jxcloud.pro/ChuanhuChatGPT/chatgpt-env/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/www/wwwroot/chat.jxcloud.pro/ChuanhuChatGPT/chatgpt-env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/www/wwwroot/chat.jxcloud.pro/ChuanhuChatGPT/chatgpt-env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/www/wwwroot/chat.jxcloud.pro/ChuanhuChatGPT/chatgpt-env/lib/python3.9/site-packages/gradio/utils.py", line 490, in async_iteration
    return next(iterator)
  File "/www/wwwroot/chat.jxcloud.pro/ChuanhuChatGPT/modules/chat_func.py", line 272, in predict
    from llama_index.indices.query.vector_store import GPTVectorStoreIndexQuery
ModuleNotFoundError: No module named 'llama_index.indices.query.vector_store'
```

### 运行环境

- OS: centos
- Server: 
- Gradio version: 
- Python version: 3.9

**Comment by MIKL2077** [comment]
将llama_index.indices.query.vector_store替换成llama_index.indices.vector_store.base_query即可。
原因：该方法GPTVectorStoreIndexQuery()不在llama_index.indices.query.vector_store之下了。
详见：https://gpt-index.readthedocs.io/en/latest/reference/indices/vector_store_query.html#gpt_index.indices.vector_store.base_query.GPTVectorStoreIndexQuery

**Comment by xingfanxia** [comment]
我已经fix了

**Comment by xingfanxia** [comment]
https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/517

**Comment by caoxiaogang96** [comment]
获取API使用情况失败，这个问题您咋解决的呢

**Comment by GaiZhenbiao** [comment]
> 获取API使用情况失败，这个问题您咋解决的呢

因为OpenAI那边，用于获取使用情况的API挂掉了。现已修复。
