### ISSUE TITLE
[本地部署]: 

### ISSUE THREAD

**Issue by wuqi030624** [GaiZhenbiao/ChuanhuChatGPT#532]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

计算机积极拒绝连接和No such file or directory。

### 复现操作

本地部署，第四步之前正常，在启动命令哪里卡住，然后根据这篇文章https://blog.csdn.net/weixin_46900108/article/details/119773973 进行了设置，然后就打不开文件，再然后根据一个issue的回答，改成了实际路径，仍然不能解决

### 错误日志

```shell
PS C:\Users\wuqi0\Downloads\ChuanhuChatGPT-main> python C:\Users\wuqi0\Downloads\ChuanhuChatGPT-main\ChuanhuChatGPT-main\\ChuanhuChatbot.py
Traceback (most recent call last):
  File "C:\Users\wuqi0\Downloads\ChuanhuChatGPT-main\ChuanhuChatGPT-main\\ChuanhuChatbot.py", line 12, in <module>
    from modules.overwrites import *
  File "C:\Users\wuqi0\Downloads\ChuanhuChatGPT-main\ChuanhuChatGPT-main\modules\overwrites.py", line 41, in <module>
    with open("./assets/custom.js", "r", encoding="utf-8") as f, open("./assets/Kelpy-Codos.js", "r", encoding="utf-8") as f2:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './assets/custom.js'
PS C:\Users\wuqi0\Downloads\ChuanhuChatGPT-main>
```

### 运行环境

```markdown
- OS: Windows11 Version 1023.322.4012.0
- Browser: chrome
- Gradio version: 3.22.1
- Python version: 3.11.1
```

**Comment by Yike-Ye** [comment]
运行python的时候要到那个文件夹下，因为这里搞了相对路径
