### ISSUE TITLE
[其他]: Hugging Face中ChuanhuChatGPT使用时☹️发生了错误：读取超时，无法获取对话。请检查网络连接，或者API-Key是否有效。

### ISSUE THREAD

**Issue by yignshi** [GaiZhenbiao/ChuanhuChatGPT#564]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 错误描述

![image](https://user-images.githubusercontent.com/130142784/230590778-cf2176de-7095-464c-9c94-f8bf805f20a5.png)
运行日志：gfm74 2023-04-07T09:47:11.459Z TypeError: object of type 'int' has no len()
gfm74 2023-04-07T09:59:05.674Z 2023-04-07 11:59:05,674 [INFO] [chat_func.py:275] 输入为：婚礼布置
gfm74 2023-04-07T09:59:05.680Z 2023-04-07 11:59:05,680 [INFO] [chat_func.py:351] 使用流式传输
gfm74 2023-04-07T09:59:05.680Z 2023-04-07 11:59:05,680 [INFO] [chat_func.py:97] 实时回答模式
gfm74 2023-04-07T09:59:05.680Z 2023-04-07 11:59:05,680 [INFO] [chat_func.py:120] 输入token计数: 25
gfm74 2023-04-07T09:59:19.338Z 

但是回答内容是空白的

### 复现操作

1.正常打开Hugging Face 
2.在聊天框中输入：婚礼布置
3.回答为空白，出现：☹️发生了错误：读取超时，无法获取对话。请检查网络连接，或者API-Key是否有效。

### 错误日志

```shell
gfm74 2023-04-07T09:59:19.340Z Traceback (most recent call last):
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/.local/lib/python3.8/site-packages/urllib3/response.py", line 444, in _error_catcher
gfm74 2023-04-07T09:59:19.340Z     yield
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/.local/lib/python3.8/site-packages/urllib3/response.py", line 828, in read_chunked
gfm74 2023-04-07T09:59:19.340Z     self._update_chunk_length()
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/.local/lib/python3.8/site-packages/urllib3/response.py", line 758, in _update_chunk_length
gfm74 2023-04-07T09:59:19.340Z     line = self._fp.fp.readline()
gfm74 2023-04-07T09:59:19.340Z   File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
gfm74 2023-04-07T09:59:19.340Z     return self._sock.recv_into(b)
gfm74 2023-04-07T09:59:19.340Z   File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
gfm74 2023-04-07T09:59:19.340Z     return self.read(nbytes, buffer)
gfm74 2023-04-07T09:59:19.340Z   File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
gfm74 2023-04-07T09:59:19.340Z     return self._sslobj.read(len, buffer)
gfm74 2023-04-07T09:59:19.340Z socket.timeout: The read operation timed out
gfm74 2023-04-07T09:59:19.340Z 
gfm74 2023-04-07T09:59:19.340Z During handling of the above exception, another exception occurred:
gfm74 2023-04-07T09:59:19.340Z 
gfm74 2023-04-07T09:59:19.340Z Traceback (most recent call last):
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/.local/lib/python3.8/site-packages/requests/models.py", line 816, in generate
gfm74 2023-04-07T09:59:19.340Z     yield from self.raw.stream(chunk_size, decode_content=True)
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/.local/lib/python3.8/site-packages/urllib3/response.py", line 624, in stream
gfm74 2023-04-07T09:59:19.340Z     for line in self.read_chunked(amt, decode_content=decode_content):
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/.local/lib/python3.8/site-packages/urllib3/response.py", line 857, in read_chunked
gfm74 2023-04-07T09:59:19.340Z     self._original_response.close()
gfm74 2023-04-07T09:59:19.340Z   File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
gfm74 2023-04-07T09:59:19.340Z     self.gen.throw(type, value, traceback)
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/.local/lib/python3.8/site-packages/urllib3/response.py", line 449, in _error_catcher
gfm74 2023-04-07T09:59:19.340Z     raise ReadTimeoutError(self._pool, None, "Read timed out.")
gfm74 2023-04-07T09:59:19.340Z urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out.
gfm74 2023-04-07T09:59:19.340Z 
gfm74 2023-04-07T09:59:19.340Z During handling of the above exception, another exception occurred:
gfm74 2023-04-07T09:59:19.340Z 
gfm74 2023-04-07T09:59:19.340Z Traceback (most recent call last):
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 393, in run_predict
gfm74 2023-04-07T09:59:19.340Z     output = await app.get_blocks().process_api(
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1108, in process_api
gfm74 2023-04-07T09:59:19.340Z     result = await self.call_function(
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 929, in call_function
gfm74 2023-04-07T09:59:19.340Z     prediction = await anyio.to_thread.run_sync(
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
gfm74 2023-04-07T09:59:19.340Z     return await get_asynclib().run_sync_in_worker_thread(
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
gfm74 2023-04-07T09:59:19.340Z     return await future
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
gfm74 2023-04-07T09:59:19.340Z     result = context.run(func, *args)
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/utils.py", line 490, in async_iteration
gfm74 2023-04-07T09:59:19.340Z     return next(iterator)
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/app/modules/chat_func.py", line 365, in predict
gfm74 2023-04-07T09:59:19.340Z     for chatbot, history, status_text, all_token_counts in iter:
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/app/modules/chat_func.py", line 148, in stream_predict
gfm74 2023-04-07T09:59:19.340Z     for chunk in tqdm(response.iter_lines()):
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/.local/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
gfm74 2023-04-07T09:59:19.340Z     for obj in iterable:
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/.local/lib/python3.8/site-packages/requests/models.py", line 865, in iter_lines
gfm74 2023-04-07T09:59:19.340Z     for chunk in self.iter_content(
gfm74 2023-04-07T09:59:19.340Z   File "/home/user/.local/lib/python3.8/site-packages/requests/models.py", line 822, in generate
gfm74 2023-04-07T09:59:19.340Z     raise ConnectionError(e)
gfm74 2023-04-07T09:59:19.340Z requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out.
```

### 运行环境

- OS: 
- Browser: Chrome
- Gradio version: 
- Python version: 
(或您的其他运行环境信息)

**Comment by lingyun66** [comment]
我也是这样,今天无论怎么试都不行,还更新了下最新的项目版本

**Comment by GaiZhenbiao** [comment]
在`modules/presets.py`里把
```
timeout_streaming = 10  # 流式对话时的超时时间
```
这个超时时间调高试试

**Comment by lijiachang** [comment]
我也是这样,今天无论怎么试都不行,还更新了下最新的项目版本

**Comment by yignshi** [comment]
超时时间调高后可以使用聊天功能，但是其他功能还是不能使用

**Comment by yignshi** [comment]
而且，大概率只能回答一次信息

**Comment by yignshi** [comment]
而且，大概率只能回答一次

**Comment by A2ureStone** [comment]
+1, 也许是对hugging face做了限制

**Comment by yignshi** [comment]
更新，今天可以正常使用了  ，大概是open.ai出问题了

**Comment by yignshi** [comment]
okok，收回我刚才说的，又开始了

**Comment by GeekHank** [comment]
本地部署遇到了同样的问题，无法恢复回复消息并提示“☹️发生了错误：读取超时，无法获取对话。请检查网络连接，或者API-Key是否有效。”

**Comment by GeekHank** [comment]
应该是api的原因，目前恢复正常

**Comment by valithria** [comment]
> 应该是api的原因，目前恢复正常

没有……我刚又出现了「☹️发生了错误：读取超时，无法获取对话。请检查网络连接，或者API-Key是否有效。」而且反应特别慢，传输回答的时候几句话得等半分钟，或者是几个小时前好了然后又出问题了？

**Comment by GeekHank** [comment]
现在感觉api通道出了一点问题，我用很多个调用api的插件试过了，效果都差不太多，如果海的那边起床就卡可能说明api没有优先级了



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
From: valithria ***@***.***&gt;
发送时间: 04/09/2023, 18:01
To: GaiZhenbiao/ChuanhuChatGPT ***@***.***&gt;
抄送: GeekHank ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [GaiZhenbiao/ChuanhuChatGPT] [其他]: Hugging Face中ChuanhuChatGPT使用时☹️发生了错误：读取超时，无法获取对话。请检查网络连接，或者API-Key是否有效。 (Issue #564)

**Comment by valithria** [comment]
> 现在感觉api通道出了一点问题，我用很多个调用api的插件试过了，效果都差不太多，如果海的那边起床就卡可能说明api没有优先级了 

试了下网页版，发现就算是普通账号也快得飞起，回答的速度比我看字都要快……OpenAI不会是把网页版跟API的优先级弄错了吧……

**Comment by GeekHank** [comment]
可能个人api是对调了，商用api不影响



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
From: valithria ***@***.***&gt;
发送时间: 04/09/2023, 18:25
To: GaiZhenbiao/ChuanhuChatGPT ***@***.***&gt;
抄送: GeekHank ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [GaiZhenbiao/ChuanhuChatGPT] [其他]: Hugging Face中ChuanhuChatGPT使用时☹️发生了错误：读取超时，无法获取对话。请检查网络连接，或者API-Key是否有效。 (Issue #564)

**Comment by Orionxer** [comment]
是API的问题（可能是因为个人免费版），把超时时间设置大一些就行，比如60秒，修改文件的位置：`modules/presets.py`
```timeout_streaming = 60  # 流式对话时的超时时间```
我用Vultr的服务器（美国硅谷）测试API接口，通过openai官网提供的curl的命令去测试，响应速度是十分缓慢的，因此在网页上的响应也会特别慢。但是官网的chatgpt就快的飞起😂，用个人免费版的API暂时无解

**Comment by NekoYu** [comment]
> 在`modules/presets.py`里把
> 
> ```
> timeout_streaming = 10  # 流式对话时的超时时间
> ```
> 
> 这个超时时间调高试试

请问下docker部署怎么改，或者能加到ui里吗(´Д` )

**Comment by GaiZhenbiao** [comment]
> > 在`modules/presets.py`里把
> > ```
> > timeout_streaming = 10  # 流式对话时的超时时间
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个超时时间调高试试
> 
> 请问下docker部署怎么改，或者能加到ui里吗(´Д` )

最新版代码已经将这个的默认值调高到30秒了

**Comment by Keldos-Li** [comment]
> 最新版代码已经将这个的默认值调高到30秒了

emm 其实是60秒了，周六晚上merge的时候main和expansive不一样，我看川虎哥第一次merge保留了60，我重新merge的时候也就留了60 QAQ（

**Comment by NekoYu** [comment]
> > > 在`modules/presets.py`里把
> > > ```
> > > timeout_streaming = 10  # 流式对话时的超时时间
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这个超时时间调高试试
> > 
> > 
> > 请问下docker部署怎么改，或者能加到ui里吗(´Д` )
> 
> 最新版代码已经将这个的默认值调高到30秒了

更新了最新的，还是一样的“Incorrect API key provided”
