### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HsunGong** [GaiZhenbiao/ChuanhuChatGPT#573]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

报错如下

### 复现操作

对话内容：你是谁？我们刚才聊了什么？

### 错误日志

```shell
2023-04-08 20:28:08,740 [INFO] [chat_func.py:275] 输入为：你是谁？我们刚才聊了什么？
2023-04-08 20:28:08,740 [INFO] [chat_func.py:371] 不使用流式传输
2023-04-08 20:28:08,740 [INFO] [chat_func.py:203] 一次性回答模式
Traceback (most recent call last):
  File "/root/miniconda3/envs/chuanhu/lib/python3.9/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/chuanhu/lib/python3.9/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/chuanhu/lib/python3.9/site-packages/gradio/blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/chuanhu/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/chuanhu/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/chuanhu/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/chuanhu/lib/python3.9/site-packages/gradio/utils.py", line 490, in async_iteration
    return next(iterator)
  File "/root/chatgpt/ChuanhuChatGPT/modules/chat_func.py", line 484, in reduce_token_size
    for chatbot, history, status_text, previous_token_count in iter:
  File "/root/chatgpt/ChuanhuChatGPT/modules/chat_func.py", line 372, in predict
    chatbot, history, status_text, all_token_counts = predict_all(
  File "/root/chatgpt/ChuanhuChatGPT/modules/chat_func.py", line 247, in predict_all
    status_text = construct_token_message(total_token_count)
  File "/root/chatgpt/ChuanhuChatGPT/modules/utils.py", line 158, in construct_token_message
    for i in range(len(tokens)):
TypeError: object of type 'int' has no len()
```

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [X] 我愿意协助解决！

**Comment by weixhishu** [comment]
#569

**Comment by Keldos-Li** [comment]
Fixed via #574.
