### ISSUE TITLE
[Bug]: 两个小bug与解决方式

### ISSUE THREAD

**Issue by wpcaxys** [GaiZhenbiao/ChuanhuChatGPT#580]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

1.使用总结对话的时候会出现报错异常，报错为TypeError: object of type 'int' has no len()，原因是传入的tokens为数值类型，错误行为chat_func.py文件的247行。将total_token_count 修改为all_token_counts 就正常使用了

2.IP地址检测，检测网站增加真人认证机制，因此我更换了IP检测源：https://ip.cn/api/index?ip=&type=0 然后空位切割取第一个字符就ok了

### 复现操作

1.使用总结对话的时候会出现报错异常，报错为TypeError: object of type 'int' has no len()，原因是传入的tokens为数值类型，错误行为chat_func.py文件的247行。将total_token_count 修改为all_token_counts 就正常使用了

2.IP地址检测，检测网站增加真人认证机制，因此我更换了IP检测源：https://ip.cn/api/index?ip=&type=0 然后空位切割取第一个字符就ok了

### 错误日志

```shell
1. 2023-04-10 16:30:31,020 [INFO] [chat_func.py:275] 输入为：你是谁？我们刚才聊了什么？
2023-04-10 16:30:31,021 [INFO] [chat_func.py:373] 不使用流式传输
2023-04-10 16:30:31,021 [INFO] [chat_func.py:203] 一次性回答模式
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 898, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.8/dist-packages/gradio/utils.py", line 549, in async_iteration
    return next(iterator)
  File "/opt/ChuanhuChatGPT/modules/chat_func.py", line 486, in reduce_token_size
    for chatbot, history, status_text, previous_token_count in iter:
  File "/opt/ChuanhuChatGPT/modules/chat_func.py", line 374, in predict
    chatbot, history, status_text, all_token_counts = predict_all(
  File "/opt/ChuanhuChatGPT/modules/chat_func.py", line 247, in predict_all
    status_text = construct_token_message(total_token_count)
  File "/opt/ChuanhuChatGPT/modules/utils.py", line 158, in construct_token_message
    for i in range(len(tokens)):
TypeError: object of type 'int' has no len()



2. 2023-04-10 16:37:08,693 [WARNING] [utils.py:388] 无法获取IP地址信息。
{'error': True, 'reason': 'RateLimited', 'message': 'Visit https://ipapi.co/ratelimited/ for details'}
```

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [X] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
感谢关注，抱歉这么久才回复。

1. 在后来的更新中，总结对话功能已经被移除了；
2. 关于IP检测，原有的方法并不影响使用。
