### ISSUE TITLE
[Bug]: 点击重新生成时，发送的是ChatGPT的回答而非我的提问

### ISSUE THREAD

**Issue by Vinzelles** [GaiZhenbiao/ChuanhuChatGPT#678]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

我的提问：发送给ChatGPT一段代码并要求优化
![image](https://user-images.githubusercontent.com/67829622/232759848-a2eddf95-665b-415b-8ef3-5d8da1f7cd58.png)

点击重新生成后，“我”发送的是ChatGPT的另一段回答
![image](https://user-images.githubusercontent.com/67829622/232759924-c192422b-d631-46e3-8d71-cfef37802e6e.png)

再次点击重新生成，两边都变成了各说各的回答
![image](https://user-images.githubusercontent.com/67829622/232760619-200c058a-3686-443e-9798-bf14a0a15ef3.png)

### 复现操作

在此之前的对话正常

### 错误日志

```shell
无错误日志
```

### 运行环境

- OS:  Windows 11 Insider Preview
- Browser: Microsoft Edge Dev

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
能否提供具体细致的，稳定可复现的复现步骤？以及是否改过system prompt？

**Comment by Vinzelles** [comment]
> 能否提供具体细致的，稳定可复现的复现步骤？以及是否改过system prompt？

偶发性无法复现，使用的prompt为“担任高级前端开发人员”，其余参数均为默认

**Comment by dsjzazs** [comment]
不用prompt也会，当输入消息后，后台出现异常，或者延时很久才回复的时候。点重新生成就会发送上一条收到的信息。


日志：


2023-06-21 14:23:21,796 [INFO] [base_model.py:377] 用户的输入为：123
2023-06-21 14:23:22,120 [INFO] [base_model.py:441] 回答为：☹️发生了错误：获取对话时发生错误，请查看后台日志
2023-06-21 14:23:26,547 [INFO] [base_model.py:377] 用户的输入为：123
Traceback (most recent call last):
  File "D:\ChuanhuChatGPT-main\modules\models\base_model.py", line 424, in predict
    for chatbot, status_text in iter:
  File "D:\ChuanhuChatGPT-main\modules\models\base_model.py", line 250, in stream_next_chatbot
    for partial_text in stream_iter:
  File "D:\ChuanhuChatGPT-main\modules\models\models.py", line 58, in get_answer_stream_iter
    for i in iter:
  File "D:\ChuanhuChatGPT-main\modules\models\models.py", line 213, in _decode_chat_response
    if chunk_length > 6 and "delta" in chunk["choices"][0]:
                                       ~~~~~^^^^^^^^^^^
KeyError: 'choices'
2023-06-21 14:23:32,160 [INFO] [base_model.py:377] 用户的输入为：☹️发生了错误：获取对话时发生错误，请查看后台日志
2023-06-21 14:23:35,458 [INFO] [base_model.py:441] 回答为：抱歉，您的请求未提供足够的信息以生成有意义的响应。请提供更具
体的问题或内容，以便我能为您提供帮助。
