### ISSUE TITLE
[远程部署]: 使用XMChat模型时，网站上传图片时一直转圈圈直到超时

### ISSUE THREAD

**Issue by realnoob007** [GaiZhenbiao/ChuanhuChatGPT#698]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

使用XMChat模型时，网站上传图片时一直转圈圈直到超时
我申请了而有xmchat的api_key，已经配置好了，并且在xmchat下说“hi”也有回复。
注意，只有xmchat模式时图片无法上传，在gpt3.5模型下图片文件均可上传到服务器。怀疑是xmchat单独的问题，服务器本身网络和文件系统都没问题。
以下是报错内容：
<img width="478" alt="image" src="https://user-images.githubusercontent.com/87698941/233842920-b0a9fb78-50f2-4fbd-9502-533e609708e3.png">

### 复现操作

1. 正常完成服务器部署
2. 成功在外部网络上访问
3. 其他模块测试均无问题，只有xmchat无法上传图片

### 错误日志

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gradio/routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/site-packages/gradio/blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/site-packages/gradio/blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/ChuanhuChatGPT/modules/utils.py", line 114, in handle_file_upload
    return current_model.handle_file_upload(*args)
  File "/root/ChuanhuChatGPT/modules/models/models.py", line 504, in handle_file_upload
    response = json.loads(response.text)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### 运行环境

- OS: Windows 10
- Server: CentOS
- Gradio version: 3.25.0
- Python version: 3.9.0

**Comment by Keldos-Li** [comment]
等待XMChat解决吧orz
- https://github.com/MILVLG/xmchat/issues/3

**Comment by Keldos-Li** [comment]
This is caused by the unstable networking in our school occasionally...

_Originally posted by @MIL-VLG in https://github.com/MILVLG/xmchat/issues/3#issuecomment-1520263490_
            
这里先关闭了……
