### ISSUE TITLE
请问，在wsl ubuntu里部署并安装了Linux的cuda后，加载模型仍然是用的CPU处理，该如何解决

### ISSUE THREAD

**Issue by Maddaxman** [GaiZhenbiao/ChuanhuChatGPT#711]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

请问，在wsl ubuntu里部署并安装了Linux的cuda后，加载模型仍然是用的CPU处理，该如何解决

### 复现操作

请问，在wsl ubuntu里部署并安装了Linux的cuda后，加载模型仍然是用的CPU处理，该如何解决

### 错误日志

```shell
To create a public link, set `share=True` in `launch()`.
2023-04-26 16:44:44,703 [INFO] [models.py:548] 正在加载OpenAI模型: gpt-3.5-turbo
2023-04-26 16:44:44,703 [INFO] [models.py:588] Model is set to:  gpt-3.5-turbo
2023-04-26 16:44:48,129 [INFO] [models.py:557] 正在加载ChatGLM模型: chatglm-6b-int8
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
--- Logging error ---
Traceback (most recent call last):
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int8/quantization.py", line 18, in <module>
    from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunction, round_up
  File "/home/miniconda3/envs/ChuanhuChat3/lib/python3.10/site-packages/cpm_kernels/__init__.py", line 2, in <module>
    from .kernels import *
  File "/home/miniconda3/envs/ChuanhuChat3/lib/python3.10/site-packages/cpm_kernels/kernels/__init__.py", line 1, in <module>
    from .embedding import embedding_forward, embedding_backward_stage1, embedding_backward_stage2, embedding_step
  File "/home/miniconda3/envs/ChuanhuChat3/lib/python3.10/site-packages/cpm_kernels/kernels/embedding.py", line 1, in <module>
    from .base import Kernel, DevicePointer, CUDAStream, round_up
  File "/home/miniconda3/envs/ChuanhuChat3/lib/python3.10/site-packages/cpm_kernels/kernels/base.py", line 5, in <module>
    from ..device import Device
  File "/home/miniconda3/envs/ChuanhuChat3/lib/python3.10/site-packages/cpm_kernels/device/__init__.py", line 126, in <module>
    _Device(i) for i in range(cudart.cudaGetDeviceCount())
  File "/home/miniconda3/envs/ChuanhuChat3/lib/python3.10/site-packages/cpm_kernels/library/base.py", line 94, in wrapper
    return f(*args, **kwargs)
  File "/home/miniconda3/envs/ChuanhuChat3/lib/python3.10/site-packages/cpm_kernels/library/cudart.py", line 351, in cudaGetDeviceCount
    checkCUDAStatus(cuda.cudaGetDeviceCount(ctypes.byref(count)))
  File "/home/miniconda3/envs/ChuanhuChat3/lib/python3.10/site-packages/cpm_kernels/library/cudart.py", line 327, in checkCUDAStatus
    raise RuntimeError("CUDA Runtime Error: %s" % cudaGetErrorString(error))
RuntimeError: CUDA Runtime Error: CUDA driver version is insufficient for CUDA runtime version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/miniconda3/envs/ChuanhuChat3/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/miniconda3/envs/ChuanhuChat3/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/miniconda3/envs/ChuanhuChat3/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/miniconda3/envs/ChuanhuChat3/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/miniconda3/envs/ChuanhuChat3/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/home/miniconda3/envs/ChuanhuChat3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/miniconda3/envs/ChuanhuChat3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/maddax/ChuanhuChatGPT3/ChuanhuChatGPT/modules/models/models.py", line 558, in get_model
    model = ChatGLM_Client(model_name)
  File "/home/maddax/ChuanhuChatGPT3/ChuanhuChatGPT/modules/models/models.py", line 241, in __init__
    model = AutoModel.from_pretrained(
  File "/home/miniconda3/envs/ChuanhuChat3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 466, in from_pretrained
    return model_class.from_pretrained(
  File "/home/miniconda3/envs/ChuanhuChat3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2546, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int8/modeling_chatglm.py", line 1062, in __init__
    self.quantize(self.config.quantization_bit, self.config.quantization_embeddings, use_quantization_cache=True, empty_init=True)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int8/modeling_chatglm.py", line 1425, in quantize
    from .quantization import quantize, QuantizedEmbedding, QuantizedLinear, load_cpu_kernel
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int8/quantization.py", line 43, in <module>
    logger.warning("Failed to load cpm_kernels:", exception)
Message: 'Failed to load cpm_kernels:'
Arguments: (RuntimeError('CUDA Runtime Error: CUDA driver version is insufficient for CUDA runtime version'),)
No compiled kernel found.
Compiling kernels : /root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int8/quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 /root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int8/quantization_kernels_parallel.c -shared -o /root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int8/quantization_kernels_parallel.so
Load kernel : /root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int8/quantization_kernels_parallel.so
Setting CPU quantization kernel threads to 3
Parallel kernel is not recommended when parallel num < 4.
Using quantization cache
Applying quantization to glm layers
2023-04-26 16:45:11,092 [INFO] [models.py:254] GPU is not available, using CPU
2023-04-26 16:45:12,657 [INFO] [models.py:588] Model is set to:  chatglm-6b-int8
```

### 运行环境

```markdown
- OS: 
- Browser: 
- Gradio version: 
- Python version:
```

**Comment by oiuv** [comment]
还是别用wsl吧，坑爹没好处，第一，容易出你遇到的不用cuda的问题，第二，wsl不能完全的利用内存，基本默认只用系统一本的内存，这样又不用cuda，又不能完全利用内存，用wsl就没必要了，直接用windows启用最方便。

**Comment by Keldos-Li** [comment]
CUDA Runtime Error: CUDA driver version is insufficient for CUDA runtime version：
CUDA Toolkit安装的版本太高了，和你的GPU驱动不匹配。百度一下应该能解决吧。

-----

关于用不用WSL……真的能直接在Windows上装上吗？应该pip install到DeepSpeed大概率就失败了。

**Comment by Keldos-Li** [comment]
如有更多问题请移步Discussion提问
