### ISSUE TITLE
[Bug]: 开启在线搜索后输入会报错

### ISSUE THREAD

**Issue by Concinnity-P** [GaiZhenbiao/ChuanhuChatGPT#748]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

在开启在线搜索功能后再输入便会报错

### 复现操作

每次启动不开启在线搜索，输入可以正常回复，但开启后就开始报错

### 错误日志

```shell
2023-05-12 15:05:05,245 [INFO] [base_model.py:286] 输入为：你好？
2023-05-12 15:05:05,693 [ERROR] [utils.py:51]
Traceback (most recent call last):
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\duckduckgo_search\utils.py", line 39, in _get_vqd
    vqd_index_start = resp.content.index(b"vqd='") + 5
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: subsection not found
2023-05-12 15:05:05,705 [WARNING] [utils.py:59] keywords=你好？. _get_vqd() is None. Refresh SESSION and retry...
2023-05-12 15:05:06,346 [ERROR] [utils.py:51]
Traceback (most recent call last):
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\duckduckgo_search\utils.py", line 39, in _get_vqd
    vqd_index_start = resp.content.index(b"vqd='") + 5
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: subsection not found
2023-05-12 15:05:06,349 [WARNING] [utils.py:59] keywords=你好？. _get_vqd() is None. Refresh SESSION and retry...
Traceback (most recent call last):
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1059, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 514, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 507, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 490, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "E:\OneDrive\ChatGPT\ChuanhuChatGPT-main\ChuanhuChatGPT\modules\utils.py", line 39, in predict
    for i in iter:
  File "E:\OneDrive\ChatGPT\ChuanhuChatGPT-main\ChuanhuChatGPT\modules\models\base_model.py", line 294, in predict
    limited_context, fake_inputs, display_append, inputs, chatbot = self.prepare_inputs(real_inputs=inputs, use_websearch=use_websearch, files=files, reply_language=reply_language, chatbot=chatbot)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\OneDrive\ChatGPT\ChuanhuChatGPT-main\ChuanhuChatGPT\modules\models\base_model.py", line 254, in prepare_inputs
    for idx, result in enumerate(search_results):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

### 运行环境

- OS:  Windows11
- Browser: Chrome
- Gradio version: 3.29.0
- Python version: 3.11.3

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by oldfishoh** [comment]
问了ai 说是Duckduckgo的api接口返回值为空  这个接口不能用了？

**Comment by oldfishoh** [comment]
解决了吗

**Comment by GaiZhenbiao** [comment]
确实存在问题！我修一下

**Comment by GaiZhenbiao** [comment]
问题解决：升级`duckduckgo_search`的版本即可。

```
pip install duckduckgo_search --upgrade
```

**Comment by zodostffaa** [comment]
duckduckgo_search 2.9.4版本现在又不能用了

**Comment by GaiZhenbiao** [comment]
> duckduckgo_search 2.9.4版本现在又不能用了

我测试并没有问题。升级到`2.9.5`版本试试？

**Comment by zodostffaa** [comment]
> > duckduckgo_search 2.9.4版本现在又不能用了
> 
> 我测试并没有问题。升级到`2.9.5`版本试试？

问题是是相同内容只有第一次可以搜索出结果，duckduckgo_search开发者已经在解决这个问题了
