### ISSUE TITLE
[Bug]: 已经解决 索引构建成功后提问时传入了一个未定义的参数

### ISSUE THREAD

**Issue by oldfishoh** [GaiZhenbiao/ChuanhuChatGPT#751]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

TypeError: BaseGPTIndexQuery.__init__() got an unexpected keyword argument 'response_synthesizer'
这个错误通常是因为您在调用 BaseGPTIndexQuery 的构造函数时，传入了一个名为 response_synthesizer 的参数，但是这个参数在 BaseGPTIndexQuery 的构造函数中并不存在。
另外

### 复现操作

1.正常完成部署
2.文件（docx）成功构建索引
3.构建索引成功后提问报错
![Snipaste_2023-05-13_11-16-43](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/119662659/bd5db7bb-4487-49db-bed9-4d46eff0c902)

### 错误日志

```shell
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1036, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 488, in async_iteration
    return next(iterator)
  File "C:\Users\Administrator\Desktop\chat\modules\utils.py", line 39, in predict
    for i in iter:
  File "C:\Users\Administrator\Desktop\chat\modules\models\base_model.py", line 294, in predict
    limited_context, fake_inputs, display_append, inputs, chatbot = self.prepare_inputs(real_inputs=inputs, use_websearch=use_websearch, files=files, reply_language=reply_language, chatbot=chatbot)
  File "C:\Users\Administrator\Desktop\chat\modules\models\base_model.py", line 230, in prepare_inputs
    query_object = GPTVectorStoreIndexQuery(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\indices\vector_store\base_query.py", line 42, in __init__
    super().__init__(
TypeError: BaseGPTIndexQuery.__init__() got an unexpected keyword argument 'response_synthesizer'
```

### 运行环境

- OS: windows server 2022, centos7.6
- Browser: Edge
- Gradio version: 3.28.0
- Python version: 3.10.10
- llama-index :0.5.13
- langcha: 0.0.142

### 帮助解决

- [X] 我愿意协助解决！

**Comment by oldfishoh** [comment]
是什么问题呢 头大
