### ISSUE TITLE
[Bug]: 在线搜索功能报错误

### ISSUE THREAD

**Issue by a327958099** [GaiZhenbiao/ChuanhuChatGPT#753]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

<img width="894" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/26393031/c9702976-fb5f-41fc-8997-877fc69792f2">
在使用在线搜索功能是报错，提示在文件"ChuanhuChatGPT/modules/models/base_model.py"的251行中，尝试对一个值为None的对象进行迭代，造成了类型错误。

### 复现操作

只要选择使用在线搜索就好报错

### 错误日志

```shell
2023-05-14 12:51:30,364 [INFO] [base_model.py:283] 输入为：JS生成一个唯一ID
2023-05-14 12:51:31,053 [ERROR] [utils.py:51] 
Traceback (most recent call last):
  File "/Users/acme/Desktop/ChuanhuChatGPT/venv/lib/python3.10/site-packages/duckduckgo_search/utils.py", line 39, in _get_vqd
    vqd_index_start = resp.content.index(b"vqd='") + 5
ValueError: subsection not found
2023-05-14 12:51:31,056 [WARNING] [utils.py:59] keywords=JS生成一个唯一ID. _get_vqd() is None. Refresh SESSION and retry...
2023-05-14 12:51:31,930 [ERROR] [utils.py:51] 
Traceback (most recent call last):
  File "/Users/acme/Desktop/ChuanhuChatGPT/venv/lib/python3.10/site-packages/duckduckgo_search/utils.py", line 39, in _get_vqd
    vqd_index_start = resp.content.index(b"vqd='") + 5
ValueError: subsection not found
2023-05-14 12:51:31,934 [WARNING] [utils.py:59] keywords=JS生成一个唯一ID. _get_vqd() is None. Refresh SESSION and retry...
Traceback (most recent call last):
  File "/Users/acme/Desktop/ChuanhuChatGPT/venv/lib/python3.10/site-packages/gradio/routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/acme/Desktop/ChuanhuChatGPT/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/Users/acme/Desktop/ChuanhuChatGPT/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1036, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/acme/Desktop/ChuanhuChatGPT/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/acme/Desktop/ChuanhuChatGPT/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/acme/Desktop/ChuanhuChatGPT/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/acme/Desktop/ChuanhuChatGPT/venv/lib/python3.10/site-packages/gradio/utils.py", line 488, in async_iteration
    return next(iterator)
  File "/Users/acme/Desktop/ChuanhuChatGPT/modules/utils.py", line 39, in predict
    for i in iter:
  File "/Users/acme/Desktop/ChuanhuChatGPT/modules/models/base_model.py", line 291, in predict
    limited_context, fake_inputs, display_append, inputs, chatbot = self.prepare_inputs(real_inputs=inputs, use_websearch=use_websearch, files=files, reply_language=reply_language, chatbot=chatbot)
  File "/Users/acme/Desktop/ChuanhuChatGPT/modules/models/base_model.py", line 251, in prepare_inputs
    for idx, result in enumerate(search_results):
TypeError: 'NoneType' object is not iterable
```

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [X] 我愿意协助解决！

**Comment by oldfishoh** [comment]
昨天有人提过了   
问了ai 说是Duckduckgo的api接口返回值为空 
ChatGPT正常
而且索引也有问题 你部署的索引能用吗

**Comment by GaiZhenbiao** [comment]
https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/748#issuecomment-1546847212

升级duckduckgo_search的版本就行了
