### ISSUE TITLE
[其他]: ImportError: cannot import name 'TextIteratorStreamer' from 'transformers' 

### ISSUE THREAD

**Issue by 1438802682** [GaiZhenbiao/ChuanhuChatGPT#757]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 错误描述

Traceback (most recent call last):
  File "/home/hdw/ChuanhuChat/ChuanhuChatGPT/ChuanhuChatbot.py", line 14, in &lt;module&gt;
    from modules.models.models import get_model
  File "/home/hdw/ChuanhuChat/ChuanhuChatGPT/modules/models/models.py", line 25, in &lt;module&gt;
    from ChuanhuChatGPT.modules.models.StableLM import StableLM_Client
  File "/home/hdw/ChuanhuChat/ChuanhuChatGPT/modules/models/StableLM.py", line 2, in &lt;module&gt;
    from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline, StoppingCriteria, StoppingCriteriaList, TextIteratorStreamer
ImportError: cannot import name 'TextIteratorStreamer' from 'transformers' (/home/hdw/anaconda3/envs/ChuanhuChat/lib/python3.10/site-packages/transformers/__init__.py)

### 复现操作

1.正常完成部署
2.运行python ChuanhuChatbot.py时报错

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 
(或您的其他运行环境信息)

**Comment by zhangavator** [comment]
您好，请问这个报错怎么解决的呢
