### ISSUE TITLE
[Docker]:  最新版本docker部署开始报错.

### ISSUE THREAD

**Issue by vshen009** [GaiZhenbiao/ChuanhuChatGPT#772]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

正常运行每天的更新脚本. 上周五开始报错

### 复现操作

1.正常docker部署使用.
2.写了一个脚本自动更新,
3.上周五开始脚本更新完报错.

### 错误日志

```shell
docker logs -f chatgpt
Traceback (most recent call last):
  File "/app/ChuanhuChatbot.py", line 12, in <module>
    from modules.overwrites import *
  File "/app/modules/overwrites.py", line 4, in <module>
    from llama_index import Prompt
  File "/root/.local/lib/python3.9/site-packages/llama_index/__init__.py", line 14, in <module>
    from llama_index.embeddings.langchain import LangchainEmbedding
  File "/root/.local/lib/python3.9/site-packages/llama_index/embeddings/langchain.py", line 6, in <module>
    from langchain.embeddings.base import Embeddings as LCEmbeddings
  File "/root/.local/lib/python3.9/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/root/.local/lib/python3.9/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/root/.local/lib/python3.9/site-packages/langchain/agents/agent.py", line 17, in <module>
    from langchain.chains.base import Chain
  File "/root/.local/lib/python3.9/site-packages/langchain/chains/__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "/root/.local/lib/python3.9/site-packages/langchain/chains/api/base.py", line 8, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "/root/.local/lib/python3.9/site-packages/langchain/chains/api/prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "/root/.local/lib/python3.9/site-packages/langchain/prompts/__init__.py", line 3, in <module>
    from langchain.prompts.chat import (
  File "/root/.local/lib/python3.9/site-packages/langchain/prompts/chat.py", line 10, in <module>
    from langchain.memory.buffer import get_buffer_string
  File "/root/.local/lib/python3.9/site-packages/langchain/memory/__init__.py", line 22, in <module>
    from langchain.memory.vectorstore import VectorStoreRetrieverMemory
  File "/root/.local/lib/python3.9/site-packages/langchain/memory/vectorstore.py", line 10, in <module>
    from langchain.vectorstores.base import VectorStoreRetriever
  File "/root/.local/lib/python3.9/site-packages/langchain/vectorstores/__init__.py", line 2, in <module>
    from langchain.vectorstores.annoy import Annoy
  File "/root/.local/lib/python3.9/site-packages/langchain/vectorstores/annoy.py", line 16, in <module>
    from langchain.embeddings.base import Embeddings
  File "/root/.local/lib/python3.9/site-packages/langchain/embeddings/__init__.py", line 18, in <module>
    from langchain.embeddings.openai import OpenAIEmbeddings
  File "/root/.local/lib/python3.9/site-packages/langchain/embeddings/openai.py", line 66, in <module>
    class OpenAIEmbeddings(BaseModel, Embeddings):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/local/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
Traceback (most recent call last):
  File "/app/ChuanhuChatbot.py", line 12, in <module>
    from modules.overwrites import *
  File "/app/modules/overwrites.py", line 4, in <module>
    from llama_index import Prompt
  File "/root/.local/lib/python3.9/site-packages/llama_index/__init__.py", line 14, in <module>
    from llama_index.embeddings.langchain import LangchainEmbedding
  File "/root/.local/lib/python3.9/site-packages/llama_index/embeddings/langchain.py", line 6, in <module>
    from langchain.embeddings.base import Embeddings as LCEmbeddings
  File "/root/.local/lib/python3.9/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/root/.local/lib/python3.9/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/root/.local/lib/python3.9/site-packages/langchain/agents/agent.py", line 17, in <module>
    from langchain.chains.base import Chain
  File "/root/.local/lib/python3.9/site-packages/langchain/chains/__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "/root/.local/lib/python3.9/site-packages/langchain/chains/api/base.py", line 8, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "/root/.local/lib/python3.9/site-packages/langchain/chains/api/prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "/root/.local/lib/python3.9/site-packages/langchain/prompts/__init__.py", line 3, in <module>
    from langchain.prompts.chat import (
  File "/root/.local/lib/python3.9/site-packages/langchain/prompts/chat.py", line 10, in <module>
    from langchain.memory.buffer import get_buffer_string
  File "/root/.local/lib/python3.9/site-packages/langchain/memory/__init__.py", line 22, in <module>
    from langchain.memory.vectorstore import VectorStoreRetrieverMemory
  File "/root/.local/lib/python3.9/site-packages/langchain/memory/vectorstore.py", line 10, in <module>
    from langchain.vectorstores.base import VectorStoreRetriever
  File "/root/.local/lib/python3.9/site-packages/langchain/vectorstores/__init__.py", line 2, in <module>
    from langchain.vectorstores.annoy import Annoy
  File "/root/.local/lib/python3.9/site-packages/langchain/vectorstores/annoy.py", line 16, in <module>
    from langchain.embeddings.base import Embeddings
  File "/root/.local/lib/python3.9/site-packages/langchain/embeddings/__init__.py", line 18, in <module>
    from langchain.embeddings.openai import OpenAIEmbeddings
  File "/root/.local/lib/python3.9/site-packages/langchain/embeddings/openai.py", line 66, in <module>
    class OpenAIEmbeddings(BaseModel, Embeddings):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/local/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
Traceback (most recent call last):
  File "/app/ChuanhuChatbot.py", line 12, in <module>
    from modules.overwrites import *
  File "/app/modules/overwrites.py", line 4, in <module>
    from llama_index import Prompt
  File "/root/.local/lib/python3.9/site-packages/llama_index/__init__.py", line 14, in <module>
    from llama_index.embeddings.langchain import LangchainEmbedding
  File "/root/.local/lib/python3.9/site-packages/llama_index/embeddings/langchain.py", line 6, in <module>
    from langchain.embeddings.base import Embeddings as LCEmbeddings
  File "/root/.local/lib/python3.9/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/root/.local/lib/python3.9/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/root/.local/lib/python3.9/site-packages/langchain/agents/agent.py", line 17, in <module>
    from langchain.chains.base import Chain
  File "/root/.local/lib/python3.9/site-packages/langchain/chains/__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "/root/.local/lib/python3.9/site-packages/langchain/chains/api/base.py", line 8, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "/root/.local/lib/python3.9/site-packages/langchain/chains/api/prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "/root/.local/lib/python3.9/site-packages/langchain/prompts/__init__.py", line 3, in <module>
    from langchain.prompts.chat import (
  File "/root/.local/lib/python3.9/site-packages/langchain/prompts/chat.py", line 10, in <module>
    from langchain.memory.buffer import get_buffer_string
  File "/root/.local/lib/python3.9/site-packages/langchain/memory/__init__.py", line 22, in <module>
    from langchain.memory.vectorstore import VectorStoreRetrieverMemory
  File "/root/.local/lib/python3.9/site-packages/langchain/memory/vectorstore.py", line 10, in <module>
    from langchain.vectorstores.base import VectorStoreRetriever
  File "/root/.local/lib/python3.9/site-packages/langchain/vectorstores/__init__.py", line 2, in <module>
    from langchain.vectorstores.annoy import Annoy
  File "/root/.local/lib/python3.9/site-packages/langchain/vectorstores/annoy.py", line 16, in <module>
    from langchain.embeddings.base import Embeddings
  File "/root/.local/lib/python3.9/site-packages/langchain/embeddings/__init__.py", line 18, in <module>
    from langchain.embeddings.openai import OpenAIEmbeddings
  File "/root/.local/lib/python3.9/site-packages/langchain/embeddings/openai.py", line 66, in <module>
    class OpenAIEmbeddings(BaseModel, Embeddings):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/local/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

### 运行环境

- OS: 
- Docker version: 
- Gradio version: 
- Python version:

**Comment by Keldos-Li** [comment]
Duplicate with 
- #766

**Comment by GolovinElics** [comment]
遇到同样的问题，docker和Hugging face都不行
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/34887710/6ada3b1d-4363-4d77-85bc-156341b546d3)

![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/34887710/aedbf3ee-1430-42c6-a449-d49c97d75b33)

**Comment by Keldos-Li** [comment]
docker 23.05.20版本不行吗？

**Comment by GaiZhenbiao** [comment]
看上去是依赖版本的问题。重新装一下依赖试试？

**Comment by hallfay0** [comment]
同样的错误

**Comment by miaowmint** [comment]
docker 23.05.20 版本应该是没问题的，问题出在 23.05.23 版本

**Comment by ghxx2016** [comment]
同样情况

**Comment by GaiZhenbiao** [comment]
23.05.24 版本试试呢？

**Comment by vshen009** [comment]
我在requirements.txt 加入了 duckduckgo_search 重新构建了镜像就OK了. 申请duckduckgo_search加入requirements.txt

**Comment by vshen009** [comment]
我在requirements.txt 加入了 duckduckgo_search 重新构建了镜像就OK了. 申请duckduckgo_search加入requirements.txt
