### ISSUE TITLE
[Bug]: 用官方的Dockerfile构建后的容器报错

### ISSUE THREAD

**Issue by vshen009** [GaiZhenbiao/ChuanhuChatGPT#780]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

ModuleNotFoundError: No module named 'duckduckgo_search', 我看了依赖里面没有这个. 

### 复现操作

1.docker build -t chatgpt /root/ChuanhuChatGPT,正常完成构建
2.运行docker 命令拉起程序看到报错.
3.docker logs chatgpt

### 错误日志

```shell
Traceback (most recent call last):
  File "/app/ChuanhuChatbot.py", line 13, in <module>
    from modules.models.models import get_model
  File "/app/modules/models/models.py", line 18, in <module>
    from duckduckgo_search import ddg
ModuleNotFoundError: No module named 'duckduckgo_search'
[root@tunnel01 ~]# docker logs chatgpt
Traceback (most recent call last):
  File "/app/ChuanhuChatbot.py", line 13, in <module>
    from modules.models.models import get_model
  File "/app/modules/models/models.py", line 18, in <module>
    from duckduckgo_search import ddg
ModuleNotFoundError: No module named 'duckduckgo_search'
```

### 运行环境

- OS: 
- Browser: 
- Gradio version: 3.28
- Python version: 3.9(来自Dockerfile里面定义的镜像)

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
感谢提醒，现在应该没问题了
