### ISSUE TITLE
[远程部署]: 构建索引时AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by realnoob007** [GaiZhenbiao/ChuanhuChatGPT#785]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

服务器按流程正常部署，所有依赖按照requirement安装，langchain版本反复检查过，也重装过，但是依然上传pdf后报错
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/87698941/21353c08-872d-4f30-b1b7-b489a733e3c1)

### 复现操作

1. 正常完成服务器部署(之前的版本都没问题)
2. pull了最新的代码！
3. 上传pdf
4. 创建索引报错

### 错误日志

```shell
2023-05-27 10:34:00,596 [INFO] [base_model.py:319] 加载索引中……
2023-05-27 10:34:00,600 [INFO] [index_func.py:38] loading file: Cisneros_Eleven.pdf
2023-05-27 10:34:00,856 [ERROR] [models.py:90] 获取API使用情况失败:Expecting value: line 1 column 1 (char 
0)
100%|███████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 11.43it/s]
2023-05-27 10:34:01,330 [INFO] [index_func.py:128] 构建索引中……
2023-05-27 10:34:01,910 [ERROR] [index_func.py:139] 索引构建失败！'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/root/chatgay/ChuanhuChatGPT/modules/index_func.py", line 130, in construct_index
    index = FAISS.from_documents(documents, embeddings)
  File "/usr/local/python310/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 296, in fr
om_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/usr/local/python310/lib/python3.10/site-packages/langchain/vectorstores/faiss.py", line 420, in f
rom_texts
    embeddings = embedding.embed_documents(texts)
  File "/usr/local/python310/lib/python3.10/site-packages/langchain/embeddings/openai.py", line 289, in em
bed_documents
    return self._get_len_safe_embeddings(texts, engine=self.deployment)
  File "/usr/local/python310/lib/python3.10/site-packages/langchain/embeddings/openai.py", line 216, in _g
et_len_safe_embeddings
    response = embed_with_retry(
  File "/usr/local/python310/lib/python3.10/site-packages/langchain/embeddings/openai.py", line 64, in emb
ed_with_retry
    return _embed_with_retry(**kwargs)
  File "/usr/local/python310/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/usr/local/python310/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/python310/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/local/python310/lib/python3.10/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/local/python310/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/python310/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/usr/local/python310/lib/python3.10/site-packages/langchain/embeddings/openai.py", line 62, in _em
bed_with_retry
    return embeddings.client.create(**kwargs)
  File "/usr/local/python310/lib/python3.10/site-packages/openai/api_resources/embedding.py", line 33, in 
create
    response = super().create(*args, **kwargs)
  File "/usr/local/python310/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resourc
e.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/python310/lib/python3.10/site-packages/openai/api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/python310/libt_response
    self._interpret_response_line(
  File "/usr/local/python310/lib/python3.10/site-packages/openai/api_requestor.py", line 687, in _interpr$t_response_line
    raise self.handle_error_response(
  File "/usr/local/python310/lib/python3.10/site-packages/openai/api_requestor.py", line 350, in handle_e$ror_response
    error_code=error_data.get("code"),
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/python310/lib/python3.10/site-packages/gradio/routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/python310/lib/python3.10/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/usr/local/python310/lib/python3.10/site-packages/gradio/blocks.py", line 1036, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/python310/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/python310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_s
ync_in_worker_thread
    return await future
  File "/usr/local/python310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/python310/lib/python3.10/site-packages/gradio/utils.py", line 488, in async_iteration
    return next(iterator)
  File "/root/chatgay/ChuanhuChatGPT/modules/utils.py", line 39, in predict
    for i in iter:
  File "/root/chatgay/ChuanhuChatGPT/modules/models/base_model.py", line 381, in predict
    limited_context, fake_inputs, display_append, inputs, chatbot = self.prepare_inputs(real_inputs=input$
, use_websearch=use_websearch, files=files, reply_language=reply_language, chatbot=chatbot)
  File "/root/chatgay/ChuanhuChatGPT/modules/models/base_model.py", line 321, in prepare_inputs
    assert index is not None, "获取索引失败"
AssertionError: 获取索引失败/python3.10/site-packages/openai/api_requestor.py", line 624, in _interpre
```

### 运行环境

- OS: Windows 10
- Server:  CentOS 7
- Gradio version: 3.28.0
- Python version: 3.10.1

### 补充说明

特意再配置了一个虚拟环境，报错依旧一样

**Comment by GaiZhenbiao** [comment]
你使用的是最新版本的代码吗？我测试是没问题的

**Comment by realnoob007** [comment]
感谢川虎的细心解答，现在全部问题已经解决。
实际的问题是我自定义了base_url，然后那个转发平台不支持embedding，导致了pdf以及文件检索功能报错。
大家选择转发平台的时候一定要看仔细支持的model，以免不必要的麻烦。
