### ISSUE TITLE
[本地部署]: 

### ISSUE THREAD

**Issue by scordl327** [GaiZhenbiao/ChuanhuChatGPT#799]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

设置川虎助理后，无法使用在线搜索，并且会报错1 validation error for DuckDuckGoSearchAPIWrapper root Could not import duckduckgo-search python package. Please install it with pip install duckduckgo-search. (type=value_error)  同时安装过 duckduckgo-search后也无法解决问题。

### 复现操作

1.正常的部署
2.设置了川虎助理
3.点开了在线搜索
4.提问，出问题了

### 错误日志

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1320, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1064, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 514, in async_iteration
    return await iterator.__anext__()
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 507, in __anext__
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 490, in run_sync_iterator_async
    return next(iterator)
  File "/home/Chat/modules/utils.py", line 59, in retry
    for i in iter:
  File "/home/Chat/modules/models/base_model.py", line 495, in retry
    for x in iter:
  File "/home/Chat/modules/models/base_model.py", line 381, in predict
    limited_context, fake_inputs, display_append, inputs, chatbot = self.prepare_inputs(real_inputs=inputs, use_websearch=use_websearch, files=files, reply_language=reply_language, chatbot=chatbot)
  File "/home/Chat/modules/models/base_model.py", line 339, in prepare_inputs
    search_results = [i for i in search(real_inputs, advanced=True)]
  File "/home/Chat/modules/models/base_model.py", line 339, in <listcomp>
    search_results = [i for i in search(real_inputs, advanced=True)]
  File "/usr/local/lib/python3.10/dist-packages/googlesearch/__init__.py", line 54, in search
    resp = _req(escaped_term, num_results - start,
  File "/usr/local/lib/python3.10/dist-packages/googlesearch/__init__.py", line 23, in _req
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%25E4%25BB%2580%25E4%25B9%2588%25E6%2598%25AF%25E6%2595%25B0%25E5%25AD%2597%25E5%25AD%25AA%25E7%2594%259F%26num%3D12%26hl%3Den%26start%3D0&hl=en&q=EhAgARnwAAUjglQABP_-dfw1GN-UjaQGIjCxgLMHmAI18WIbl6FVeud-TcAitUxwxe2DFXiavAcnZtHAhDG1va_teVteJ-FdDAcyAXJaAUM
```

### 运行环境

```markdown
- OS: ubutnu 22.04 
- Browser: 
- Gradio version: 
- Python version: 3.10
```

**Comment by Keldos-Li** [comment]
请尝试更新到新版本的 **ChuanhuChat**

**Comment by GaiZhenbiao** [comment]
最新版本换回了duckduckgo搜索，去试试吧～
