### ISSUE TITLE
[Bug]: 上传pdf文件后ValueError: binary mode doesn't take an encoding argument

### ISSUE THREAD

**Issue by cwayer** [GaiZhenbiao/ChuanhuChatGPT#810]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

当前版本上传pdf文件后出现Error报错

### 复现操作

在https://huggingface.co/spaces/JohnSmith9982/ChuanhuChatGPT上传pdf文件后出现Error报错，复制到自己space后也同样报错

### 错误日志

```shell
2023-06-14 17:18:28,494 [INFO] [models.py:562] 正在加载OpenAI模型: gpt-3.5-turbo
2023-06-14 17:18:28,495 [INFO] [models.py:615] 模型设置为了： gpt-3.5-turbo
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/user/app/modules/utils.py", line 116, in handle_file_upload
    return current_model.handle_file_upload(*args)
  File "/home/user/app/modules/models/base_model.py", line 286, in handle_file_upload
    index = construct_index(self.api_key, file_src=files)
  File "/home/user/app/modules/index_func.py", line 114, in construct_index
    index_name = get_index_name(file_src)
  File "/home/user/app/modules/index_func.py", line 19, in get_index_name
    with open(file_path, "rb", encoding="utf-8") as f:
ValueError: binary mode doesn't take an encoding argument
```

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by Lao-Tz** [comment]
俺也一样
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/93063057/69757be8-7923-4549-8527-c869b9ceb155)

**Comment by Keldos-Li** [comment]
> 俺也一样

@Lao-Tz 你的问题与本ISSUE无关。请参考 [常见问题](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/常见问题#something-went-wrong-expecting-value-line-1-column-1-char-0)

**Comment by GaiZhenbiao** [comment]
已修复 https://github.com/GaiZhenbiao/ChuanhuChatGPT/commit/356ead395bcd0605cd21621c3ee5aad68e8cbb88
