### ISSUE TITLE
[Bug]: 索引构建失败

### ISSUE THREAD

**Issue by slideslide** [GaiZhenbiao/ChuanhuChatGPT#815]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/86949124/d1933a85-197e-4629-9b62-e1c763e35953)
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/86949124/3ba5f6fe-a3bf-47f5-9497-3d685bb1d37c)

### 复现操作

正常完成部署，在放入文件后出现这个错误，后续直接使用也无法获取索引。

### 错误日志

```shell
2023-06-16 09:06:08,159 [INFO] [index_func.py:38] loading file: 2103.00020.pdf
2023-06-16 09:06:08,340 [ERROR] [index_func.py:83] Error loading file: 2103.00020.pdf
Traceback (most recent call last):
  File "J:\bots\chatGPT\long2\ChuanhuChatGPT\modules\index_func.py", line 47, in get_documents
    pdftext = parse_pdf(filepath, two_column).text
  File "J:\bots\chatGPT\long2\ChuanhuChatGPT\modules\pdf_func.py", line 87, in parse_pdf
    title, user_info, first_page = get_title_with_cropped_page(pdf.pages[0])
  File "J:\bots\chatGPT\long2\ChuanhuChatGPT\modules\pdf_func.py", line 64, in get_title_with_cropped_page
    user_info = [i["text"] for i in extract_words(first_page.within_bbox((x0,title_bottom,x1,top)))]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pdfplumber\page.py", line 334, in within_bbox
    return CroppedPage(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pdfplumber\page.py", line 464, in __init__
    test_proposed_bbox(self.bbox, parent_page.bbox)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pdfplumber\page.py", line 428, in test_proposed_bbox
    bbox_area = utils.calculate_area(bbox)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pdfplumber\utils\geometry.py", line 70, in calculate_area
    raise ValueError(f"{bbox} has a negative width or height.")
ValueError: (0, 544.46, 612, 187.7354368) has a negative width or height.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "J:\bots\chatGPT\long2\ChuanhuChatGPT\modules\index_func.py", line 50, in get_documents
    with open(filepath, "rb", encoding="utf-8") as pdfFileObj:
ValueError: binary mode doesn't take an encoding argument
2023-06-16 09:06:08,343 [ERROR] [index_func.py:139] 索引构建失败！local variable 'texts' referenced before assignment
Traceback (most recent call last):
  File "J:\bots\chatGPT\long2\ChuanhuChatGPT\modules\index_func.py", line 127, in construct_index
    documents = get_documents(file_src)
  File "J:\bots\chatGPT\long2\ChuanhuChatGPT\modules\index_func.py", line 86, in get_documents
    texts = text_splitter.split_documents(texts)
UnboundLocalError: local variable 'texts' referenced before assignment
```

### 运行环境

- OS: Windows10 22H1
- Browser: Chrome
- Gradio version: 
- Python version: 3.9

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by isdkz** [comment]
ChuanhuChatGPT\modules\index_func.py 第50行
将 with open(filepath, "rb", encoding="utf-8") as pdfFileObj:  改为  with open(filepath, "rb") as pdfFileObj:
即 去掉 encoding="utf-8"
因为以二进制模式打开是不需要编码的

**Comment by GaiZhenbiao** [comment]
请更新到最新版本，这个问题已经解决了

**Comment by 2-3-5-7** [comment]
应该还有一处
https://github.com/GaiZhenbiao/ChuanhuChatGPT/blob/ed82ab0f281d5d9ec7f9d03093c9e07066faa026/modules/index_func.py#L50

**Comment by slideslide** [comment]
感谢
