### ISSUE TITLE
使用文档时出现AttributeError: 'NoneType' object has no attribute 'docstore'[Bug]: 

### ISSUE THREAD

**Issue by yxmnjxzx** [GaiZhenbiao/ChuanhuChatGPT#816]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

更新至最新版后，上传本地文件，不能使用，出现错误

### 复现操作

正常本地部署
更新至最新版

### 错误日志

```shell
Traceback (most recent call last):
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Users\ChuanhuChatGPT\modules\utils.py", line 119, in handle_summarize_index
    return current_model.summarize_index(*args)
  File "D:\Users\ChuanhuChatGPT\modules\models\base_model.py", line 305, in summarize_index
    summary = chain({"input_documents": list(index.docstore.__dict__["_dict"].values())}, return_only_outputs=True)["output_text"]
AttributeError: 'NoneType' object has no attribute 'docstore'
```

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
你的 langchain 版本是什么？

**Comment by yxmnjxzx** [comment]
> 你的 langchain 版本是什么？

0.0.2

**Comment by GaiZhenbiao** [comment]
你应该使用`0.0.173`版本的 langchain

**Comment by zernel** [comment]
我用 0.0.173 版本的 langchain 也有遇到这个问题，直接在 huggingface 的 space 上传文档再点总结也会一样报错（https://huggingface.co/spaces/JohnSmith9982/ChuanhuChatGPT）

**Comment by GaiZhenbiao** [comment]
唔，那你再看看 FAISS 的版本？`faiss-cpu`的版本应该是`1.7.4`

**Comment by himself07** [comment]
遇到相同的问题，0.0.173和高版本的都试过，FAISS版本是F1.7.4，huggingface的demo好像也有这个问题呢

**Comment by himself07** [comment]
估计是其它包的版本应该是个低版本？

**Comment by GaiZhenbiao** [comment]
这个问题应该早就解决了。项目现在适配的是高版本的 langchain，安装最新版本`0.0.287`就行了。
