### ISSUE TITLE
[功能请求]: 能否添加上传图片功能呢？页面可否加入自助注册功能?

### ISSUE THREAD

**Issue by tutianyu101** [GaiZhenbiao/ChuanhuChatGPT#822]
### 相关问题

能否添加上传图片功能呢？类似bing的图片识别和文言一心的那种？还有页面可否加入自助注册功能？多人使用可以自助注册账号

### 可能的解决办法

能否添加上传图片功能呢？类似bing的图片识别和文言一心的那种？还有页面可否加入自助注册功能？多人使用可以自助注册账号

### 帮助开发

- [X] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
支持上传图片的，请使用 XMChat 模型（需要申请XMChat 的 API Key）

**Comment by tutianyu101** [comment]
> 支持上传图片的，请使用 XMChat 模型（需要申请XMChat 的 API Key）

我说的是gpt4的，上传图片的那种。大佬这个可以实现吗？

**Comment by MZhao-ouo** [comment]
> > 支持上传图片的，请使用 XMChat 模型（需要申请XMChat 的 API Key）
> 
> 我说的是gpt4的，上传图片的那种。大佬这个可以实现吗？

gpt4我们也没拿到识别图像的api，XMChat可以做到一部分功能

**Comment by baiyi-os** [comment]
现在有这个api了吗，目前看还是不行，报错如下：
2023-10-10 21:09:49,260 [INFO] [index_func.py:25] loading file: xin.jpg
2023-10-10 21:09:49,261 [ERROR] [index_func.py:73] Error loading file: xin.jpg
Traceback (most recent call last):
  File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/langchain/document_loaders/text.py", line 41, in load
    text = f.read()
  File "/usr/local/Python-3.9.12/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xin/ChuanhuChatGPT/modules/index_func.py", line 70, in get_documents
    texts = loader.load()
  File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/langchain/document_loaders/text.py", line 54, in load
    raise RuntimeError(f"Error loading {self.file_path}") from e
RuntimeError: Error loading /tmp/gradio/01ed09e8783e62426736598d18280a5497a0b15f/xin.jpg
2023-10-10 21:09:49,261 [INFO] [index_func.py:126] 构建索引中……
2023-10-10 21:09:49,261 [ERROR] [index_func.py:137] 索引构建失败！list index out of range
Traceback (most recent call last):
  File "/home/xin/ChuanhuChatGPT/modules/index_func.py", line 128, in construct_index
    index = FAISS.from_documents(documents, embeddings)
  File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/langchain/vectorstores/base.py", line 417, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/langchain/vectorstores/faiss.py", line 603, in from_texts
    return cls.__from(
  File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/langchain/vectorstores/faiss.py", line 562, in __from
    index = faiss.IndexFlatL2(len(embeddings[0]))
IndexError: list index out of range

**Comment by GaiZhenbiao** [comment]
截至目前，GPT4-V还没有开放API调用，开放了我们会第一时间跟进。GPT4-V效果确实很不错～

**Comment by Keldos-Li** [comment]
已经加入GPT-Vision，可在[新版本](https://github.com/GaiZhenbiao/ChuanhuChatGPT/releases/tag/20231110)中体验。
