### ISSUE TITLE
[Docker]: validation error for SerpAPIWrapper root Could not import serpapi python package. Please install it with pip install google-search-results

### ISSUE THREAD

**Issue by 503611908** [GaiZhenbiao/ChuanhuChatGPT#852]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

错误：validation error for SerpAPIWrapper root Could not import serpapi python package. Please install it with pip install google-search-results
之前有个issues类似，但是没有解决掉问题，我切换了python版本，重新安装，都没有办法解决该问题

### 复现操作

1.正常完成docker部署
2.正常完成配置、api的填写
3.执行pip install google-search-results
4.还是报相同的错误

### 运行环境

- OS: 
- Docker version: 
- Gradio version: 
- Python version:

**Comment by GaiZhenbiao** [comment]
奇怪。我等会儿调查一下

**Comment by hkwz2023** [comment]
同样的问题。求解

**Comment by GaiZhenbiao** [comment]
虚拟环境是同一个吗？换句话说，安装 google-search-results 的 python 和启动川虎 Chat 的 python 是同一个 python 吗？另外，重新安装之后，应该重新启动川虎 Chat

**Comment by hkwz2023** [comment]
docker安装，没有用虚拟环境。自带Python2.7，后来换成了3.7安装google-search-results，重启docker问题依旧。

**Comment by heavenkiller2018** [comment]
I am confronting an identical predicament, earnestly anticipating a resolution. 

@GaiZhenbiao

**Comment by heavenkiller2018** [comment]
Following the implementation via Docker, I find myself unable to access it through the Edge browser, though Chrome presents no such impediments. Herein, I provide the corresponding error narrative.

```
dom.js:238  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')
    at k (dom.js:238:9)
    at Object.m (Blocks.svelte:554:63)
    at ke (Component.js:42:23)
    at Object.m (Index.svelte:343:26)
    at Object.p (Index.svelte:296:89)
    at fr (utils.js:168:8)
    at Object.p (Embed.svelte:25:7)
    at cn (scheduler.js:119:30)
    at yr (scheduler.js:79:5)
(索引):461  Uncaught TypeError: Cannot read properties of null (reading 'style')
    at setChatbotHeight ((索引):461:21)
```

**Comment by Keldos-Li** [comment]
> Following the implementation via Docker, I find myself unable to access it through the Edge browser, though Chrome presents no such impediments. Herein, I provide the corresponding error narrative.
> 
> ```
> dom.js:238  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')
>     at k (dom.js:238:9)
>     at Object.m (Blocks.svelte:554:63)
>     at ke (Component.js:42:23)
>     at Object.m (Index.svelte:343:26)
>     at Object.p (Index.svelte:296:89)
>     at fr (utils.js:168:8)
>     at Object.p (Embed.svelte:25:7)
>     at cn (scheduler.js:119:30)
>     at yr (scheduler.js:79:5)
> (索引):461  Uncaught TypeError: Cannot read properties of null (reading 'style')
>     at setChatbotHeight ((索引):461:21)
> ```

Hi @heavenkiller2018, There shouldn't be such a problem because now Edge and Chrome use the same kernal. If you encounter an issue where the web page cannot be opened in a specific browser, we generally recommend clearing the browser cache and trying again, or adjusting the network environment and trying again.

If you are certain that Edge cannot be used, please open a new issue and provide more detailed information about the error. This is unrelated to the original issue and the deployment method used. Additionally, the error message indicates that the main issue stems from the native JS of Gradio, which we may not be able to resolve.
