### ISSUE TITLE
[Bug]: azure opena使用报错

### ISSUE THREAD

**Issue by yxmnjxzx** [GaiZhenbiao/ChuanhuChatGPT#858]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

切换成azure openai 无法使用，使用代理出现_ssl.c:997错误，tunnel模式不会报错，但tunnel模式下依然无法使用，错误如下：
Traceback (most recent call last):
  File "D:\Users\ChuanhuChatGPT\modules\models\base_model.py", line 454, in predict
    for chatbot, status_text in iter:
  File "D:\Users\ChuanhuChatGPT\modules\models\base_model.py", line 276, in stream_next_chatbot
    self.history.append(construct_assistant(partial_text))
UnboundLocalError: local variable 'partial_text' referenced before assignment

相同设置在chatgpt_academic和chatbox上均可以正常使用

### 复现操作

正常本地部署

### 错误日志

```shell
Traceback (most recent call last):
  File "D:\Users\ChuanhuChatGPT\modules\models\base_model.py", line 454, in predict
    for chatbot, status_text in iter:
  File "D:\Users\ChuanhuChatGPT\modules\models\base_model.py", line 276, in stream_next_chatbot
    self.history.append(construct_assistant(partial_text))
UnboundLocalError: local variable 'partial_text' referenced before assignment
```

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
更新一下再试试呢？

**Comment by yxmnjxzx** [comment]
似乎还是不行，报错：
2023-08-12 14:08:40,268 [INFO] [models.py:625] 模型设置为了： Azure OpenAI
2023-08-12 14:08:42,576 [WARNING] [base_model.py:242] billing info not implemented, using default
2023-08-12 14:08:42,675 [INFO] [base_model.py:406] 用户的输入为：hi
2023-08-12 14:08:49,420 [INFO] [util.py:67] error_code=404 error_message='Resource not found' error_param=None error_type=None message='OpenAI API error received' stream_error=False
Exception in thread Thread-15 (thread_func):
Traceback (most recent call last):
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Users\ChuanhuChatGPT\modules\models\base_model.py", line 776, in thread_func
    self.model(messages=history, callbacks=[
  File "D:\Users\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\langchain\chat_models\base.py", line 178, in __call__
    generation = self.generate(
  File "D:\Users\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\langchain\chat_models\base.py", line 91, in generate
    raise e
  File "D:\Users\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\langchain\chat_models\base.py", line 83, in generate
    results = [
  File "D:\Users\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\langchain\chat_models\base.py", line 84, in <listcomp>
    self._generate(m, stop=stop, run_manager=run_manager)
  File "D:\Users\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\langchain\chat_models\openai.py", line 296, in _generate
    response = self.completion_with_retry(messages=message_dicts, **params)
  File "D:\Users\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\langchain\chat_models\openai.py", line 257, in completion_with_retry
    return _completion_with_retry(**kwargs)
  File "D:\Users\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "D:\Users\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "D:\Users\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\Users\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "D:\Users\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\langchain\chat_models\openai.py", line 255, in _completion_with_retry
    return self.client.create(**kwargs)
  File "D:\Users\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\Users\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\Users\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "D:\Users\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "D:\Users\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Resource not found

**Comment by GaiZhenbiao** [comment]
"Resource not found"，hmm…… 你愿意提供你的 Azure OpenAI API 给我用于测试吗？因为我手头并没有这个。你可以发邮件给我：cascade.lucite-04@icloud.com

**Comment by Keldos-Li** [comment]
应该已经解决了（许久之前）
