### ISSUE TITLE
[本地部署]: ☹️发生了错误：module ‘commentjson’ has no attribute ‘JSONDecodeError’

### ISSUE THREAD

**Issue by mgclznr** [GaiZhenbiao/ChuanhuChatGPT#865]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

部署完成后填写cofig.json后，首次试用提示☹️发生了错误：module ‘commentjson’ has no attribute ‘JSONDecodeError’

### 复现操作

1、正常完成部署
2、聊天框输入123
3、返回空白，右上角提示☹️发生了错误：module ‘commentjson’ has no attribute ‘JSONDecodeError’

### 错误日志

```shell
错误信息为
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\lark\parsers\lalr_parser.py", line 62, in get_action
    return states[state][token.type]
           ~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: '$END'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\gj\ai\ChuanhuChatGPT\modules\models\models.py", line 210, in _decode_chat_response
    chunk = json.loads(chunk[6:])
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\commentjson\commentjson.py", line 180, in loads
    parsed = _remove_trailing_commas(parser.parse(text))
                                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\lark\lark.py", line 311, in parse
    return self.parser.parse(text, start=start)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\lark\parser_frontends.py", line 89, in parse
    return self._parse(token_stream, start, *[sps] if sps is not NotImplemented else [])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\lark\parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\lark\parsers\lalr_parser.py", line 36, in parse
    return self.parser.parse(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\lark\parsers\lalr_parser.py", line 99, in parse
    _action, arg = get_action(token)
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\lark\parsers\lalr_parser.py", line 65, in get_action
    raise UnexpectedToken(token, expected, state=state)
lark.exceptions.UnexpectedToken: Unexpected token Token($END, '') at line 1, column 1.
Expected one of:
        * LBRACE
        * LSQB
        * TRUE
        * FALSE
        * SIGNED_NUMBER
        * ESCAPED_STRING
        * NULL


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\gj\ai\ChuanhuChatGPT\modules\models\base_model.py", line 455, in predict
    for chatbot, status_text in iter:
  File "E:\gj\ai\ChuanhuChatGPT\modules\models\base_model.py", line 269, in stream_next_chatbot
    for partial_text in stream_iter:
  File "E:\gj\ai\ChuanhuChatGPT\modules\models\models.py", line 58, in get_answer_stream_iter
    for i in iter:
  File "E:\gj\ai\ChuanhuChatGPT\modules\models\models.py", line 211, in _decode_chat_response
    except json.JSONDecodeError:
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'commentjson' has no attribute 'JSONDecodeError'
```

### 运行环境

```markdown
- OS: Windows11 22H2
- Browser: edge
- Gradio version: 
- Python version: v3.11.4:
```

**Comment by Keldos-Li** [comment]
尝试执行
```
pip install commentjson --upgrade
```
?

**Comment by Keldos-Li** [comment]
应该已经解决了
