### ISSUE TITLE
[Bug]: 接入Azure OpenAI 报错

### ISSUE THREAD

**Issue by Concinnity-P** [GaiZhenbiao/ChuanhuChatGPT#872]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

加入了一些log之后发现错误似乎是在openai.py
message格式不对
2023-08-27 19:16:52,039 [INFO] [base_model.py:769] [SystemMessage(content='You are a helpful assistant.', additional_kwargs={}), HumanMessage(content='1', additional_kwargs={}, example=False)]
2023-08-27 19:16:52,043 [INFO] [base.py:84] [SystemMessage(content='You are a helpful assistant.', additional_kwargs={}), HumanMessage(content='1', additional_kwargs={}, example=False)]
2023-08-27 19:16:52,043 [INFO] [openai.py:279] content='You are a helpful assistant.' additional_kwargs={}
2023-08-27 19:16:52,043 [INFO] [openai.py:308] content='You are a helpful assistant.' additional_kwargs={}

### 复现操作

正常在config中填入azure信息后报错

### 错误日志

```shell
Traceback (most recent call last):
  File "E:\OneDrive\ChatGPT\ChuanhuChatGPT-main\ChuanhuChatGPT\modules\models\base_model.py", line 462, in predict
    chatbot, status_text = self.next_chatbot_at_once(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\OneDrive\ChatGPT\ChuanhuChatGPT-main\ChuanhuChatGPT\modules\models\base_model.py", line 292, in next_chatbot_at_once
    ai_reply, total_token_count = self.get_answer_at_once()
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\OneDrive\ChatGPT\ChuanhuChatGPT-main\ChuanhuChatGPT\modules\models\base_model.py", line 770, in get_answer_at_once
    response = self.model.generate(history)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chat_models\base.py", line 94, in generate
    raise e
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chat_models\base.py", line 86, in generate
    results = [
              ^
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chat_models\base.py", line 87, in <listcomp>
    self._generate(m, stop=stop, run_manager=run_manager)
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chat_models\openai.py", line 280, in _generate
    message_dicts, params = self._create_message_dicts(messages, stop)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chat_models\openai.py", line 309, in _create_message_dicts
    message_dicts = [_convert_message_to_dict(m) for m in messages]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chat_models\openai.py", line 309, in <listcomp>
    message_dicts = [_convert_message_to_dict(m) for m in messages]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hddpp\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chat_models\openai.py", line 92, in _convert_message_to_dict
    raise ValueError(f"Got unknown type {message}")
ValueError: Got unknown type ('content', 'You are a helpful assistant.')
```

### 运行环境

OS: Windows11 22H2
Browser: Chrome
Gradio version: 3.22.1
Python version: 3.11.1

### 帮助解决

- [X] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
我等会儿看下👀

**Comment by Keldos-Li** [comment]
顺便，这个gradio版本有点老了

**Comment by Concinnity-P** [comment]
> 顺便，这个gradio版本有点老了，和我们项目匹配的现在应该是gradio 3.40.0
我这个是就是3.40.0版本呀

**Comment by Concinnity-P** [comment]
> 顺便，这个gradio版本有点老了，和我们项目匹配的现在应该是gradio 3.40.0

我现在就是3.40.0版本呀

**Comment by Keldos-Li** [comment]
哦 你运行环境那里没改……我还以为怎么是这么老版呢。

**Comment by GaiZhenbiao** [comment]
请测试一下，最新版还有这个问题吗？

**Comment by Concinnity-P** [comment]
> 请测试一下，最新版还有这个问题吗？

似乎还是不行，一摸一样的报错

**Comment by Concinnity-P** [comment]
> 请测试一下，最新版还有这个问题吗？

还是一模一样的报错
另外还发现了一个bug，即使在ui中切换了模型，界面中的api-key并不会切换，一直显示的是openai_api_key，而不是azure_openai_api_key
还希望能增加一个设置，可以默认关闭实时问答传输功能，因为我都这个azure openai目前是不支持的，不关闭会直接报错卡死

谢谢谢谢

**Comment by Keldos-Li** [comment]
应该已经解决了（许久之前）？
