### ISSUE TITLE
[本地部署]: 本地部署启动报错

### ISSUE THREAD

**Issue by Timoshao** [GaiZhenbiao/ChuanhuChatGPT#886]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

按照文档教程 
git clone https://github.com/GaiZhenbiao/ChuanhuChatGPT.git
cd ChuanhuChatGPT
pip install -r requirements.txt
然后，在项目文件夹中复制一份 config_example.json，并将其重命名为 config.json，在其中填入 API-Key 等设置。

python ChuanhuChatbot.py
报错如下
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/108260847/3c0ee603-cb65-474c-8db8-c4b6d23a43d5)

![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/108260847/dabc2fd4-2978-489e-bfb0-cb0102d2784a)

### 复现操作

啥也没干 启动报错

### 错误日志

```shell
PS D:\git\ChuanhuChatGP> python ChuanhuChatbot.py
'TZ' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
D:\git\ChuanhuChatGP\modules\overwrites.py:89: GradioUnusedKwargWarning: You have unused kwarg parameters in JSON, please remove them: {'readonly': True}
  res = original_IOComponent_init(self, *args, **kwargs)
Running on local URL:  http://192.168.5.88:7860

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.
Traceback (most recent call last):
  File "D:\Program Files\Python\Lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\git\ChuanhuChatGP\ChuanhuChatbot.py", line 496, in create_greeting
    filename, system_prompt, chatbot = current_model.auto_load()
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\git\ChuanhuChatGP\modules\models\base_model.py", line 762, in auto_load
    filepath = get_history_filepath(self.user_identifier)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\git\ChuanhuChatGP\modules\utils.py", line 679, in get_history_filepath
    latest_file = new_auto_history_filename(username)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\git\ChuanhuChatGP\modules\utils.py", line 671, in new_auto_history_filename
    now = i18n("新对话 ") + datetime.datetime.now().strftime('%m-%d %H꞉%M')
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'locale' codec can't encode character '\ua789' in position 8: encoding error
```

### 运行环境

```markdown
- OS:  Windows11 22H2
- Browser: Chrome
- Gradio version: 3.43.2
- Python version: 3.11
```

### 补充说明

/

**Comment by Keldos-Li** [comment]
拉一下最新版代码

**Comment by GaiZhenbiao** [comment]
这是 Windows 编码引起的 bug，现在已经在最新版代码里修复了。请拉取最新版本的代码。

**Comment by GaiZhenbiao** [comment]
> > 这是 Windows 编码引起的 bug，现在已经在最新版代码里修复了。请拉取最新版本的代码。
> > 请问如何拉取最新代码？
> > 我用git clone https://github.com/GaiZhenbiao/ChuanhuChatGPT.git
> > 和发行版20230830下载的都测试了

在 git clone 的目录下执行 `git pull` 就行了

**Comment by Timoshao** [comment]
> > > 这是 Windows 编码引起的 bug，现在已经在最新版代码里修复了。请拉取最新版本的代码。
> > > 请问如何拉取最新代码？
> > > 我用git clone https://github.com/GaiZhenbiao/ChuanhuChatGPT.git
> > > 和发行版20230830下载的都测试了
> 
> 在 git clone 的目录下执行 `git pull` 就行了
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/108260847/b5e7631e-e885-44f8-b81d-89a63248e0c0)

![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/108260847/81c5f526-a0fa-49ae-b165-a2419d0b2289)

重新拉取了代码 安装了依赖 仍然报错

**Comment by GaiZhenbiao** [comment]
那么，试试安装更新版的依赖：
```
pip install -r requirements.txt --upgrade
```

**Comment by Timoshao** [comment]
> 那么，试试安装更新版的依赖：
> 
> ```
> pip install -r requirements.txt --upgrade
> ```

不行 还是同样的问题

**Comment by Timoshao** [comment]
> 那么，试试安装更新版的依赖：
> 
> ```
> pip install -r requirements.txt --upgrade
> ```

ubuntu系统下部署成功了
