### ISSUE TITLE
[Docker]: 在Docker中部署llama2-7b-chat-hf模型，无法使用CPU加载

### ISSUE THREAD

**Issue by SunMacArenas** [GaiZhenbiao/ChuanhuChatGPT#895]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

在Docker中部署Llma2-7b-chat-hf模型，因为没有GPU资源无法使用cuda,在加载模型时报RuntimeError: Found no NVIDIA driver on your system 错误，如何手动修改配置禁用Cuda，使用CPU加载模型。

### 复现操作

1.正常完成dockers部署，能加载chatglm-6b-int4模型，
2.加载Llma2-7b-chat-hf模型时，报RuntimeError: Found no NVIDIA driver on your system 错误。

### 错误日志

```shell
正在加载LLaMA模型: Llama-2-7b-hf + No LoRA
Traceback (most recent call last):
  File "/app/modules/models/models.py", line 645, in get_model
    model = LLaMA_Client(
  File "/app/modules/models/models.py", line 397, in __init__
    LLAMA_MODEL = AutoModel.get_model(
  File "/usr/local/lib/python3.9/site-packages/lmflow/models/auto_model.py", line 16, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/lmflow/models/hf_decoder_model.py", line 216, in __init__
    if gpu in torch.cuda.get_device_name():
  File "/usr/local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 365, in get_device_name
    return get_device_properties(device).name
  File "/usr/local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 395, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/usr/local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/.local/lib/python3.9/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/.local/lib/python3.9/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/root/.local/lib/python3.9/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/.local/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/.local/lib/python3.9/site-packages/gradio/utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "/app/modules/models/models.py", line 692, in get_model
    model.history = original_model.history
AttributeError: 'NoneType' object has no attribute 'history'
```

### 运行环境

- OS: SUSE12 
- Docker version: 19.03
- Gradio version: 
- Python version: 3.9

### 补充说明

无

**Comment by GaiZhenbiao** [comment]
请升级到最新版，支持纯CPU推理～
