### ISSUE TITLE
[本地部署]: 本地部署启动报错No module named 'colorama'

### ISSUE THREAD

**Issue by fuzhengqu** [GaiZhenbiao/ChuanhuChatGPT#898]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

正常下载，双击 run_Windows.bat运行，出现报错：
Opening ChuanhuChatGPT...
venv "D:\Downloads\ChuanhuChatGPT-main\\ChuanhuChat\Scripts\Python.exe"
Traceback (most recent call last):
  File "D:\Downloads\ChuanhuChatGPT-main\ChuanhuChatbot.py", line 2, in <module>
    from modules.models.models import get_model
  File "D:\Downloads\ChuanhuChatGPT-main\modules\models\models.py", line 6, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'
请按任意键继续. . .

**也尝试安装过依赖，执行pip install -r requirements.txt --upgrade
安装依赖最后也有报错，如下：**
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "C:\Program Files\Python\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Program Files\Python\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Program Files\Python\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

尝试再次安装依赖，依旧报错：

### 复现操作

首次运行直接就是这个报错，未作其他操作，换了另外两台电脑都是同样问题

### 错误日志

```shell
Opening ChuanhuChatGPT...
venv "D:\Downloads\ChuanhuChatGPT-main\\ChuanhuChat\Scripts\Python.exe"
Traceback (most recent call last):
  File "D:\Downloads\ChuanhuChatGPT-main\ChuanhuChatbot.py", line 2, in <module>
    from modules.models.models import get_model
  File "D:\Downloads\ChuanhuChatGPT-main\modules\models\models.py", line 6, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'
请按任意键继续. . .

**也尝试安装过依赖，执行pip install -r requirements.txt --upgrade
安装依赖最后也有报错，如下：**
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "C:\Program Files\Python\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Program Files\Python\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Program Files\Python\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

尝试再次安装依赖，依旧报错：
 Using cached googlesearch-python-1.2.3.tar.gz (3.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "C:\Program Files\Python\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Program Files\Python\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Program Files\Python\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### 运行环境

```markdown
- OS: Windows11 22H2
- Browser: Edge
- Gradio version: 3.43.2
- Python version: 3.11
```

### 补充说明

项目代码已经是最新的了

**Comment by Keldos-Li** [comment]
这似乎是一个 [setuptools](https://github.com/pypa/setuptools) 的问题。请你尝试将pip更新到23.2及以上。
- https://github.com/pypa/pip/issues/11501

**Comment by fuzhengqu** [comment]
> 这似乎是一个 [setuptools](https://github.com/pypa/setuptools) 的问题。请你尝试将pip更新到23.2及以上。
> 
> * [pip's vendored pkg_resources should stop using pkgutil.ImpImporter pypa/pip#11501](https://github.com/pypa/pip/issues/11501)

Requirement already satisfied: pip in c:\program files\python\lib\site-packages (23.2.1)

**Comment by Keldos-Li** [comment]
那这似乎不是我们能解决的问题……请你尝试自己检索一下解决办法……

**Comment by fuzhengqu** [comment]
> 那这似乎不是我们能解决的问题……请你尝试自己检索一下解决办法……

我自己解决了，之前安装的python是选择all users，所以是在C盘program files目录下的，这里面需要权限。我卸载后重新安装，不选择all users，默认会安装到当前用户默认目录，这样就不需要权限，重新运行就正常了，判断应该是权限引起的问题。另外双击bat运行，还会报最后的缺少ModuleNotFoundError: No module named 'colorama'。不过此报错并不影响执行chuanhuchatbot.py,没有报错，正常运行了。这是否说明是项目并未考虑到python安装到C:/Program files/目录下呢，是否可以调整下
