### ISSUE TITLE
[本地部署]: 选择 ChatGLM2-6b 模型后代码报错 AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer'

### ISSUE THREAD

**Issue by abbish** [GaiZhenbiao/ChuanhuChatGPT#906]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

本地部署启动后，选择 ChatGLM2-6b 模型后代码报错，经过测试所有 ChatGLM 系列的模型都有类似错误，测试了 MOSS、Llama-2-7B-Chat、StableLM 可以正常使用。

```shell
(venv) abbish@ABBISH-ROG:~/Workspace/ai/ChuanhuChatGPT$ python ChuanhuChatbot.py 
WARNING:root:Language file for en_US:en does not exist. Using English instead.
WARNING:root:Available languages: extract_loca, en_US, vi_VN, ja_JP, ru_RU, zh_CN, ko_KR, sv_SE
WARNING:root:无法获取IP地址信息。
{'error': True, 'reason': 'RateLimited', 'message': 'Visit https://ipapi.co/ratelimited/ for details'}
/home/abbish/Workspace/ai/ChuanhuChatGPT/modules/overwrites.py:89: GradioUnusedKwargWarning: You have unused kwarg parameters in JSON, please remove them: {'readonly': True}
  res = original_IOComponent_init(self, *args, **kwargs)
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/abbish/Workspace/ai/ChuanhuChatGPT/modules/models/models.py", line 53, in get_model
    model = ChatGLM_Client(model_name, user_name=user_name)
  File "/home/abbish/Workspace/ai/ChuanhuChatGPT/modules/models/ChatGLM.py", line 32, in __init__
    CHATGLM_TOKENIZER = AutoTokenizer.from_pretrained(
  File "/home/abbish/Workspace/ai/ChuanhuChatGPT/venv/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 738, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/abbish/Workspace/ai/ChuanhuChatGPT/venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2045, in from_pretrained
    return cls._from_pretrained(
  File "/home/abbish/Workspace/ai/ChuanhuChatGPT/venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/abbish/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b/8fd7fba285f7171d3ae7ea3b35c53b6340501ed1/tokenization_chatglm.py", line 69, in __init__
    super().__init__(padding_side=padding_side, clean_up_tokenization_spaces=clean_up_tokenization_spaces, **kwargs)
  File "/home/abbish/Workspace/ai/ChuanhuChatGPT/venv/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 366, in __init__
    self._add_tokens(self.all_special_tokens_extended, special_tokens=True)
  File "/home/abbish/Workspace/ai/ChuanhuChatGPT/venv/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 462, in _add_tokens
    current_vocab = self.get_vocab().copy()
  File "/home/abbish/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b/8fd7fba285f7171d3ae7ea3b35c53b6340501ed1/tokenization_chatglm.py", line 112, in get_vocab
    vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)}
  File "/home/abbish/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b/8fd7fba285f7171d3ae7ea3b35c53b6340501ed1/tokenization_chatglm.py", line 108, in vocab_size
    return self.tokenizer.n_words
AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer'
``` 

### 复现操作

1. 正常完成本地部署
2. 选择加载 ChatGLM2-6b 模型

### 错误日志

```shell
Traceback (most recent call last):
  File "/home/abbish/Workspace/ai/ChuanhuChatGPT/modules/models/models.py", line 53, in get_model
    model = ChatGLM_Client(model_name, user_name=user_name)
  File "/home/abbish/Workspace/ai/ChuanhuChatGPT/modules/models/ChatGLM.py", line 32, in __init__
    CHATGLM_TOKENIZER = AutoTokenizer.from_pretrained(
  File "/home/abbish/Workspace/ai/ChuanhuChatGPT/venv/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 738, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/abbish/Workspace/ai/ChuanhuChatGPT/venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2045, in from_pretrained
    return cls._from_pretrained(
  File "/home/abbish/Workspace/ai/ChuanhuChatGPT/venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/abbish/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b/8fd7fba285f7171d3ae7ea3b35c53b6340501ed1/tokenization_chatglm.py", line 69, in __init__
    super().__init__(padding_side=padding_side, clean_up_tokenization_spaces=clean_up_tokenization_spaces, **kwargs)
  File "/home/abbish/Workspace/ai/ChuanhuChatGPT/venv/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 366, in __init__
    self._add_tokens(self.all_special_tokens_extended, special_tokens=True)
  File "/home/abbish/Workspace/ai/ChuanhuChatGPT/venv/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 462, in _add_tokens
    current_vocab = self.get_vocab().copy()
  File "/home/abbish/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b/8fd7fba285f7171d3ae7ea3b35c53b6340501ed1/tokenization_chatglm.py", line 112, in get_vocab
    vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)}
  File "/home/abbish/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b/8fd7fba285f7171d3ae7ea3b35c53b6340501ed1/tokenization_chatglm.py", line 108, in vocab_size
    return self.tokenizer.n_words
AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer'
```

### 运行环境

```markdown
- OS: Ubuntu 22
- Browser: Chrome
- Gradio version: 3.43.2
- Python version: 3.10.12
```

**Comment by GaiZhenbiao** [comment]
ChatGLM他们把推理代码搞坏了，在他们修复前，可以降级`transformers`来正常使用ChatGLM2：
```
pip install transformers==4.33.0
```
