### ISSUE TITLE
[本地部署]: OSError: [Errno 22] Invalid argument: 'history\\"OpenAI\'s AI Assistant Based on gpt-3.5-turbo Model".json'

### ISSUE THREAD

**Issue by xiekangmin** [GaiZhenbiao/ChuanhuChatGPT#913]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

发生了一个不大不小的错误，部署完成之后可以正常对话，但是会弹出Error框，但是不影响继续对话。每次登陆历史记录都会消失，看错误似乎与历史记录有关。
<img width="467" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/50229337/623c2acd-ba25-4671-85b8-deccda52f2b4">

### 复现操作

正常完成部署，就会出现这种错误

### 错误日志

```shell
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\Anaconda\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\Anaconda\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "D:\Anaconda\lib\site-packages\gradio\blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\Anaconda\lib\site-packages\gradio\utils.py", line 503, in async_iteration
    return await iterator.__anext__()
  File "D:\Anaconda\lib\site-packages\gradio\utils.py", line 496, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\Anaconda\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Anaconda\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Anaconda\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Anaconda\lib\site-packages\gradio\utils.py", line 479, in run_sync_iterator_async
    return next(iterator)
  File "D:\Anaconda\lib\site-packages\gradio\utils.py", line 629, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\1\Desktop\ChengXu\ChuanhuChatGPT-main\ChuanhuChatGPT-main\modules\utils.py", line 36, in predict
    for i in iter:
  File "C:\Users\1\Desktop\ChengXu\ChuanhuChatGPT-main\ChuanhuChatGPT-main\modules\models\base_model.py", line 515, in predict
    self.auto_save(chatbot)
  File "C:\Users\1\Desktop\ChengXu\ChuanhuChatGPT-main\ChuanhuChatGPT-main\modules\models\base_model.py", line 702, in auto_save
    save_file(self.history_file_path, self.system_prompt,
  File "C:\Users\1\Desktop\ChengXu\ChuanhuChatGPT-main\ChuanhuChatGPT-main\modules\utils.py", line 352, in save_file
    with open(history_file_path, "w", encoding='utf-8') as f:
OSError: [Errno 22] Invalid argument: 'history\\"OpenAI\'s AI Assistant Based on gpt-3.5-turbo Model".json'
```

### 运行环境

```markdown
- OS:  Windows11 22H2
- Browser: edge
- Gradio version: 
- Python version: 3.8.5
```

### 补充说明

暂无

**Comment by GaiZhenbiao** [comment]
我等会儿解决下
