### ISSUE TITLE
[Bug]: instruct模型报错

### ISSUE THREAD

**Issue by hengyanqwe** [GaiZhenbiao/ChuanhuChatGPT#914]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

gpt-3.5-turbo-instruct报错：
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/68996932/48d697bb-a75f-45e9-bce2-3de3e2a9ce0b)

### 复现操作

只在这个模型选择下报错

### 错误日志

```shell
2023-10-11 10:10:36,457 [INFO] [base_model.py:378] 用户的输入为：23
2023-10-11 10:10:36,939 [ERROR] [models.py:90] 获取API使用情况失败:API request failed with status code 403: {
  "error": {
    "message": "Your request to GET /dashboard/billing/usage must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

Traceback (most recent call last):
  File "/home/ChuanhuChatGPT/modules/models/base_model.py", line 425, in predict
    for chatbot, status_text in iter:
  File "/home/ChuanhuChatGPT/modules/models/base_model.py", line 250, in stream_next_chatbot
    for partial_text in stream_iter:
  File "/home/ChuanhuChatGPT/modules/models/models.py", line 58, in get_answer_stream_iter
    for i in iter:
  File "/home/ChuanhuChatGPT/modules/models/models.py", line 219, in _decode_chat_response
    raise Exception(error_msg)
Exception: {  "error": {    "message": "This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?",    "type": "invalid_request_error",    "param": "model",    "code": null  }}
```

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
今天我做一下适配

**Comment by hengyanqwe** [comment]
> 今天我做一下适配

辛苦大佬了

**Comment by GaiZhenbiao** [comment]
做好了，拉取最新版本测试一下吧～https://github.com/GaiZhenbiao/ChuanhuChatGPT/commit/e99bd71662ad69f2fa2bc2c85a5b88ae9d48b0d8

另外，这不是一个对话模型，而是一个补全模型，所以不要期待它和对话模型一样表现。你们的“对话”实际上会被合成为
```
你说的话……

模型的补全……

更多内容……
```
这样的段落。
