### ISSUE TITLE
[本地部署]: 本地無法部署原始<meta-llama/Llama-2-7b-chat-hf>模型

### ISSUE THREAD

**Issue by xiaoguowei** [GaiZhenbiao/ChuanhuChatGPT#924]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

无法使用原版<meta-llama/Llama-2-7b-chat-hf>模型本地部署。我看了一下代码，好像只有提供量化版llama2的部署，不知道作者是否有空为这部分撰写部署代码，方便其他使用者可以部署非量化原始版llama2和微调中文版的llama2。

### 复现操作

因为models/models/LLaMA.py里的代码是提供gguf版模型的运行使用，所以无法原始版<meta-llama/Llama-2-7b-chat-hf>模型使用。
我查看了QWEN和chatglm的HF仓库文件发现跟<meta-llama/Llama-2-7b-chat-hf>差不多，所以我尝试先把模型下载到本地，然后通过models/models/ChatGLM.py或者models /models/Qwen.py加载使用，但是报了一个错误<AttributeError: 'LlamaForCausalLM' object has no attribute 'chat_stream>。
也许是我不知道正确的配置方式是什么，所以想请问作者可以提供如何配置原始版<meta-llama/Llama-2-7b-chat-hf>模型方式吗，或者可能代码本身就不支援原版llama2需要作者改写一下代码去适配llama2，谢谢！

### 错误日志

```shell
Traceback (most recent call last):
  File "D:\LLM_Project\ChuanhuChatGPT\modules\models\base_model.py", line 479, in predict
    for chatbot, status_text in iter:
  File "D:\LLM_Project\ChuanhuChatGPT\modules\models\base_model.py", line 288, in stream_next_chatbot
    for partial_text in stream_iter:
  File "D:\LLM_Project\ChuanhuChatGPT\modules\models\Qwen.py", line 71, in get_answer_stream_iter
    for response in self.model.chat_stream(
  File "D:\miniconda3\envs\ChuanhuChatGPT\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LlamaForCausalLM' object has no attribute 'chat_stream
```

### 运行环境

```markdown
OS: Windows11 22H2
Browser: Chrome
Gradio version: 3.22.1
Python version: 3.11.1
```

### 补充说明

可以让本地部署的使用者使用原本llama2的模型，和其他基于llama2的微调模型

**Comment by GaiZhenbiao** [comment]
那我把运行原版LLaMA 2的代码加回来，之前是用llama.cpp替换了torch。

**Comment by xiaoguowei** [comment]
万分感谢作者這麽快回答！！
當然也許有些人沒有那麽多GPU，還是想用量化過gguf版，也許可以在代碼裏同時保留加載原始版和加載量化版的代碼，供使用者自己選擇，謝謝！
