### ISSUE TITLE
[Bug]: 添加的自定义prompt模板读取错误

### ISSUE THREAD

**Issue by max-su-2019** [GaiZhenbiao/ChuanhuChatGPT#960]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

在flowgpt上找到了个prompt，想要将它加到templates文件里的自定义模板中，我将其按CSV格式做了个文件后，发现在浏览器中选择加载这个prompt模板时会显示Error，添加的其它自定义prompt文件却都能正常加载读取，怀疑是不是因为这个prompt的字符串里存在不兼容的特殊字符导致的。
[NovelGPT Prompts.csv](https://github.com/GaiZhenbiao/ChuanhuChatGPT/files/13428049/NovelGPT.Prompts.csv)

### 复现操作

1.将此prompt文件添加到templates文件夹中
1.正常完成本地部署，打开了浏览器
2.在浏览器中加载此prompt

### 错误日志

```shell
Traceback (most recent call last):
  File "F:\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "F:\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "F:\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "F:\ChuanhuChatGPT\modules\utils.py", line 436, in load_template
    lines = list(reader)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 1817: invalid start byte
```
```


### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 


### 帮助解决

- [X] 我愿意协助解决！

### 补充说明

_No response_

**Comment by GaiZhenbiao** [comment]
这个文件是用Windows的一个编码保存的
<img width="135" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/51039745/0419f280-b584-4763-88d1-4933552dd7f3">
转换成utf-8编码即可，我帮你转化了下：
[NovelGPT Prompts.csv](https://github.com/GaiZhenbiao/ChuanhuChatGPT/files/13428144/NovelGPT.Prompts.csv)

**Comment by max-su-2019** [comment]
好的明白了!
