### ISSUE TITLE
[其他]: 提问后，回答总是显示error

### ISSUE THREAD

**Issue by baiyi-os** [GaiZhenbiao/ChuanhuChatGPT#961]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 错误描述

提问后，回答总是显示error
报错如下：
Exception ignored in: <generator object OpenAIClient._decode_chat_response at 0x7f6941a0f2e0>
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 802, in run
    context, func, args, future = item
                   ^^^^
RuntimeError: generator ignored GeneratorExit

### 复现操作

正常提问，连续提问3-4此后会出现这个情况

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 
(或您的其他运行环境信息)

**Comment by baiyi-os** [comment]
帮忙看下这个问题

**Comment by baiyi-os** [comment]
目前发现只有在模型切换到GPT4 Turbo时才会出现
这是在服务端看到的日志：
ERROR: {'id': 'chatcmpl-8T1RojF1zGZRKd3AjIqiXfgDOM8Uw', 'object': 'chat.completion.chunk', 'created': 1701927768, 'model': 'gpt-4-1106-preview', 'system_fingerprint': 'fp_a24b4d720c', 'choices': [{'index': 0, 'delta': {'content': 'host'}, 'finish_reason': None}]}
Exception ignored in: <generator object OpenAIClient._decode_chat_response at 0x7f06195b7120>
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 802, in run
    context, func, args, future = item
RuntimeError: generator ignored GeneratorExit

**Comment by XudongLiu** [comment]
我有时也发现这个问题，可能是接口不问题，不知道您是不是在多轮问答后才出现的这个问题 @baiyi-os

**Comment by baiyi-os** [comment]
我是多轮回答后会出现这个问题
目前两种情况，一种是nginx导致的，其实在服务端已经看到了完整的答案，但是通过nginx显示不完全，并且页面右上角显示error
第二种就是服务端报错导致的
对于第一种不知道有没有配置优化的方法，我当初是按照教程中的nginx配置的
