### ISSUE TITLE
[Bug]: 啟用帳號登入功能時，history如果沒有該帳號的資料夾會錯誤

### ISSUE THREAD

**Issue by ixqkedp** [GaiZhenbiao/ChuanhuChatGPT#965]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

啟用帳號登入功能時，history如果沒有該帳號的資料夾會錯誤

### 复现操作

啟用帳號登入功能時，history如果沒有該帳號的資料夾會錯誤

### 错误日志

```shell
To create a public link, set `share=True` in `launch()`.
2023-11-28 16:14:28,371 [INFO] [utils.py:625] 您的IP区域：Taiwan。
2023-11-28 16:14:35,244 [INFO] [ChuanhuChatbot.py:492] Get User Name: 26666
2023-11-28 16:14:35,255 [INFO] [models.py:39] 正在加载OpenAI模型: GPT3.5 Turbo
Traceback (most recent call last):
  File "d:\VSCode\Python\eGenieChatGPT_Latest\modules\models\models.py", line 42, in get_model
    model = OpenAIClient(
            ^^^^^^^^^^^^^
  File "d:\VSCode\Python\eGenieChatGPT_Latest\modules\models\OpenAI.py", line 28, in __init__
    super().__init__(
  File "d:\VSCode\Python\eGenieChatGPT_Latest\modules\models\base_model.py", line 234, in __init__
    self.history_file_path = get_first_history_name(user)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\VSCode\Python\eGenieChatGPT_Latest\modules\utils.py", line 474, in get_first_history_name
    history_names = get_history_names(user_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\VSCode\Python\eGenieChatGPT_Latest\modules\utils.py", line 466, in get_history_names
    history_files = get_file_names_by_last_modified_time(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\VSCode\Python\eGenieChatGPT_Latest\modules\utils.py", line 454, in get_file_names_by_last_modified_time
    files = get_file_names_by_type(dir, filetypes)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\VSCode\Python\eGenieChatGPT_Latest\modules\utils.py", line 435, in get_file_names_by_type
    files += [f for f in os.listdir(dir) if f.endswith(type)]
                         ^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] 系統找不到指定的路徑。: 'history\\26666'
Traceback (most recent call last):
  File "d:\VSCode\Python\eGenieChatGPT_Latest\.venv\Lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\VSCode\Python\eGenieChatGPT_Latest\.venv\Lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\VSCode\Python\eGenieChatGPT_Latest\.venv\Lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\VSCode\Python\eGenieChatGPT_Latest\.venv\Lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\VSCode\Python\eGenieChatGPT_Latest\.venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\VSCode\Python\eGenieChatGPT_Latest\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "d:\VSCode\Python\eGenieChatGPT_Latest\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\VSCode\Python\eGenieChatGPT_Latest\.venv\Lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "d:\VSCode\Python\eGenieChatGPT_Latest\ChuanhuChatbot.py", line 501, in create_greeting
    loaded_stuff = current_model.auto_load()
                   ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'auto_load'
Keyboard interruption in main thread... closing server.
Traceback (most recent call last):
  File "d:\VSCode\Python\eGenieChatGPT_Latest\.venv\Lib\site-packages\gradio\blocks.py", line 2209, in block_thread
    time.sleep(0.1)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\VSCode\Python\eGenieChatGPT_Latest\ChuanhuChatbot.py", line 799, in <module>
    demo.queue(concurrency_count=CONCURRENT_COUNT).launch(
  File "d:\VSCode\Python\eGenieChatGPT_Latest\.venv\Lib\site-packages\gradio\blocks.py", line 2125, in launch      
    self.block_thread()
  File "d:\VSCode\Python\eGenieChatGPT_Latest\.venv\Lib\site-packages\gradio\blocks.py", line 2213, in block_thread
    self.server.close()
  File "d:\VSCode\Python\eGenieChatGPT_Latest\.venv\Lib\site-packages\gradio\networking.py", line 75, in close     
    self.thread.join()
  File "C:\Program Files\Python311\Lib\threading.py", line 1112, in join
    self._wait_for_tstate_lock()
  File "C:\Program Files\Python311\Lib\threading.py", line 1132, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### 运行环境

OS: win10
Browser: edge
Gradio version: 3.43.2
Python version: 3.11.5

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by angkec** [comment]
Heroku的部署会有同样问题
