### ISSUE TITLE
[其他]: 使用Qwen-1_8B-Chat模型加载出错

### ISSUE THREAD

**Issue by Sooloom** [GaiZhenbiao/ChuanhuChatGPT#971]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 错误描述

服务器部署正常，使用Chatglm2-6b-int4正常，但使用Qwen-1_8B-Chat模型加载出错

### 复现操作

正常完成了服务器部署
使用Chatglm2-6b-int4正常
换成Qwen-1_8B-Chat模型加载出错

### 错误日志

```shell
Traceback (most recent call last):
  File "D:\ChatGPT\ChuanhuChatGPT\modules\models\models.py", line 128, in get_model
    model = Qwen_Client(model_name, user_name=user_name)
  File "D:\ChatGPT\ChuanhuChatGPT\modules\models\Qwen.py", line 12, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(MODEL_METADATA[model_name]["repo_id"], trust_remote_code=True, resume_download=True)
KeyError: 'Qwen-1_8B-Chat'
```

### 运行环境

- OS: Windows 10 22H2
- Browser: Microsoft EDGE 119
- Gradio version: 
- Python version: 3.10.11
(或您的其他运行环境信息)

**Comment by windark998** [comment]
同样咨询该问题。加载 Qwen-14B-Chat-Int4模型时，始终提示keyerror错误。presets路径、configure.py和json都做了修改依旧无效。
Traceback (most recent call last):
  File "C:\Users\Administrator\ChuanhuChatGPT\modules\models\models.py", line 132, in get_model
    model = Qwen_Client(model_name, user_name=user_name)
  File "C:\Users\Administrator\ChuanhuChatGPT\modules\models\Qwen.py", line 11, in __init__
    super().__init__(model_name=model_name, user=user_name)
  File "C:\Users\Administrator\ChuanhuChatGPT\modules\models\base_model.py", line 225, in __init__
    self.model_name = MODEL_METADATA[model_name]["model_name"]
KeyError: 'model_name'
