### ISSUE TITLE
[本地部署]: duckduckgo搜索超时

### ISSUE THREAD

**Issue by slideslide** [GaiZhenbiao/ChuanhuChatGPT#984]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

我确信代理规则中有duckduckgo.com的主域名但是通过这个包进行搜索还是超时，下面涉及的包我都尝试更新到了最新版但并无作用。

尝试访问lite.duckduckgo.com
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/86949124/f9c5adcc-fbc7-4ef8-97e5-6e601154438f)

### 复现操作

1.正常完成部署
2.勾选在线搜索并询问
3.出现报错

### 错误日志

```shell
Traceback (most recent call last):
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\curl_cffi\requests\session.py", line 695, in request
    c.perform()
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\curl_cffi\curl.py", line 257, in perform
    self._check_error(ret, action="perform")
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\curl_cffi\curl.py", line 112, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to lite.duckduckgo.com port 443 after 21008 ms: Timed out'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\duckduckgo_search\duckduckgo_search.py", line 42, in _get_url
    resp = self._session.request(method, url, **kwargs)
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\curl_cffi\requests\session.py", line 699, in request
    raise RequestsError(str(e), e.code, rsp) from e
curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to lite.duckduckgo.com port 443 after 21008 ms: Timed out'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\gradio\blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\gradio\utils.py", line 503, in async_iteration
    return await iterator.__anext__()
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\gradio\utils.py", line 496, in __anext__
    return await anyio.to_thread.run_sync(
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\gradio\utils.py", line 479, in run_sync_iterator_async
    return next(iterator)
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\gradio\utils.py", line 629, in gen_wrapper
    yield from f(*args, **kwargs)
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\modules\utils.py", line 36, in predict
    for i in iter:
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\modules\models\base_model.py", line 550, in predict
    ) = self.prepare_inputs(
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\modules\models\base_model.py", line 470, in prepare_inputs
    for r in islice(ddgs_gen, 10):
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\duckduckgo_search\duckduckgo_search.py", line 91, in text
    for i, result in enumerate(results, start=1):
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\duckduckgo_search\duckduckgo_search.py", line 276, in _text_lite
    resp = self._get_url("POST", "https://lite.duckduckgo.com/lite/", data=payload)
  File "J:\bots\chatGPT\long3\ChuanhuChatGPT\ChuanhuChat\lib\site-packages\duckduckgo_search\duckduckgo_search.py", line 50, in _get_url
    raise DuckDuckGoSearchException(f"_get_url() {url} {type(ex).__name__}: {ex}")
duckduckgo_search.exceptions.DuckDuckGoSearchException: _get_url() https://lite.duckduckgo.com/lite/ RequestsError: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to lite.duckduckgo.com port 443 after 21008 ms: Timed out'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
```

### 运行环境

```markdown
- OS: Windows10 22H2
- Browser: Chrome
- Gradio version: 3.43.2
- Python version: 3.9
```

**Comment by slideslide** [comment]
已解决

**Comment by caramel678** [comment]
大佬，怎么解决的，求指导，谢谢

**Comment by Denticle** [comment]
我也遇到这个问题

**Comment by slideslide** [comment]
建议检查以下事项：
项目是否为最新版本
chuanhu文件夹中duckduckgo版本是否正确
代理规则是否正确

**Comment by jamsnrihk** [comment]
我下了最新版本，也遇到这个问题
