### ISSUE TITLE
[其他]: 在本地部署的时候，修改对话名称的时候会报错

### ISSUE THREAD

**Issue by WanZunGe** [GaiZhenbiao/ChuanhuChatGPT#991]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 错误描述

在本地部署的时候，修改对话名称的时候会报错
而且，我导入自己的历史对话的时候，第一次对话总会自动修改我的对话名称，能不能在对话命名选项里加一个不修改对话命名的选择

### 复现操作

正常完成部署

### 错误日志

```shell
Traceback (most recent call last):
  File "L:\Anaconda3\envs\ChuanhuChatbot\Lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Anaconda3\envs\ChuanhuChatbot\Lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Anaconda3\envs\ChuanhuChatbot\Lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Anaconda3\envs\ChuanhuChatbot\Lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Anaconda3\envs\ChuanhuChatbot\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Anaconda3\envs\ChuanhuChatbot\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "L:\Anaconda3\envs\ChuanhuChatbot\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Anaconda3\envs\ChuanhuChatbot\Lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "d:\Microsoft VS Code\my project\ChuanhuChatGPT\modules\utils.py", line 88, in rename_chat_history
    return current_model.rename_chat_history(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseLLMModel.rename_chat_history() takes 3 positional arguments but 4 were given
```

### 运行环境

- OS: win10
- Browser: Chrome
- Gradio version: 
- Python version: 3.11.5
(或您的其他运行环境信息)

### 补充说明

没有

**Comment by slideslide** [comment]
挪走当前用户的历史记录创建完第一个再挪回来就可以暂时解决

**Comment by WanZunGe** [comment]
> 挪走当前用户的历史记录创建完第一个再挪回来就可以暂时解决
不行哦，我挪走所有历史记录，然后重开新建一个对话，新建的对话依然无法改名，改了会报错
